; generated by PrusaSlicer 2.4.2+win64 on 2022-05-19 at 02:55:47 UTC


;
; thumbnail begin 128x128 11152
; iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAgcklEQVR4Ae1dB1yUR9M/uoUidlBQ7B
; 3svSL2EruxG2J781kSX1ui5o3GxB67YhQbxqix94JRE1s0RlRQUFQQadJ7u/99N4uHd8eVp9whGCa/
; +Ung7nl2d2Znp68E70AqleL27dto1rQZJBJJgaCZqRkGDRqE1ORU+QDYGKTgCPv374e5ubnG5zpVc8
; L+X/cjKytL5zM0vU8mB/rn7p27aNumLXte+XLlMXrMaFy7dg0paSkQC/Tavbv3wqmqE0xMTLSuj421
; DRZ9uwgJCQnKY9M6dl3vu3zlMho2aZj/ffSB9PR0rFixAnZ2dgVG/DwmMDPD+nXrkZ2ZDT5AxJ01ax
; ZjIsWzTM1M0WdAHzx7/kzfgmhcPFrgjIwMrF29FmXsyuQbq4WFBerWq4uly5YiMDAQoCHngBdERkTC
; c4InSpYsyXl9unTpgvv/3JfpGjsXiIqOgudkT5hbKG2coKAg9O7dG6ampgVO/DxOt7PBzRs3eU1GKv
; 8vMjoS3d27s0Wys7fD6p9WIyVV8A6VBT8PxoB+A9jztI7XRI5mEpQsXRKfDPgE+/btQ1xiHLjQ5fLF
; y2jUsJGgta5cuTK2em2Vpqalgi8oS47MzEz4HPBBVeequc92cHAQSjipwb5jKoFbczfOC6kMQU+CMH
; joYNy6c0vn53TtnJycHBz69RCcqjjxXgczczNUrFQRU6dOxZ9//ImM1IxcyaAESUlJWPj1QtiXsVf5
; ri7x/w5l6hJoxMgReBXyCmIh6Jl84/frTc8VRHzDM4p8Z02fOR3GAF0iPzo6GlMmTUGJEiVEz5WOoD
; at22DdunUICwtjzPzo4SN07dxVRaqQBCDd59dffkXjho31ET7f+tWpWwfHTxxHdja/Y1MdSFryZQAh
; u54zlipVCocPH4axgQhPxPnz+p9wbexq8HmYmJrA1t4W3Xt0R8UKFVV2ermy5bBxw0aQrkEEDA0Jxe
; effQ4rKytNxNeKpEN8NfsrxMTGaJwf17XgygBCCc/7e1WrVmXiic54MaBr16empmLJ/5YwLVvgvLih
; ier/t2vXDg8ePFAfJ1JSUvCLzy+o4liF17qRJGnTtg1u3LzB6+hUZhAuDGDUXZ9vUiZyTb5XH8TFx8
; EIIPP394dHN48CVXpLly6N+fPm55lzmoCUswD/APTr00/Kd2xly5bFmp/WyOQiXefO12RGSiQGmKCh
; kZSdVatWMeWMD+ja9SRud+3chUoVKhXoXOrUroML5y9o3aHKRKH5xsfHY+XylRrNUF1IPpH+A/ojMC
; hQ73uU16lQMgAhLcDVa1dhCOK/CXuDsaPHwtLCssDGTwQZO2Yswt+Eg+/YyS9z68YttGnZhvd7XVxc
; 8MuBX5CRmcHpXYZiAKMcE66NXBEfGw+h6gDtKNp9tAuNMT5tWKlSJXh7e2vV0rl49LKzsrFn1x5dPg
; mtyiIplJOnTCbHj15l0BAMINXys2gkL9+UyVPkbj9oZAJdu57+Xb1mNUpbl4Yhx6QPPbp74MmTJxAD
; yUnJmD93PiwthUsssjzc3Nzge8VX51FqCAYwCvGVufnQwUP5zlAuLtEbf95gfnxjjEsdbW1t8f3S75
; lGrwm4+vHv/32f+RI4OIm0oYoPgca1ZOkSJCYmwtgMYByUewkrOFSAn58fdIEm2zcjOwMbNm9g3jpj
; jrFJ4ya4fv06J0VPG9C5v2nDJtjZiorHaHQg0THi7u4Ov4d+AhjARKKwZwvUHFRG8rBRvCI2PlaaI8
; 3htcBpaWmYPHUyTMxNDD4ukk7Tpk5DdFQ09IGuXR8SEoKBAweKMU3V9QGNtHJ0dMQO7x1IS0/jyADy
; 3efeyx0bNm2AczVngy8gD5QSF69aswoZWRmcCK8McXFxaN6qOZuPocZEDquDBw9y2vW6FL2jR47C2c
; lga6t3k5JeMWbMGISGhepgAPmOL21XGstWLUNCcgKycrIQHBqMQUMHGZvQOidlXcoav1/9Pd8C6wNa
; f//H/qhQroLo8dAuHThgIIKDg7m8V+uuj4+LxxfTvtAdeRS4TvqQ9Iv69evj1JlTGhhAvksaNW2Eaz
; evQVnc0s8JKQnYuHUj8zwZkMCc0cLMAm6N3GRREVHgA0QH8r0f8DnAniH0/fb29li7Zi07r4UCjYVC
; 366uWmMQMgm/cQk+min2osIAZpZmmDZzGqJiorRyb2ZOJu4+uIs27dpA6ItFTEpmZmLGEirSU9J5+w
; cyMzIxdcpUSMwl+fz0+rB1q9a4d++eXpGva9enpaZh+Y/LFQtvzHXig7mLUbW6/Ew7dhCZWZl6TSyS
; BtFx0Zj/jdxWtSow71rezihhVQJ79+7lnTtAEJ8QD4+eHuw51lZmqGxjpXuXlCyF2V/NZnqEPtC1bk
; GBQUwTF2HeGQnlIr//kP4IDgnWuqCaJkbRuvSsdJy5eAa169Q2xGC07vp8v5OPuaJjRXau8wUyDZ8+
; e4o+LevhzGctZIS96mrWDWrUqIEzp88IYjQFUJCHIn3kHSxYwnLEdVvWITk1WXCuGZ2HR48eFeW14k
; V8BcqlloeHBxISE3gTKPDXVbJr01qr4IJuNWQkEejZpJh9OvJTvH79WuP3uTp1yDwcN3acNkWP71lv
; HNRkV3MBci9SyHb5yuWwsTF4XJ3z4iz9YSkyszM5jTk5NBB3Fn6Sj/gK3DmssaxLAyds99quNaOYC/
; FpbXwv+aJunbpi5qczK8hgqG8ymoAWJ+BJAHr07CHm5fx3vQYsaV0Sl30v6x3za98D0EZ4Zfzjy26y
; 15cPIDs1CeqE56LopSSnYNE3i2BlaSVmbQpOOoAHsOyV1BTs8dmDyg6VjUF8jUi2N71vzLgxsLWzVf
; 27mQQNGjbAy5cvNVoFWXJCPlg7TcaF+MpI30l7+0bTGmgl/kO/hyzrx1B+fElBeF/BESi0GfYmDBM9
; J7KcNwMPRCvHU1y9q3tX+D/JVfhu3roJN1e3fJ/znOiZm5GrRJ6Im6fAl/DKeOMrd1mY7wG9DqeM9A
; x4bfVifgIDrYFGwpewLAHrEtYgU9hga69vcgonyoVLF1Cvfj0xL+Ml8mkXkW7x3dLvkJSsKo5jYmIw
; ffp0FcWTPk9nt2KDPt2zRCaG+OrSIEvtSFAAJZsMHTLU6ClmlC9IqeuUZeze1R0WloIcWlJeDEDKDC
; 32wsULDZI2zRVJa27i2oS5fXWYpsz6UPajV6xYEbfPH9Wp6ImRBm//eZ+hRBLxxPETqF69uqHmrXGD
; EGNRscrzZ8+Rk52rsFPIefGixUziiGY8bcQn+/Ufv3/QoWMHg09KF9Kupujd27dvwQVCXoVg8KDBTA
; J81toJhia8OhM8P7SWSYOgp0FwcBRcVKO+RhrXidLiqEyNspg1bYTfr/yOxo0aa62RFMQA9CKqZNnq
; tRXly4tKptA0KZlEi8gnTqaI44GDB/QWdapDXPBjnJnhITMm8ZXx3rIxMjIpXzx/gR7de7BMZqX5iV
; 0jhq1btsbdv+7qLf6IiorCJM9JLPNYkPKp/DB62cuQlxg2YpihCa9zcYiD+/bvi+cvnoMvcDXvjCEN
; 6N0UX1i7ai1zGXNYG72KHhV8zJ41mx29fBxc+332w7mqM//oIn2ZXkSJE8dOHINLDRcxxOcy8Twkjq
; XI4tqfcsUcHyAxbEhFTygqzMV7d+7BrYmbYMIT1nCpgVMnT7HjVwg8C3qGvr36wtLMEiYSjtKAPIFR
; sVH48r9fsnx8gQTmveuJU1u0bIHbf90GX9Dn0fsQ0oAUxOTEZMz4Yob6mayX+PT5kcNH4tWrV7xrIR
; QgzZEi7m0cxo8dD3NTHjoBBXWeBj5Fx/YdhToweJt3rK7tv18Jqv4hJaywEF4daWwZSfE4e+osqjlV
; 47R+5cuWZz4EMrWFBp2ot8L1K9fRsF5DmJvxVAgVD6GKlHlz5jFlQgATcEJS9GrWqomTp07y5nTa9a
; R8FVbiK5ApiK8DWTHKoAGDaM5SbRuhS6cu8HvgJ7jKlxiG8iL+t/B/KFWilGGUwHNnzqFeHb0OH94i
; n46X4SOHM28iX/hQip6YI4HGnJYQB68tXrCzUc30tS5tjcULF7NUbaG7PicrB08ePUGXDl1gaS4iEq
; vp4VSyrKOUip/Il7uNK1WuBK+fvXinUpGi93jbnCJDeHVUKIiP/R6jXevcGEGDBg1w5fIV3qauMmSm
; Z2Kn106Uty+vbIIajgHYS+SaqPcOb1SqKDyRgZSbjp07wu+RH+9JklJFO6koEVybNKCYBKWD7fh5B9
; 68eSNK0Yt4HYGRQ0eyuIAowutjAPbCdx0uerj30OZy1KroWVtbsw5XiUmJvCdaGMw7QyPNSVs8gQtk
; ZWbh4tmLqOVSS6Uxlg7k5pTi8vLk5GTWUMHWxlbvA8m8a9CoAS5dvsT7fCts5p2hkRRE5XgCF6A1JP
; Ny9szZKGVlsGRS/QygHvcmBfH61evk7NCp6FG4mNqR8YWXp7YXKUVPKCoURC7SgApHHtx7gFbNWolK
; Z+fNALqqbiMiIvI1VaLjoapTVez12cuyivkA86IVAfPO0Kgt4SSXAHIdLC0TG9ZuQBmbMsbNJOZCJP
; UqHNJgDx44yHzPJmYm6NW7FwKfBYIviE3Y+FikgTKweMyLl+jbsy+sLKxgNMKrM4C+Wnt1oI9TKHbP
; nj1MR+ALH6OiJxQVCSe0pidPn2Qp5AXWw0hMSbMQ+NgVPaGoiCckxCdg6uSp/F26ApAx2ZLvl7D4f0
; EQvzD78QsLKuIJJ46eQFXHqoYgtEbHHVl038z7Rv6zuQRd3LsgICDAqLv+36joCUVFwknoq1D0691P
; +TgQnS7OKoPr1selc5dYo2sJ+4MZ68Iho+YBYlyUmqCo+fELC76PJ8Ri84bNBmlqaWVlJZ0wdgIiwy
; LzsqcleZxlKucOCxOMGjsKb8LfQCwUdT9+YUGFufjgvtwf0LwVF5NQc3eQyo7Yu3MvpNmqOp8k34fl
; 0qBm3Zo4e+6s4EhVfOC9j8KPX1hQEU9ITUnFnK/mwMKcu1OIPLO9PORmun9gvrsN6MiXaPyiXBpYlb
; bCnHlzWJ4AHyhW9IyHZDpnJCfg4rmLLH1MH/GpPf0PS35ARkqG1l4KEq0PoAYKcgWxVdtW+Pv+33oJ
; X2zeFQwq4gnUJWXksJEaA0N0TDR1bYqb12/qvdFEoleMyI8E+wr2WL9hvUp3KWUoVvQKFhUKYnpiHH
; bt2KVyEQVlJ38x5QvERsXm2/WarDz9DKAkDQYOHqhyW4XQwstiNAwqFMSnAU/RuUNn1KpeC8cOHct3
; Y4k4CaAmDZyqO+Hwb4cRfuNk8a4vBKhcn8CaZ3HY9cIZ4J2C+I1H7SK1SP8G1FTAysWxx4sBapUvhY
; Nj3IrUwvybUBFP4HVlTPVq1XMLGfS0TZvQokqxyC8iqChg1Qd/3fsLEsorp0sQt/+8HRM8J7AOksq1
; 57TrqXdOUVqAYnwfT9AEVIa3fuN6dhehcj4Aa6GWlpmGF69esD58/3FvUrzrizBqSjh58fIFBg0e9P
; 7mUk0cwvz4W4v9+B8LkoKYHBmKQ78dQq3atVRrF9WJX+zH/zjR9z/tZR71HTVfHq2AYj/+x4/T21fL
; a4iZxwD/1szcfyuSUp/XI5kYIPyZPy4u+UzmO6VVkZpIMQrDb9xrymyszN8zANUBXjx/BmNau8h+G9
; e0SE2mGLnj8QnNZH3rV1RNK0tKSMKPy39ktXz0i5rlSmHjJw2KpcFHhkRTR1ur/DmF3Ty65fMCljA3
; xQhXB9n5z1sWqUkWY368NLmlbEyzKrqSSbW7f0ka7BrRpEhNuBjf46GxTWXL506TlSlbBqYWptrc/b
; pjACQNZnasXnwkFDE8PHuILDLsZW51cXIy9h/Yz/I5bGxt+DGAggnca5eDz6euRWoR/o1Iit6VPevz
; eXfZDS+Z6ewSjJ9//hldOnZ5V26uOwqoODtYqnFVuxJY3a9esTQopHh2wXBZaOBj6AJFQyrqO0xBQE
; mvPr3YDZhaCJ9H/GIFsfAiKXpXf/5BUFWXhCqBwsPDsXL5SjR1a0rNmmVcGg0qzMWitFAfIx707CC7
; cfoQhEJuLIDyyEgy5IBdarhg7gJpowaN9JYokzSY3Map+Ej4QLh/1iDZ2zehEANaG0TQ3Td08dG0Kd
; NgX9aeJYRqY4T21e2LFcQCRFL0ejRxxt9//527cYXfaqenQURO7sMTEhKwa/cuDBsyTCUHXRkryYML
; S3vWKZYGRsbvetSWlSuV27+xQ/sOSIzn34UtHwNwuTGMzAjq/xMaGoodO3ewNqclzEvIlI8JOhKGNK
; 5cHE8wAmr048vx+2Xfi6ro5nVrGIHCjJDzjOzp06dYunQp6/qd12ncpFhBNDTSWla3L6nRnUvNuqjF
; PPj2npTmIm8GUAfqekkChNq+z54zG04uTqx2gKTB+BZVis1FEUjm3bS2zjJLM93KeK2atRARFsGLCd
; 5GvkVcTJx4BlCHeGpvcuYERo8dDTs7O2kLpzLFCqIAJJHfrIr+xpwKqTvwk4HIyMzgTKf0jHQs+GaB
; YRlA/VrV6LfR+O3Ib5g28VMs8ChWELmiSsIGRwawKmWFTRs28ZICVPpvcAmgCbJzsvH8WQBOrZkvOz
; OlXZEiRkEi7frutcsL7gNUoWwF3L17l6X3SznYhnR8a2UAusGCkA9wsSZC/G7j1Kw+xdJADdf0r5dn
; 3onB9u3bIyY2BlxBIwOQKKfLCdeuWYtfD/6a1whSxyWOvFwRaUkJuLlrebGCOI1TwgYvpHsXZ86ayd
; k0lGgivuLnpMQk9B/Qn8UINm3ahMiYyHxXtUuFNhKSQ+jDOzg2pWORIpghcf8oV1mjyjYGvSmc8v7p
; 2p8TJ05wun1Mrw4QHR2Nnj16soc7Ojpi5lcz8dD/IfkDpGKIrwCSBldWz/zXHQlzutTgp+jxRKoAom
; Ye+iQBJyUwPCIcLZq3yOMwy5KWUvfu7ti9ezfTJLNysiCWFx6e3ovT0zoXKSIKQVL02lQrYzTCK1sG
; w4YP09rWhxcDEIGfBD2BcxVnlQsJiRnoetmp/5mK69evswCSGIgODsClhSM/Wmmg7McvCAYwMTfB6l
; Wr8y6dFswABLTDjx87DutS1lpf2rRZUyz7YRlevnoJoaBQEC/P6FqkiKtv12vy4xcE0sVS9+7e07re
; Ei6iW3HW03myaPEi7XkClF4mdwNTjcGQQUNw9LejSEtJE3Q8kIJI5mJRIrQmfOfHL3DCK2PjBo0RGx
; OrcZ0lGamqTQTVvXnqX0hOScaA/gO4vVzODA5VHTBnzhzcv3cfWWlZ+VqV6gKmIG78ukgeCWTezexQ
; Xa8fv6BwxowZ7OKpfAywYvkKjTtUl4b//NVz1KxTU29bGWXJQC1L27drj+3btrPMVD4WxMNLR4qUgv
; hO0fsgIl8bUkOIw4cP57uyTmJvb49r166pEF4fcejPJ06dYO1k+Q7k3Y3h0lGfjsKFixeYrUoXWOu7
; uIIKWP9YO6vQSwPefvwCxDp16rAbxlUYwNTEVEZnxJsIdqEhZ9uePrZ6zWrBgyFGoE4VNWvWxHdLv8
; ObSP0dyulIuL7jx0KpIH5IRY8PDh82XOWCEAn9ksTzF9O/kFLhAB+gZkOjRo0SNSBSKEeMHMFu1OQK
; CgWxsEiDd4WX7+dl+g4lubenmsr1gFKlSjExTK1c7e3sWcdvuvOX11XvBkDaeKtXrs7TxYgBKO9fSh
; k9FLrlA3SeUIpYkyZN2CT5DoZ8CF7bvQSlNBWGeILCj08biHzwDpUd0M29G76c/SU2b9nMWu5TKza6
; f+FtzFuGCYkJiI6NBt0u/tT/KXwv+2Lf3n1Y8PUCjJ84Ho0aN2KuXHqeMa6Lo2cSM969fZcllEqU/1
; jNuRqCgoJ4mW302Zs3b+ZmDvMYSKfOneDv7w+x8KHiCVR42baOI0YOH4n1a9ezDF26JpdiJdlS/tfB
; 0zqSPkRIDHP8+HEsWrQIbdu2RWmb0jqzsoUgdROPj42XqjAAcfKAAQPYRPhecLxt2zaYW+gXZ8Tdix
; cvFnSnsNJiqagqBR1P8J7UQ3bQZze7RJMlYAi7C5rrXBESEoLNWzfDw90DVpaGuUuQJMEkz0mqEkDx
; h1UrV/F23mRnZMPzM092Xby2l9arVw9XrlyBUKAxkcu5a9eu+HrB13gS8ERlnMaOJ5Cid8n7JxkfX4
; ahgOZJdnzI8xAmGVxquIhmgndNQfL/oUyZMvD19eU1QHImRUZHwq2FW76zixQhT09PREXxv1NYAaS5
; kpvZxia3vJmUR1KqOnfuLN27Zy9i42JZxrKx4glcCi8LBN7xHgXh9u3eBzc3tzyFUyDm/yXdQkEXFE
; VGRfKWBHQWOjg65D3LwcEB+3z28T5S8uYrf39AQIC0e/fuWpUi+n3FihUxdepU5vdOjIvBTW/DKIhi
; Ci+NDnTHcEYmjvx2BK3btNZVyiflxQBsUeVRv0lTJuUmFeignbrfgP53v89+Zu7QncLPnj+DUKB379
; q1S1rZoTLnCREz0K5Ys3IN7pw/LiqeQIWX/1w9j0IPcgokxiVip/dOVHepzof42hmA0KKEBfbt28fr
; BgomouRW3dXfryItLQ1CITw8XDpu/DhN5qWuCak4YuiuvQH9emP1OHfeR8LRheNlqUkJhXPnawBKAq
; Vk0IioCMydP5dMPX2E188AZHpQO/nHDwvu7KOj4tz5c9I6detwPcN0o0nuPDrXrsipPoEUvVtHdsEQ
; QNnQ6VnpyMrOTZhRFNEYG0gqk2nesmVLLr4E3QtI+oBHDw9ExUYxn70xgRQbcojkdbLmLsY4ob4C1u
; Nzh5KiJ3jXE3FJb7pw4QKWLlmKzz//HB7dPNCubTs0bdoUzZo1Q6eOnTBixAhmxXjv8Ib/E38kpCTk
; ra0YBlE/jklxnjN3jkr7f94MoNhFK1asQE5GjlFsXhr3/X/uo137dkbxfimjpgJW2vUXty3jTXjFel
; MGtbe3N/r068OaMNEcSIcyMzHTvrHkf6PPkOLm7OSM0SNHw2ubF8LehCE9PZ13ybe2GA5JoWMnjqFK
; lSoiGECSW4SoHDU0FJCesGnzJuYWNgCBOUkKItCYfu44PqOnbN+EdrKn926CL7DuW+nJ2LJtC2rXrp
; 3LuFzD4xpQHpRj/1qXtsbgTwbj4C8H2VXyhoJHjx6hZYuWwhmAbM2GjRsKMg21AXm4Bg8ZrLcTiSGJ
; T84POmbiEuKYB1EI0Fnu+7svOnToYDSJRdKhQf0G2LxpM2JjNWfz8MmpyMzJREhYCHr17KU+Zu6DMj
; M3A2nmXPLN9S3gkaNHNJksulB0qLVhg4Y4f/E8U8qEQmJiIpYsXQJbW1uIHQ9XdHFxgZeXF3u3mCOY
; YhTh0eEsJKx04yi/wVBHMe+d3hAKMTExmDFzBot2FdQC0pjHjx+P0DBx/XT8HvqxaB/FTApq7AqkXd
; uiRQucO3tOmpGeIdixRrpFWnIaevbsqbg5hP9gSKF44PeA91FAn6e7iKwseAU0RO18RwdH7N6zm1fp
; tDpQbj11RaHCGIHjMIgVQ8+hjTNp8iRERkaKksSR4ZHo0rkLJOSx4zsQ4py+vfoiNjoW0hx+TED9Az
; 4d/SmX8KYowpNe0atHLzzyfyRKZ6GimNFjRr/vgFJIsFatWvjjzz+YxSB0fpQeJjl57CSnq8jVkc6Q
; FT+uECSKIiIj4OrqatQFql+3PoKDgyEWKFWu3+B+YgMuRkEKrVNaHjPPBfI4KwwJeRnCriJXuU2KA5
; LDhriQD5Dmmp6djhu3b+RF9ozJBBTVFHxevoPk1GT8tPkn2JWzE2XqCUC9RwfRbNbMWSw9TwjkVQZR
; rHnb5m0oX46HPS7fFfUa1mMZLOpE1vVS5rfOyMDefXuNrgyWLFGSed1SUsWVrZGn7s79O2jepnmhkw
; Z03JGSm5ScBL6gUhpGdPO778dawHG1bylYM9FzIus5wxfICTR50mQZX8nDF2ku1FOPtHixPoyY+BjM
; XjAbFiULl05AOG7COKSn8aODxtrA5MRkLFqwiHmluLyYdrHcFapxZfVJg5ioGFYwovZMQ2nNKli2TF
; mWukb9DsUA+RFOnpPrTnVrGPJIED1nM0szZmLzAa3FoVRR6nvRFw3rN+T0ckr8uP/3ffACOWtQetVj
; /8eo6lTV4ATXhCRthgwegpDQEIgB4uvQ8FCMGDvCEAmbBmN4CoH7+PiA9CwuwTu91cHhYeGYOG4ip7
; O6Z++eee1ktIGmq80pk9Znn0+BOodcqrng1KlTLFgiBshHsM1brjtVLi9UGhhc2jk7O+Np4FNOjaIk
; ugijgOysbPjs9mF577peTPrAggULIM2U8jZLSAmdP3c+tZ/NC4wYG8lDOHPGTJarLwZIGjwMeIhO3T
; vxURCNcswRkpQbNXoUp3oLXv0BAgMC0btHb53BGyo6OHP6jMp3dTGXMlA+QKdOnYxOeGVkLtZmLXD7
; zm3RCiI5uRZ/vxglrXmXgxucGcjEJm+tPuDdJzA1JRXLv18OO1s7zS9/ZxpSxZAu0KQckteuXad2gq
; qMRC+Y/OykbhpiXMYEdO5eunYJ9ZrU++Dm4vSZ0/UytaBGkeRYufXnLTRv2lzji0mEjxw6kpl5XBQR
; MiEpodHJ2emDEF+B5N3s07uPqERWAjp7KermOc0z97q2DzEfuT5Sv1F9lqqvCyRbtmwRHFR4G/0W/z
; ft/5izRW0AzLbfsWtHvrZy6kBOpDHjxrCj44MslAZ0rOyIAwcOiAobE5A08Tkk152cHArag8jyCWyt
; bZkyqAskdAYOGzoMr0NfQwhQMcaxw8dQ3bl6vkFQgcnDhw81fo+kyJmzZ9CgYYNCF2iRUNTNwpJVOl
; G/Y6GgKGELDA5Er/69CvRIILqWtCyJU6dPsSZf2kCi+AJl/544fkKwIvQy+KWM+gKpx8rbtGnDbhxR
; fm58QjzmLZhH3cSNngMoFunupKvXrvKOJ6jrOIkpiVi5biVs7G0KRhrI30HHz+mzp3UWq0qUv0Q7UR
; 5YkGpLQdIHmemZ2LhuI8ral817JjHEooWLWK0AmYZ3791F+w7tVa6qo3zDiZ9NxLw58+DW2I1vvoDR
; kULm3377LVLThAVcFED60I2/bsC1hWuBSANLK0s8DtCd0v//7xInPXz5pFUAAAAASUVORK5CYII=
; thumbnail end
;
; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

M107
M190 S60 ; set bed temperature and wait for it to be reached
;TYPE:Custom
;Begin Start GCode

;set temps
G10 P0 S210
G10 P0 R170
G10 P1 S210
G10 P1 R170

G28 ;home all axis
G29 S1 ;enable mesh


T0


M116 ;Wait for all temps

G90
M98 P"prime.g"
;End Start GCode
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
;T0
T0
; Filament-specific start gcode
M703
M107
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.2

G10 ; retract
G1 Z.2 F10800
;AFTER_LAYER_CHANGE
;0.2
M800 F"layer"
G1 X146.015 Y141.693
G11 ; unretract
M204 P1000
;TYPE:Skirt/Brim
;WIDTH:0.42
G1 F1200
G1 X147.06 Y140.817 E.04107
G1 X148 Y140.623 E.02888
G1 X182 Y140.623 E1.0234
G1 X183.307 Y141.015 E.04107
G1 X184.183 Y142.06 E.04107
G1 X184.377 Y143 E.02888
G1 X184.377 Y177 E1.0234
G1 X183.985 Y178.307 E.04107
G1 X182.94 Y179.183 E.04107
G1 X182 Y179.377 E.02888
G1 X148 Y179.377 E1.0234
G1 X146.693 Y178.985 E.04107
G1 X145.817 Y177.94 E.04107
G1 X145.623 Y177 E.02888
G1 X145.623 Y143 E1.0234
G1 X145.997 Y141.75 E.03926
G10 ; retract
G1 X149.413 Y144.413 F10800
G11 ; unretract
;TYPE:Perimeter
G1 F1200
G1 X165.587 Y144.413 E.48684
G1 X165.587 Y157.757 E.40165
G1 X167.243 Y159.413 E.0705
G1 X180.587 Y159.413 E.40165
G1 X180.587 Y175.587 E.48684
G1 X164.413 Y175.587 E.48684
G1 X164.413 Y162.243 E.40165
G1 X162.757 Y160.587 E.0705
G1 X149.413 Y160.587 E.40165
G1 X149.413 Y144.473 E.48504
G1 X149.79 Y144.79 F10800
;TYPE:External perimeter
G1 F1200
G1 X165.21 Y144.79 E.46414
G1 X165.21 Y157.913 E.395
G1 X167.087 Y159.79 E.0799
G1 X180.21 Y159.79 E.395
G1 X180.21 Y175.21 E.46414
G1 X164.79 Y175.21 E.46414
G1 X164.79 Y162.087 E.395
G1 X162.913 Y160.21 E.0799
G1 X149.79 Y160.21 E.395
G1 X149.79 Y144.85 E.46234
G1 X149.697 Y144.401 F10800
G1 X148.787 Y143.787
;TYPE:Perimeter
G1 F1200
G1 X181.213 Y143.787 E.97602
G1 X181.213 Y176.213 E.97602
G1 X148.787 Y176.213 E.97602
G1 X148.787 Y143.847 E.97422
G1 X148.41 Y143.41 F10800
;TYPE:External perimeter
G1 F1200
G1 X181.59 Y143.41 E.99872
G1 X181.59 Y176.59 E.99872
G1 X148.41 Y176.59 E.99872
G1 X148.41 Y143.47 E.99692
G1 X148.796 Y143.514 F10800
G1 X149.121 Y144.121
;TYPE:Gap fill
;WIDTH:0.334364
G1 F1200
G1 X149.1 Y144.224 E.00245
;WIDTH:0.291684
G1 X149.1 Y160.776 E.32866
G10 ; retract
G1 X149.121 Y144.121 F10800
G11 ; unretract
;WIDTH:0.334366
G1 F1200
G1 X149.224 Y144.1 E.00245
;WIDTH:0.291684
G1 X165.776 Y144.1 E.32866
G10 ; retract
G1 X180.324 Y143.9 F10800
G11 ; unretract
;TYPE:Solid infill
;WIDTH:0.426247
G1 F1200
G1 X180.93 Y144.506 E.02622
G1 X180.93 Y145.048 E.01659
G1 X179.952 Y144.07 E.04233
G1 X179.41 Y144.07 E.01659
G1 X180.93 Y145.59 E.06579
G1 X180.93 Y146.132 E.01659
G1 X178.868 Y144.07 E.08925
G1 X178.326 Y144.07 E.01659
G1 X180.93 Y146.674 E.11271
G1 X180.93 Y147.217 E.01659
G1 X177.783 Y144.07 E.13617
G1 X177.241 Y144.07 E.01659
G1 X180.93 Y147.759 E.15963
G1 X180.93 Y148.301 E.01659
G1 X176.699 Y144.07 E.18308
G1 X176.157 Y144.07 E.01659
G1 X180.93 Y148.843 E.20654
G1 X180.93 Y149.385 E.01659
G1 X175.615 Y144.07 E.23
G1 X175.073 Y144.07 E.01659
G1 X180.93 Y149.927 E.25346
G1 X180.93 Y150.469 E.01659
G1 X174.531 Y144.07 E.27692
G1 X173.989 Y144.07 E.01659
G1 X180.93 Y151.011 E.30038
G1 X180.93 Y151.553 E.01659
G1 X173.447 Y144.07 E.32384
G1 X172.904 Y144.07 E.01659
G1 X180.93 Y152.096 E.3473
G1 X180.93 Y152.638 E.01659
G1 X172.362 Y144.07 E.37075
G1 X171.82 Y144.07 E.01659
G1 X180.93 Y153.18 E.39421
G1 X180.93 Y153.722 E.01659
G1 X171.278 Y144.07 E.41767
G1 X170.736 Y144.07 E.01659
G1 X180.93 Y154.264 E.44113
G1 X180.93 Y154.806 E.01659
G1 X170.194 Y144.07 E.46459
G1 X169.652 Y144.07 E.01659
G1 X180.93 Y155.348 E.48805
G1 X180.93 Y155.89 E.01659
G1 X169.11 Y144.07 E.51151
G1 X168.568 Y144.07 E.01659
G1 X180.93 Y156.432 E.53497
G1 X180.93 Y156.974 E.01659
G1 X168.026 Y144.07 E.55842
G1 X167.483 Y144.07 E.01659
G1 X180.93 Y157.517 E.58188
G1 X180.93 Y158.059 E.01659
G1 X166.941 Y144.07 E.60534
G1 X166.399 Y144.07 E.01659
G1 X180.93 Y158.601 E.6288
G1 X180.93 Y158.942 E.01043
G1 X180.729 Y158.942 E.00616
G1 X166.058 Y144.271 E.63484
G1 X166.058 Y144.529 E.00788
G1 X165.87 Y144.529 E.00577
G1 X165.87 Y144.625 E.00294
G1 X180.375 Y159.13 E.6277
G1 X179.833 Y159.13 E.01659
G1 X165.87 Y145.167 E.60424
G1 X165.87 Y145.709 E.01659
G1 X179.291 Y159.13 E.58078
G1 X178.749 Y159.13 E.01659
G1 X165.87 Y146.251 E.55732
G1 X165.87 Y146.793 E.01659
G1 X178.207 Y159.13 E.53386
G1 X177.665 Y159.13 E.01659
G1 X165.87 Y147.335 E.5104
G1 X165.87 Y147.877 E.01659
G1 X177.123 Y159.13 E.48694
G1 X176.581 Y159.13 E.01659
G1 X165.87 Y148.419 E.46349
G1 X165.87 Y148.962 E.01659
G1 X176.038 Y159.13 E.44003
G1 X175.496 Y159.13 E.01659
G1 X165.87 Y149.504 E.41657
G1 X165.87 Y150.046 E.01659
G1 X174.954 Y159.13 E.39311
G1 X174.412 Y159.13 E.01659
G1 X165.87 Y150.588 E.36965
G1 X165.87 Y151.13 E.01659
G1 X173.87 Y159.13 E.34619
G1 X173.328 Y159.13 E.01659
G1 X165.87 Y151.672 E.32273
G1 X165.87 Y152.214 E.01659
G1 X172.786 Y159.13 E.29927
G1 X172.244 Y159.13 E.01659
G1 X165.87 Y152.756 E.27582
G1 X165.87 Y153.298 E.01659
G1 X171.702 Y159.13 E.25236
G1 X171.159 Y159.13 E.01659
G1 X165.87 Y153.841 E.2289
G1 X165.87 Y154.383 E.01659
G1 X170.617 Y159.13 E.20544
G1 X170.075 Y159.13 E.01659
G1 X165.87 Y154.925 E.18198
G1 X165.87 Y155.467 E.01659
G1 X169.533 Y159.13 E.15852
G1 X168.991 Y159.13 E.01659
G1 X165.87 Y156.009 E.13506
G1 X165.87 Y156.551 E.01659
G1 X168.449 Y159.13 E.1116
G1 X167.907 Y159.13 E.01659
G1 X165.87 Y157.093 E.08815
G1 X165.87 Y157.635 E.01659
G1 X167.534 Y159.3 E.07203
G10 ; retract
G1 X162.466 Y160.7 F10800
G11 ; unretract
G1 F1200
G1 X164.13 Y162.365 E.07203
G1 X164.13 Y162.907 E.01659
G1 X162.093 Y160.87 E.08815
G1 X161.551 Y160.87 E.01659
G1 X164.13 Y163.449 E.11161
G1 X164.13 Y163.991 E.01659
G1 X161.009 Y160.87 E.13507
G1 X160.467 Y160.87 E.01659
G1 X164.13 Y164.533 E.15853
G1 X164.13 Y165.075 E.01659
G1 X159.925 Y160.87 E.18198
G1 X159.383 Y160.87 E.01659
G1 X164.13 Y165.617 E.20544
G1 X164.13 Y166.16 E.01659
G1 X158.84 Y160.87 E.2289
G1 X158.298 Y160.87 E.01659
G1 X164.13 Y166.702 E.25236
G1 X164.13 Y167.244 E.01659
G1 X157.756 Y160.87 E.27582
G1 X157.214 Y160.87 E.01659
G1 X164.13 Y167.786 E.29928
G1 X164.13 Y168.328 E.01659
G1 X156.672 Y160.87 E.32274
G1 X156.13 Y160.87 E.01659
G1 X164.13 Y168.87 E.34619
G1 X164.13 Y169.412 E.01659
G1 X155.588 Y160.87 E.36965
G1 X155.046 Y160.87 E.01659
G1 X164.13 Y169.954 E.39311
G1 X164.13 Y170.496 E.01659
G1 X154.504 Y160.87 E.41657
G1 X153.962 Y160.87 E.01659
G1 X164.13 Y171.038 E.44003
G1 X164.13 Y171.581 E.01659
G1 X153.419 Y160.87 E.46349
G1 X152.877 Y160.87 E.01659
G1 X164.13 Y172.123 E.48695
G1 X164.13 Y172.665 E.01659
G1 X152.335 Y160.87 E.51041
G1 X151.793 Y160.87 E.01659
G1 X164.13 Y173.207 E.53386
G1 X164.13 Y173.749 E.01659
G1 X151.251 Y160.87 E.55732
G1 X150.709 Y160.87 E.01659
G1 X164.13 Y174.291 E.58078
G1 X164.13 Y174.833 E.01659
G1 X150.167 Y160.87 E.60424
G1 X149.625 Y160.87 E.01659
G1 X164.13 Y175.375 E.6277
G1 X164.13 Y175.471 E.00294
G1 X163.942 Y175.471 E.00577
G1 X163.942 Y175.729 E.00788
G1 X149.271 Y161.058 E.63484
G1 X149.07 Y161.058 E.00616
G1 X149.07 Y161.399 E.01043
G1 X163.601 Y175.93 E.6288
G1 X163.059 Y175.93 E.01659
G1 X149.07 Y161.941 E.60534
G1 X149.07 Y162.484 E.01659
G1 X162.516 Y175.93 E.58188
G1 X161.974 Y175.93 E.01659
G1 X149.07 Y163.026 E.55842
G1 X149.07 Y163.568 E.01659
G1 X161.432 Y175.93 E.53496
G1 X160.89 Y175.93 E.01659
G1 X149.07 Y164.11 E.5115
G1 X149.07 Y164.652 E.01659
G1 X160.348 Y175.93 E.48804
G1 X159.806 Y175.93 E.01659
G1 X149.07 Y165.194 E.46459
G1 X149.07 Y165.736 E.01659
G1 X159.264 Y175.93 E.44113
G1 X158.722 Y175.93 E.01659
G1 X149.07 Y166.278 E.41767
G1 X149.07 Y166.82 E.01659
G1 X158.18 Y175.93 E.39421
G1 X157.638 Y175.93 E.01659
G1 X149.07 Y167.362 E.37075
G1 X149.07 Y167.905 E.01659
G1 X157.095 Y175.93 E.34729
G1 X156.553 Y175.93 E.01659
G1 X149.07 Y168.447 E.32383
G1 X149.07 Y168.989 E.01659
G1 X156.011 Y175.93 E.30037
G1 X155.469 Y175.93 E.01659
G1 X149.07 Y169.531 E.27692
G1 X149.07 Y170.073 E.01659
G1 X154.927 Y175.93 E.25346
G1 X154.385 Y175.93 E.01659
G1 X149.07 Y170.615 E.23
G1 X149.07 Y171.157 E.01659
G1 X153.843 Y175.93 E.20654
G1 X153.301 Y175.93 E.01659
G1 X149.07 Y171.699 E.18308
G1 X149.07 Y172.241 E.01659
G1 X152.759 Y175.93 E.15962
G1 X152.216 Y175.93 E.01659
G1 X149.07 Y172.784 E.13616
G1 X149.07 Y173.326 E.01659
G1 X151.674 Y175.93 E.11271
G1 X151.132 Y175.93 E.01659
G1 X149.07 Y173.868 E.08925
G1 X149.07 Y174.41 E.01659
G1 X150.59 Y175.93 E.06579
G1 X150.048 Y175.93 E.01659
G1 X149.07 Y174.952 E.04233
G1 X149.07 Y175.494 E.01659
G1 X149.676 Y176.1 E.02621
G10 ; retract
G1 X164.224 Y175.9 F10800
G11 ; unretract
;TYPE:Gap fill
;WIDTH:0.291684
G1 F1200
G1 X180.776 Y175.9 E.32866
;WIDTH:0.334366
G1 X180.879 Y175.879 E.00245
;WIDTH:0.334364
G1 X180.9 Y175.776 E.00245
;WIDTH:0.291684
G1 X180.9 Y159.224 E.32866
G10 ; retract
; Filament-specific end gcode
;T1
T1
; Filament-specific start gcode
M703
G10 ; retract
G1 X179.413 Y160.587 F10800
G11 ; unretract
;TYPE:Perimeter
;WIDTH:0.42
G1 F1200
G1 X179.413 Y174.413 E.41616
G1 X165.587 Y174.413 E.41616
G1 X165.587 Y161.757 E.38095
G1 X163.243 Y159.413 E.09978
G1 X150.587 Y159.413 E.38095
G1 X150.587 Y145.587 E.41616
G1 X164.413 Y145.587 E.41616
G1 X164.413 Y158.243 E.38095
G1 X166.757 Y160.587 E.09978
G1 X179.353 Y160.587 E.37914
G1 X179.79 Y160.21 F10800
;TYPE:External perimeter
G1 F1200
G1 X179.79 Y174.79 E.43886
G1 X165.21 Y174.79 E.43886
G1 X165.21 Y161.913 E.3876
G1 X163.087 Y159.79 E.09037
G1 X150.21 Y159.79 E.3876
G1 X150.21 Y145.21 E.43886
G1 X164.79 Y145.21 E.43886
G1 X164.79 Y158.087 E.3876
G1 X166.913 Y160.21 E.09037
G1 X179.73 Y160.21 E.38579
G1 X179.574 Y160.547 F10800
G10 ; retract
G1 X163.535 Y145.7
G11 ; unretract
;TYPE:Solid infill
;WIDTH:0.421078
G1 F1200
G1 X164.13 Y146.295 E.0254
G1 X164.13 Y146.83 E.01614
G1 X163.17 Y145.87 E.04098
G1 X162.635 Y145.87 E.01614
G1 X164.13 Y147.365 E.06381
G1 X164.13 Y147.899 E.01614
G1 X162.101 Y145.87 E.08664
G1 X161.566 Y145.87 E.01614
G1 X164.13 Y148.434 E.10947
G1 X164.13 Y148.969 E.01614
G1 X161.031 Y145.87 E.1323
G1 X160.496 Y145.87 E.01614
G1 X164.13 Y149.504 E.15513
G1 X164.13 Y150.039 E.01614
G1 X159.961 Y145.87 E.17796
G1 X159.427 Y145.87 E.01614
G1 X164.13 Y150.573 E.20079
G1 X164.13 Y151.108 E.01614
G1 X158.892 Y145.87 E.22362
G1 X158.357 Y145.87 E.01614
G1 X164.13 Y151.643 E.24645
G1 X164.13 Y152.178 E.01614
G1 X157.822 Y145.87 E.26928
G1 X157.287 Y145.87 E.01614
G1 X164.13 Y152.713 E.29211
G1 X164.13 Y153.247 E.01614
G1 X156.753 Y145.87 E.31495
G1 X156.218 Y145.87 E.01614
G1 X164.13 Y153.782 E.33778
G1 X164.13 Y154.317 E.01614
G1 X155.683 Y145.87 E.36061
G1 X155.148 Y145.87 E.01614
G1 X164.13 Y154.852 E.38344
G1 X164.13 Y155.387 E.01614
G1 X154.613 Y145.87 E.40627
G1 X154.079 Y145.87 E.01614
G1 X164.13 Y155.921 E.4291
G1 X164.13 Y156.456 E.01614
G1 X153.544 Y145.87 E.45193
G1 X153.009 Y145.87 E.01614
G1 X164.13 Y156.991 E.47476
G1 X164.13 Y157.526 E.01614
G1 X152.305 Y145.7 E.50483
G10 ; retract
G1 X179.3 Y161.465 F10800
G11 ; unretract
G1 F1200
G1 X178.705 Y160.87 E.02539
G1 X178.17 Y160.87 E.01614
G1 X179.13 Y161.83 E.04098
G1 X179.13 Y162.365 E.01614
G1 X177.635 Y160.87 E.06381
G1 X177.101 Y160.87 E.01614
G1 X179.13 Y162.899 E.08664
G1 X179.13 Y163.434 E.01614
G1 X176.566 Y160.87 E.10947
G1 X176.031 Y160.87 E.01614
G1 X179.13 Y163.969 E.1323
G1 X179.13 Y164.504 E.01614
G1 X175.496 Y160.87 E.15513
G1 X174.961 Y160.87 E.01614
G1 X179.13 Y165.039 E.17796
G1 X179.13 Y165.573 E.01614
G1 X174.427 Y160.87 E.20079
G1 X173.892 Y160.87 E.01614
G1 X179.13 Y166.108 E.22362
G1 X179.13 Y166.643 E.01614
G1 X173.357 Y160.87 E.24645
G1 X172.822 Y160.87 E.01614
G1 X179.13 Y167.178 E.26928
G1 X179.13 Y167.713 E.01614
G1 X172.287 Y160.87 E.29211
G1 X171.753 Y160.87 E.01614
G1 X179.13 Y168.247 E.31495
G1 X179.13 Y168.782 E.01614
G1 X171.218 Y160.87 E.33778
G1 X170.683 Y160.87 E.01614
G1 X179.13 Y169.317 E.36061
G1 X179.13 Y169.852 E.01614
G1 X170.148 Y160.87 E.38344
G1 X169.613 Y160.87 E.01614
G1 X179.13 Y170.387 E.40627
G1 X179.13 Y170.921 E.01614
G1 X169.079 Y160.87 E.4291
G1 X168.544 Y160.87 E.01614
G1 X179.13 Y171.456 E.45193
G1 X179.13 Y171.991 E.01614
G1 X168.009 Y160.87 E.47476
G1 X167.474 Y160.87 E.01614
G1 X179.13 Y172.526 E.49759
G1 X179.13 Y173.061 E.01614
G1 X166.939 Y160.87 E.52042
G1 X166.64 Y160.87 E.00905
G1 X164.13 Y158.36 E.10713
G1 X164.13 Y158.061 E.00905
G1 X151.939 Y145.87 E.52042
G1 X151.405 Y145.87 E.01614
G1 X179.13 Y173.595 E1.18359
G1 X179.13 Y174.13 E.01614
G1 X150.87 Y145.87 E1.20642
G1 X150.87 Y146.405 E.01614
G1 X178.595 Y174.13 E1.18359
G1 X178.06 Y174.13 E.01614
G1 X165.87 Y161.94 E.52041
G1 X165.87 Y161.64 E.00905
G1 X163.36 Y159.13 E.10713
G1 X163.06 Y159.13 E.00905
G1 X150.87 Y146.94 E.52041
G1 X150.87 Y147.474 E.01614
G1 X162.526 Y159.13 E.49758
G1 X161.991 Y159.13 E.01614
G1 X150.87 Y148.009 E.47475
G1 X150.87 Y148.544 E.01614
G1 X161.456 Y159.13 E.45192
G1 X160.921 Y159.13 E.01614
G1 X150.87 Y149.079 E.42909
G1 X150.87 Y149.613 E.01614
G1 X160.386 Y159.13 E.40626
G1 X159.852 Y159.13 E.01614
G1 X150.87 Y150.148 E.38343
G1 X150.87 Y150.683 E.01614
G1 X159.317 Y159.13 E.3606
G1 X158.782 Y159.13 E.01614
G1 X150.87 Y151.218 E.33777
G1 X150.87 Y151.753 E.01614
G1 X158.247 Y159.13 E.31494
G1 X157.713 Y159.13 E.01614
G1 X150.87 Y152.287 E.29211
G1 X150.87 Y152.822 E.01614
G1 X157.178 Y159.13 E.26928
G1 X156.643 Y159.13 E.01614
G1 X150.87 Y153.357 E.24645
G1 X150.87 Y153.892 E.01614
G1 X156.108 Y159.13 E.22362
G1 X155.573 Y159.13 E.01614
G1 X150.87 Y154.427 E.20079
G1 X150.87 Y154.961 E.01614
G1 X155.039 Y159.13 E.17796
G1 X154.504 Y159.13 E.01614
G1 X150.87 Y155.496 E.15513
G1 X150.87 Y156.031 E.01614
G1 X153.969 Y159.13 E.1323
G1 X153.434 Y159.13 E.01614
G1 X150.87 Y156.566 E.10947
G1 X150.87 Y157.101 E.01614
G1 X152.899 Y159.13 E.08664
G1 X152.365 Y159.13 E.01614
G1 X150.87 Y157.635 E.06381
G1 X150.87 Y158.17 E.01614
G1 X151.83 Y159.13 E.04098
G1 X151.295 Y159.13 E.01614
G1 X150.7 Y158.535 E.02539
G10 ; retract
G1 X165.7 Y162.305 F10800
G11 ; unretract
G1 F1200
G1 X177.526 Y174.13 E.50483
G1 X176.991 Y174.13 E.01614
G1 X165.87 Y163.009 E.47475
G1 X165.87 Y163.544 E.01614
G1 X176.456 Y174.13 E.45192
G1 X175.921 Y174.13 E.01614
G1 X165.87 Y164.079 E.42909
G1 X165.87 Y164.614 E.01614
G1 X175.387 Y174.13 E.40626
G1 X174.852 Y174.13 E.01614
G1 X165.87 Y165.148 E.38343
G1 X165.87 Y165.683 E.01614
G1 X174.317 Y174.13 E.3606
G1 X173.782 Y174.13 E.01614
G1 X165.87 Y166.218 E.33777
G1 X165.87 Y166.753 E.01614
G1 X173.247 Y174.13 E.31494
G1 X172.713 Y174.13 E.01614
G1 X165.87 Y167.287 E.29211
G1 X165.87 Y167.822 E.01614
G1 X172.178 Y174.13 E.26928
G1 X171.643 Y174.13 E.01614
G1 X165.87 Y168.357 E.24645
G1 X165.87 Y168.892 E.01614
G1 X171.108 Y174.13 E.22362
G1 X170.573 Y174.13 E.01614
G1 X165.87 Y169.427 E.20079
G1 X165.87 Y169.961 E.01614
G1 X170.039 Y174.13 E.17796
G1 X169.504 Y174.13 E.01614
G1 X165.87 Y170.496 E.15513
G1 X165.87 Y171.031 E.01614
G1 X168.969 Y174.13 E.1323
G1 X168.434 Y174.13 E.01614
G1 X165.87 Y171.566 E.10947
G1 X165.87 Y172.101 E.01614
G1 X167.899 Y174.13 E.08664
G1 X167.365 Y174.13 E.01614
G1 X165.87 Y172.635 E.06381
G1 X165.87 Y173.17 E.01614
G1 X166.83 Y174.13 E.04098
G1 X166.295 Y174.13 E.01614
G1 X165.7 Y173.535 E.02539
G10 ; retract
M107
;TYPE:Custom
; Filament-specific end gcode
; Filament-specific end gcode
M106 S0 ; turn off cooling fan
G10 P0 S0 R0
G10 P1 S0 R0
M140 S0; turn off bed
;Drop the bed
G91
G1 Z10 F1000
G90
M0
; filament used [mm] = 58.86, 36.97
; filament used [cm3] = 0.14, 0.09
; filament used [g] = 0.18, 0.11
; filament cost = 0.00, 0.00
; total filament used [g] = 0.29
; total filament cost = 0.01
; estimated printing time (normal mode) = 2m 50s

; prusaslicer_config = begin
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = G:\\Rancor\\Rancor\\PrusaSlicer\\BedModel.stl
; bed_custom_texture = G:\\Rancor\\Rancor\\PrusaSlicer\\BedTexture.png
; bed_shape = 0x0,330x0,330x320,0x320
; bed_temperature = 60,60
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 4
; bottom_solid_min_thickness = 0.5
; bridge_acceleration = 1000
; bridge_angle = 0
; bridge_fan_speed = 100,100
; bridge_flow_ratio = 0.95
; bridge_speed = 30
; brim_separation = 0
; brim_type = outer_only
; brim_width = 0
; clip_multipart_objects = 1
; color_change_gcode = M600
; complete_objects = 0
; cooling = 1,1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 1000
; default_filament_profile = ""
; default_print_profile = 
; deretract_speed = 0,0
; disable_fan_first_layers = 1,1
; dont_support_bridges = 1
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0.2
; end_filament_gcode = "; Filament-specific end gcode";"; Filament-specific end gcode"
; end_gcode = M106 S0 ; turn off cooling fan\nG10 P0 S0 R0\nG10 P1 S0 R0\nM140 S0; turn off bed\n;Drop the bed\nG91\nG1 Z10 F1000\nG90\nM0
; ensure_vertical_shell_thickness = 1
; external_perimeter_extrusion_width = 0.45
; external_perimeter_speed = 35
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 45
; extruder_colour = #FF8000;#0000FF
; extruder_offset = 0x0,0x0
; extrusion_axis = E
; extrusion_multiplier = 0.96,0.96
; extrusion_width = 0.45
; fan_always_on = 1,1
; fan_below_layer_time = 100,100
; filament_colour = #FF8000;#FF8000
; filament_cooling_final_speed = 3.4,3.4
; filament_cooling_initial_speed = 2.2,2.2
; filament_cooling_moves = 4,4
; filament_cost = 24.99,24.99
; filament_density = 1.24,1.24
; filament_diameter = 1.75,1.75
; filament_load_time = 0,0
; filament_loading_speed = 28,28
; filament_loading_speed_start = 3,3
; filament_max_volumetric_speed = 15,15
; filament_minimal_purge_on_wipe_tower = 15,15
; filament_notes = "Affordable filament for everyday printing in premium quality manufactured in-house by Josef Prusa";"Affordable filament for everyday printing in premium quality manufactured in-house by Josef Prusa"
; filament_ramming_parameters = "120 100| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6";"120 100| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = PLA;PLA
; filament_soluble = 0,0
; filament_spool_weight = 0,0
; filament_toolchange_delay = 0,0
; filament_type = PLA;PLA
; filament_unload_time = 0,0
; filament_unloading_speed = 90,90
; filament_unloading_speed_start = 100,100
; filament_vendor = Prusa Polymers
; fill_angle = 45
; fill_density = 20%
; fill_pattern = grid
; first_layer_acceleration = 1000
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 60,60
; first_layer_extrusion_width = 0.42
; first_layer_height = 0.2
; first_layer_speed = 20
; first_layer_speed_over_raft = 30
; first_layer_temperature = 210,210
; full_fan_speed_layer = 0,0
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 40
; gcode_comments = 0
; gcode_flavor = reprapfirmware
; gcode_label_objects = 0
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = duet
; infill_acceleration = 1000
; infill_anchor = 600%
; infill_anchor_max = 50
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.45
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 200
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]\nM800 F"layer"
; layer_height = 0.2
; machine_limits_usage = time_estimate_only
; machine_max_acceleration_e = 1500,1500
; machine_max_acceleration_extruding = 1500,1500
; machine_max_acceleration_retracting = 1500,1500
; machine_max_acceleration_travel = 500,1250
; machine_max_acceleration_x = 500,500
; machine_max_acceleration_y = 500,500
; machine_max_acceleration_z = 100,100
; machine_max_feedrate_e = 60,60
; machine_max_feedrate_x = 180,180
; machine_max_feedrate_y = 180,180
; machine_max_feedrate_z = 15,15
; machine_max_jerk_e = 25,25
; machine_max_jerk_x = 6.7,6.7
; machine_max_jerk_y = 6.7,6.7
; machine_max_jerk_z = 1.7,1.7
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100,100
; max_layer_height = 0,0
; max_print_height = 601
; max_print_speed = 200
; max_volumetric_speed = 0
; min_fan_speed = 100,100
; min_layer_height = 0.07,0.07
; min_print_speed = 15,15
; min_skirt_length = 4
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.4,0.4
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_T0-{filament_preset[0]}_T1-{filament_preset[1]}.gcode
; overhangs = 0
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 800
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.45
; perimeter_speed = 60
; perimeters = 2
; physical_printer_settings_id = Printer 1
; post_process = 
; print_settings_id = N0.4 0.20mm SPEED
; printer_model = 
; printer_notes = 
; printer_settings_id = Rancor
; printer_technology = FFF
; printer_variant = 
; printer_vendor = 
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 0
; resolution = 0
; retract_before_travel = 2,2
; retract_before_wipe = 70%,70%
; retract_layer_change = 1,1
; retract_length = 0.5,0.5
; retract_length_toolchange = 0,0
; retract_lift = 0,0
; retract_lift_above = 0,0
; retract_lift_below = 600,600
; retract_restart_extra = 0,0
; retract_restart_extra_toolchange = 0,0
; retract_speed = 40,40
; seam_position = nearest
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 0
; skirt_distance = 2
; skirt_height = 3
; skirts = 1
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 20,20
; small_perimeter_speed = 25
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.45
; solid_infill_speed = 200
; spiral_vase = 0
; standby_temperature_delta = 170
; start_filament_gcode = "; Filament-specific start gcode\nM703";"; Filament-specific start gcode\nM703"
; start_gcode = ;Begin Start GCode\n\n;set temps\nG10 P0 S{temperature[0]}\nG10 P0 R{if temperature[0] == 0}0{else}{temperature[0] - 40}{endif}\nG10 P1 S{temperature[1]}\nG10 P1 R{if temperature[1] == 0}0{else}{temperature[1] - 40}{endif}\n\nG28 ;home all axis\nG29 S1 ;enable mesh\n\n{ if current_extruder == 0 }\nT0\n{ elsif current_extruder == 1 } \nT1\n{ endif }\n\nM116 ;Wait for all temps\n\nG90\nM98 P"prime.g"\n;End Start GCode
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = -1
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.1
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.35
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 2
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 50
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 55
; support_material_with_sheath = 0
; support_material_xy_spacing = 50%
; temperature = 210,210
; template_custom_gcode = 
; thick_bridges = 1
; thin_walls = 0
; threads = 32
; thumbnails = 128x128
; toolchange_gcode = ;T[next_extruder]
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0.4
; top_solid_infill_speed = 50
; top_solid_layers = 5
; top_solid_min_thickness = 0.6
; travel_speed = 180
; travel_speed_z = 0
; use_firmware_retraction = 1
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wipe = 0,0
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 20
; wipe_tower_x = 156.544
; wipe_tower_y = 144.37
; wiping_volumes_extruders = 70,70,70,70
; wiping_volumes_matrix = 0,140,140,0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
