; generated by PrusaSlicer 2.4.2+win64 on 2022-05-19 at 02:57:55 UTC


;
; thumbnail begin 128x128 11328
; iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAg90lEQVR4Ae1dB3yNVxu/2aMRJQlJhB
; ghkWFTJbXahBgtLW3NamsUJfiUqlFVoTVbLW3xqfnRGLX3KhIaYpcgiJBpZU/3f7/3OXG5ufMd92Zo
; nvb5/SI3933POc9znvN/xjlHBhWKvxuP93u/DwsLC8hkMqEsF/odSwtLjB8/Hrk5uYCc+58j8KDCwk
; LMWzAPZmZmWp9r72CP6d9MR3pGOsSQgqP79+5jQP8BsLW1RZMmTTB/wXzEx8fj6dOnMAadjjyNVi1b
; 6R3r2rVrY93/1iEvL0/j+3zHiignNwe/Lv8VLtVdNN/z7GHYsWMH6tSpI0bwktjK2gp7d+/lpApBlJ
; mZiff7vF9MCehn3wBfHDxyEE/lwgVFgicBU3vqe9XXaGulSpXQ671e2PrnVmRlZQH0Ct5iKKK83DzM
; /W4unJ2deY2PjY0NhgwdguSUZIXyGUKEr0oXLl1AYPtAmJubv3jH48ePMTZ0LOzs7Epc+Ep2q+GGO7
; fvCOoMCfh67HUE+AewDllaWeKToZ8gOTVZ7/d0DR4JPz0tHRMnTIS9vb3u9ppzimZlBs/anpg8aTIu
; XryI/MJ88KEb12+gR7cesLKyEjQ+pNiNGzfGwcMHJVug9PR0TJ0xFfavPOtjixYtSk3wz9lChuCQYO
; QV5gnqjPypHH+f+huNGjXCug3rkJ+vXxC6hE+/PnvmLNq0bqNzWdFpwWys0LJ1S/y85GckJiRCXigv
; sgxqz1+/dj1q1awl9PkKlZ/lZIFmfDMDaelpkELUngOHDqChf0N6rskFzAsbmFuaY/b3syHGuuXm5h
; rqsM5ZT0rz46IfUeXVKpL7WrlyZQz9dCj27t2L/IIiZUxOTma/U7cqAQEBmDZ1GpydnA0Jv9j4EWbo
; 2Kkjzl88D6nELSuCFUAw0BPC1VyqISIiAsYkPeul4vat2+j1Ti+xoFe3VeBwjbefN8b9Zxz8fP2Krb
; m0po8aOQoPUh8wcBd9Nhod2ndQtQwKPuPt5uaGZSuWIScnR7NjHIEnCVEAMcIX/B1C3DRrpJK+WU/r
; 6JZNW+BZ01OUgHmzefF/1/SoiU2bNhWzctSWhw8fYtqUaXB4xUHQ2BGW6NuvL+7G34UQUlUQIQpQIm
; xuZo6RI0YiNy8XYkmf8B88eICRw0cy967E+sRZgF49e+H27ds620zL2IH9B+DX0E/QpDGTmcHHxwc7
; du5A4VP9rpSq4JVjZGwFkIv8rBjb2thi3bp1MBZRx6m/kRGRaNq4qTH7a5CrVqmKH3/4Uasvry6Ugo
; IC3I27i08GfwJra2tB7yGM8cXEL/Do8SOD71GlklQAQezp6YnY2FjwJX2zntbJ2bNmw7GSozH7apBb
; t26Nc9HnIKTt9CPFGNauWQt3N3dD71DIVDADWZo2bdvg1OlTvN6lSwGEClEu8nsGOfjNYGSkZUACKa
; 5du4bgoODiwQ8TM5uNE77AkydPtDdKiylWp8KCQmwO36wPoCp0vd/JyQmLfliE7Oxsg++RSeionOfv
; RLONlQ0WzlsIeYFca8RN36ynjzb+sRGurq4wZpsMsVc9L+zds1enO8sHoZNrum7NOlSrVk10OywtLd
; GzZ0/ciL2h910ymcxonTeJi0gRq+N/HddQAD7h0D82/gEHBweYol3aBrx/v/64f/8+DAleX9tTklNY
; DsLCXLRrWsyNrFu3rnxj+EadQTKxCmDSeEAx5lypeg3qISkpCfpI28yiEO2EiRNgZm4GU7aRZuqK5S
; sYiBMrfHIHDx44iAb1G0hpi9YYAsUeRowcgZTUFEhRgJITuhpTlPCjQR9RVosbPTkv4bPB5v7LyMpA
; xzc7snCzKdrWqVMnXP3nKqQQJbamTJ4iGPkLkRUFmpo1a4ajx44WS5TpVwAzbvb51MOwz4YpTWmpKQ
; Hnt8tXrV2lkS/gs6bGxcWhVp1aGoEZKczi8l/PYMIzRPpM/oXzF/B669cF5yD4Cl6dKVw9a/as56ly
; 3QrAzZj+H/fHvaR7yCvIw7GTx+DfyN+kQjbEFEm7fPkyb8G/kACwb98+9UibaPb388exo8ckAT1KC/
; +y5Be8+uqr2t6hMIXwlUyeRVBwEC5fuaxFAbhZX82dW9PWrEBO3os4c6G8EImpiRg5eqTRY+d8OkUR
; L2sLa3Tr3A2ZGYZnnSrR+kqRttnfzoaluaXo9pCJHjZ0GANqhkjfrL8ffx/v9nrXWK6paKvs4eGhpg
; CciewY3BFXYq7QOiHX0ink5OcgfGs4PGp6GFPQfDulIAGGfRuGwrxCwcUYOVk5LB8vBg/UcK+BDf/b
; wCsfr9O3LyzEtj+3sSCXicdJCMvYrLd3tMfM72YiLSNNPTKl0ZmCpwWIjYvF273eNlZHeAlf+bOdrR
; 1OHD8BMZSUnARvX2/2HC9newTW0Z8GprW5R/ceiL1pOCqpb9anPUnDmNFjmLsoclxUo35GxGLcrPdt
; 7IsjJ4/I1bVb2SFtHSMkmZaVhh+W/IAqVaoYqTFaO6a5HnJt9vL2QkqKYVOsTuQaRvwdgQ+a1sBfI1
; 5T7P6khaJ3I1c42Ggua7Q+z583X2e9AR/3jn59+tRpNG3SlC1jEoSvb4zE8/DRw5H8MFl0nRll7XZs
; 3wFrK0kujMFZr00JBg4ciLx8YVVE+VnpOLdguIKEr8o/vtNQ4VrJ5vnzW7ZoiaioKINAT9+4UQ5i3t
; x5RgOfJmGhA6gkhge4Dm7dtpVVr5qgcQaRMAU4fl/7O+9SsqTInVAXvCqTNejbzAPjxo7Do0eGs2r6
; hE9Lhp4chMIY/TcK8+mMOhGYoXKisePGsmJMkS8XPuu1sIenBy5dumSwzTGrZyr0CV+VLyz8TFGYna
; FX+LqoIL8AGzdshJurmxTBlIzwVRWAL1FM+WTkSTRp2kTKi4UVPXBAzNbOFi1fa6npgnKInmrkUlNT
; tbY3M/46/p7ak7fwlRwx/k3Fg/PHNJ6nb6JQscnHgz82lpssl5VE4A08iQAipTdpQ4ajo9Hz6jo1nk
; yoV30v7Ny9kynfqlWrUL16dY2/mzplKp7mPy3mGt7ZuQxCBa/OseELFQXZGQbH5uiRo/Dx9jHWGGgV
; PFVLUSzESFFD/gpASY6Y6zHo0rWLlJcJNvlU8/Zhvw+RkJhQrD1UXx8UFFTsbylIc3D/QfY5zfqzYQ
; MUUoWvZHpWRnyM1rGh4o0Z02eYvMSMgOQ307/B1s1bUb9efSnuJH8FIGuXnZ3Ntie5uUta0wQJn2Y9
; 5fGX/XeZztpAGviwsLBiVT7eDbxxa89qGEvw6kvCvcMbirXh8qXLCGwbaPI4vr+vP7MwymzjvXv38E
; GfD5jSSX63LuET0LufcB9Dhg0xRTWNzllPmt2+Y3sWp+ZDJ0+cRKOARsyPDwtpoDCF8IsDxBGKnAcJ
; iLkWg2rVq0EmM8p4aBW+jbUNhnwyBImJiRoRSJIP5RJcq7tKwxzQMutpraVtSA19Gxq9U7qET5pMGc
; evv/kaGRnCysBiIw/gwPDWJhe+qjVIPXeUzUrv+t4G+2ZgjLSOE3kRG9ZvMLjbiaxQx/YdBW8306oA
; rEb90UMmBBPsFdQ5OKTB/gH+OHzksOCdQQTSSkrw2gBiSvxdDB44mO8sNKggZG27hXRjOIdmOR+ilP
; TUr6ay3U2CrbXyIbS+0O5RMr8ShCwY6BF4+3Top1qrVfR22shATyxHc21Iu3NVsWHdBrg4u0iaJJUd
; K2Pe9/MYvhETmD108BDtKxCW8aQXZWZn4rflv8HZxRkSOiAY6NWsWZMBTF2lVLqIwFhpC159SaA2Xb
; 94AUGdgpi7pqP/OoFey+Zc6PnvKMFj8Zw4fcnPycf0qdNhY2HDP+9ACkAbDT1rGUxRyo016wnohXQL
; wc3Ym4L6SP44gbCyJHxVpralJ8Rh7py5LGPJR/j0d6GjQ1kQSWQ6Bk8LnyIuNg5dO3dlldS8BK9k5U
; Nu3rhpko2SqkxAjzKHFEzKys6CEDIUxy9L1oBrq4JtW/dvpHfW1/asje3bthsEevqoIK8Amzduhoeb
; B9/1X6FVAYgo7fnDwh/YdiaR1kAv0GvWvBkiT0dCKAmJ45cVvvLrF4pHSQkY9dkodhSO+ljQUTx37t
; wRfeAD1es8efgEwz8dDjtrCYBd/cHUIFqL6LAEYwifZj15FKHjQ3XuW9NFYuP4ZYWp7SnRR7Bz207U
; rFGTjUdVp6pY+vNSNtnEmvzC/EKcOHYCAQ0DNJRLsgIoiY6O+eI/X+AV+1dEP5xMUt16dfHn9j95uz
; RKMkYcvywwLQnUlzvXr2HMmDGsCljoWCiJFCY3Oxfffv0tHOwcjBOB1PdCauiunbvQwKsBv/VEhSkw
; 8V6f9xB/Lx5CqKy4d8ZmAojUNylA7/o/1/Fm+zdhbcmr+IZfUMrQiyn9SVuW+3/YXz3apNPk006Zpb
; 8uZceTCaGy5t6Zwhqo5xP4UH4ulwVdsQouVV3UXUzTWQD1vDftb1/+23I6xkWve9c2sK3g82vIvSuP
; QE+KNaB8giEiPJaSkIJ+H/SDrbWJso3gIXwVUly6eAlvdnxT43y+V155BVOmTRF8OGN5B3pSrIG2gh
; MlEdA7tO8QGtRtYNp9GHyEpF4KRcmar6d9jUoOlRjQo6TR/oP7BR/OWJpx/LLC6gUn7ICI9CxMHD8R
; 9jb2phK8XEMB9O211/Z7AoiRJyMROjYUyUnCDnV6WYGeWKaxoDEhOnPuDJo2aworSyuYSPiaFkCo8I
; uRQFD7sgM9sawEiFeiz6JDuw7GLfvSwewd4ZvCNfxSQRsveRKZOYqOlSehlAYr8wlhM8PYYVlGNfcq
; zNz0nu9BZmlric9GfcaSEaYS/pPrZ0EaXp4EUZpMY5UYsQMRJyJYeldFcEYpF3dxcsFPi35CQW4B92
; 8z7peWMvg18lOcOCluv50+qgB64plc44cJ9zDs02HSQ74yFpmVB74eiEvRl56fZyx7rlnmMji86sAO
; D+Bz6IEh+re6d8ZmAogp0YexddNWuLu68xG0VpNPB1pMmjAJGU8yiuE2WbE/fGYNOgV1QkxMjFjZVw
; A9I7MSIN66egUhwSGCyr4I6FHd4v7d+zVOMaflXqb1ixZFh0SsXLVSUIUKAb0K9850TAAxI/EuFi9a
; zGvDKZXbDeo3CEn3knR6azKdD+CWBHNrcwwcPNDgCV1E5aVgo7wzswaH/ofz0efRvGlzKv3SavKpXP
; z35b8XnbGoh2R6tcisyBp4+Xhh3/59Oh/yb4rjlxUma5CWmozxoeOLBY1oeaATVmMux2g1+cIUQMUa
; 2DrY4suvvkRa2ovbKiqAXukyWQMqONm3ex/qeNaBcxVnhH0ThpzMHN4BOn4KoAIQXw98HecvnH9pCj
; ZeBiZX+/6tm4iKjOI168UpwDP2qmaP/74fUK4G6N/AqvkEvsIXrAB0lk55GpR/G4spOJGRq8CSAma6
; Bc82XnZpoPhrxGsVXA5YW8GJtoRfYlIiZAl3E7ApfBM+D/0cLVq1YGfdq2aimrg7gs7OKU8DUMHP9y
; donfVUabRn3x74+XN5BiVaZGcB5Gez00C379iOSZMmYVJww3LV6QrWZHLRVQtOyIub/NVkdgQeiyhq
; 0xACE6enVLh3LwsTQKSM7NlzZxH4RiA7Xe35Eq8u/Io4/svJx8a0Vwxt3xCV7dRKypWCL+sbLyvYOK
; x+ICZTgMdx13B4eKty1ZEKFs8E6v1cHV4oQOLNf/DfIW8p9g1pWa46UsHC+eCwloppb3kp3B1tXigA
; pXyvXrmI0UEBig39m5SrDlUwfw4f2FTxXoCrwtrC/EVpGW072rx1M2p51mK/aFXrVSx8u6GiYkl4uX
; hhj4aKANdKmjWFIz8fqXHeb3UOJIxvV0exidOY8tTJCtbkbYObKT5qUUPhZK9zQ6n28K+tpTm6NnRR
; LO/jX2ENyikv6+2vGNbjDQVdZ6/nwiz9CSDPKnaYHuRVARDLERPQm9OrmeKfM8fZjeIXLl7AtBnTUN
; +nvrZ6QsNZQLIG73LgYW3fxuVqIP6N/PsHjRSrZo7XSAOzG14y0nDy5El2dU0N1xrs4Gkh6WB5I7dK
; 7DjWiiWhbPL3Xb0VkbvC9dYAkMfHLvvIzsHWLVsh86zjCXML/mXGBBD7NXWvAIhliAnoLfq0m+JBgr
; DTWEgRZHSb1eFDh9G3b1927TiXClZYmD3fjy7XtSQEN3BWLO7pW2ENSpl/5mSwY/lCiKWiXAClhAu5
; VOGjNAWdAtK9S3d2DLuhHaoEEMld3PVJ83I1aC8D06z/eVgPRfz1K5BC2k4LZ9fHxd2Jw4+LfsTrr7
; 1edKmxuX53sQIglhyTe/eGl7Pi7t27GkWgkhSgWNnQM6tABxJGR0cjdFxo0UHEOjYpkjUggFjhLpqO
; lXF8b5eio/v69O7DjpKRrAB8bgyjP0nPSseRo0cQGhoK9+ruRYcSqywTZA0qAKJpmOL4fbmxrWTzYg
; JaWFpg5cqVok8bfa4AQojcCHphTk6OYsvmLQw8OjsXP2W8Ip9gXNYZx+fY1c0VZ6LOCD6pRbQCqBOd
; LkJ1ZqtWr0JQlyBY0BWsZi/yCQRWytNglyXmEcdn3KZNGzxOfSwID+Rl57ELuCUrQDFl4MKOsXdiMe
; u7WWjesjkcbK3lHEBERT5BOBPQa+NZhdeJILQMjxs3TtBObroZlbb6GVUBVO7TpWVCHnkqEjNnzkSX
; Ns0q8gk8mYDepI51FbWrCDgBnLO4dg522LFjh6Cl4P79+8ZVAF2UkZ2Bo0f2Y/GYDysKTvQwxfF7+F
; YrXrDBk+mGEJ96PoiPj0fBU36WgCyGTgUQgyz5eBNn9oRjWf/XKpYENaY4Pgf0IFTw6vzeu+8htyCX
; MwT8TIFWBSBTTqeB/vbrb4g+F23whGv5MwJPohrELd+OrHAXR7wAeqrunRSmyyS/n/s97wmsdwm4ff
; s22rVrx7SK/P+svCwN8yJU+ErK4VKT+38NU2z4pO2/1hpQHJ8v0OPLlO+nu5VPnDjB614Cgxjg1u1b
; 8PfzZyeB0y3ddJ0rBYRI5mIEr/H886dYRfK/KZ9As34c5yI/r8w1Abdp24Yd7WPIM+AFAuka11oeRU
; Wj5ly0z8XVRT5q9Cj52bNnmZaR+yeHeF1QWoN/Qz6B3LsO9ZwUphK8qmtI+zsNWQFeCpD/NB/HThxj
; J0zKVFLE1lbWaNmiJX5a+hMoMVFYIC0uTdZgSd9WL6W7SO4dAT1lHN/kzLmGFJTb9uc2va4hbzeQQM
; W8ufNgb2uvVdvo3t8B/Qew+4Gyc7Ihlsga/DFjxEsFEI0N9IRYAc8anoiPi5emAMq1nq6SHzBggO46
; ATpazsocDbwbsPsE6C5CutdODEVs+R1rBrcp9wCR4vjNPSqXqODVuUtwF3YdrVYFoOtGhSzfdMdvq5
; ateL3YwsoCnd7qhHXr1iE1JZWLPEBQvJrcxdVjepZLgEizfuhrNQ3G8UuCCcAvmLdAKx6Qbdm0Rauf
; r8u9I7B36swpOFZx1HusjOpaRJaBLlYeOmQojv91nN2Zx5dUAWJ5sQZC4vglxVTuR4eBq8cHZB41PB
; B7K1ZD+PqEQqh/2cpl7CRRoQ2hQw19fX3l3835jt2c+cydhCFSuotlGSAqCza4OH6ZEr6S6XCIx48e
; F1cACzMLRacOnZCZkykoqJOTk4PRY0eLaghhCApY0AnW77zzDrbv3I4nmU8Mv5OzBtvnTyqT+QSVjZ
; elIVw537+lPQGq3ppMOSvD5oTJ8wrzIIQePXyEDu07SG5k8+bNcS3mGu/3Ru/bjJUDXy8zS4JGwYaZ
; TGN5JIVXMt3wzSaBmbnx7wE0wHRTyNrVa5/jPtkzwcjpVu+IiAgIIQIVJLjqrtVF3XFDZ9WMHTeW5a
; aFEgHEPyYPKlV3UeneOdpaMaBFE8mjpgfad2yPYSOGISwsDGvWrsHu3btxOuo0Tv19CmfOnkFUdBR2
; 79qNzRs2Y/7c+ZgwYQK6du0KvwA/ZhXpmjh6nrFmvbr19fDwwK3rtxggl6k+qHHjxkhISIAQIlCxff
; v2osphAQ3xrO3Jviclmpz9DCBuGhJY4taA4vht61ZVUKHssCHDsOr3Vbh69SpLffNNx6oS263DLaup
; D1LZPo3ZYbPRvXt3VHepzqKvejZ3ilKCd95+B1kZWXKZ6gekdVTwSf6+EMGQJfhy8pf8Xm5uhj7v92
; F5a7GkjlNKEiDu+bSFYnKQj2LejMmK06dOs2tdpZZm6yPKyu7dtxcjRo1ArRq1jLZk0FJASiZT/4DM
; Dx0cKTS2n52RjeDgYL1LAbkiS39Zivz8fIiluLg4hI4JxYb1G5Cb88KdLIl8AhVsrPg6VJGRnoGSJv
; K80tLT2M0fZBko8ipVCZydnDUVgLhWzVrMnAkiTl9uxN6Q1/Oup1UJAgMDcenyJYglsjKbNm+Se3p6
; sueTtXJ3d8foz0fjXPQ55OblMqv1z8kDLJ9g7CWB4vgRu8JRGlTM4j0tWi6u/HMFY0ePZalfXvEYHU
; uBVgWgvYE9uvbAkzTDrplaQ7Ft+zZ2j7DyWexO4alTkJ4u7E5hVXrw4IH889Gf68QZpAykYEt+XoLE
; xEQ8TrpntHyC2I2XJUG0aYdubZ02bRpcXV31CVsfYNT+Ae0AmjFzBvIK8gSFikkJ5syew9ydBg0a4O
; ChgxBL9KyTJ0/KGzVupG5VtHaI3kneTP/+/bFzy1acDF8pKZ9A7p2UjZdSSEitxdPCpyzhM3bsWHbW
; swDh61YA4sqvVsbRw0fZFjHexJmo/Ox8/LL0FyQnC7tTWJUyMjPkc76bI3d0dBTSIYWqMtSrWw/D+/
; bCjx91EJRPMNbGy5Ik0heqBaRltmu3rkJuFtPxwbP7gho3aoyUlBT1l0muBNJHMddj5IYAJW+mkmk7
; S/RqUpNXPoHi+H8smmGU21NpmPIL82Hi4dIgLtciX7NmDcNIopcAJVuZW+HjwR8jKzfL5B2h8qXVa1
; bDzc1NuuC1sL7zjiiOv6B3C4MnbBjsQ2EBc3GpEGPhwoWY+MVEfDbiM5ZGJx4TOgaUB6FoXFRUFDu2
; hVXxGmlsVSfn7Vu3+VgDwwNHgYi169cWXUFmIh2g+rWPP/6YuaGmEL6SlRtYVfMJFMf/fnBX0UCPgm
; FRf0dhwhcT4OvnyyKc5K9bmuuO5tFnVhZWcKrqhJCQEMyaOQunIk6xGExeXp7RxpmCS3PmzuGsoJ14
; BSCu5lINN2JuwNhECrv/wH65T0MfkwpenUOa1MPy/q0Y0Du0YQWEEovcFeTgrxN/IaRLCAusSInWkU
; IQ8Pbx8cHMr2fi8oXLKMgXV0yjra0Ujq5Ro4Z4BaDOBXUOwuMnj2Esok2l5CJqQa76WFeqlVdsnFzG
; 3r1742bsTSRw+QSxQI++P2TokCLBG1ExiWmXj421DXq+3RNHDh8RtOdPF1Fd5/mL59HQu6FIBZAVVf
; hM/2a6pEiekujsOspPGwXo8WSKfC1evBg5uTkQS9T3jeEbUbdu3RJpMy2Jnbt0xvETx4sqenSEnfkA
; c1KCf67/g9avtVYdd2ENsrO3w8EDL3x7PleTqRJVA1E42MXFxRgDxGvWU2ffeOMNRJ2NYufliSUqhx
; sxckTxGzdKiMnS9OvXDzFXY1idpVjQSN+7d+ce/P39lXhLeGNonUpKToJQIi1dsWwFKycX8D5J1TV0
; yTLVx0tZugjkHTl2BM2aNStRi6VN4Sk2s/jnxQws8tn5o4sIY/h4c7hLyFXkqto4aOAgdkWpEE2kBF
; Pqo1Q2GynGIOMZ1BHLtN7t2buHuWZiibJxs2bPQuXKpVvZq8qkhEFvBeHWrVvMYxBrDU6dOgXZ3Nlz
; UdlReOfsbOyw+vfVvF6uvj49KyKRy2TGHRhV9vXxxc2bNyGVrt+4joCmAUbNxwtkneNExSe7du0S7Z
; 6zgyLJvJ2OOI2WzVvyaUyxWUkJCNo2JpSo9Gzr9q26kjtGKagkyxbSOQQ3bkpzXclqJT1IwtBRQ9me
; BxMLm7fwlUwVRL8s+UW0p/B8Y8jDBw8xZtQY2NkKOJmCmxWdQzqzPHWxQTNgFgiIZWZlYuq0qXxKny
; Sxa3VXrF+/XtIyQJSXn4f1m9bDvZa76PSrqZjA3KywWaLOdCi2M4hAxbYt29hV5HxfTlHCb2d/K0oD
; 0zPSERwUTEpg0jJqAp0UziYUL4VIr2/euYmQd0JKc0nQ3kfOmlL2ljKDQkjr1rC4W3Ho824fnYdCqr
; ONrY3OtK8haxB3Ow5e9bxKZJB8G/ri6NGjks7VI6K6v/mL58OxqmOZsgb2leyxYMECQaBQ597A/Lx8
; LFm8hMWq+byccv9UrqVKBoMT9ClnOA4fOcziCyUySHb2mDZ1GrKysyCFaBmLPBuJpq2alilrQDuwKG
; hEQR8+ZX16N4eS/M6fPY92ge14+b8DBw00qH3qgSNlHnvB/AUlNkjUl/ZvtGcAVmoW7sHjBxg7cSys
; bI0WEpbsHfn5+bF28Ql6yXQJRpXS09Lx1aSvWFBF34tt7Wzx008/FW0CFTiuVGjZv29/dotFSQVbnK
; o4Yfny5cgvkBbaJoD55+4/Ubt+7TKxJBAo/HzU57zazv98AA5cHNh7QFsyoRi7uboxq6FOfELGdMgE
; HUdTkoNFXggdunzv/j1IIbIkdxPuone/3sogV6kxTSCXai64E3fHYLsFnxOYcC8BHw34SPdGEG49DO
; wQSIWcMDBgGjaCNkX06t1L0A0mxuJ6dephz549rPxaCmXnZmPpiqVwqu5U6tZg8uTJBtsr6qBIylOv
; XrkartW0V6JSEObLCV+yv+MDREgXjh0/huYtmrOMY2kNmK2NLTtyldxTlbYJBgkMO105j7Yd26oCRL
; msBPrwnDnla9G6BTKy9O9hkB0+fJhPh+TaOnn1ylV0fquztpIjBWXM9h3cB0MbTjMzM1msvapTVYjJ
; SxibyXy2atEKUWeiJAPEx+mPMeWbKbB5peSzh8SVHCoZjITKqBhj+vTpouv2s7OyETYzjF0xo94Ayp
; nTebS66Oq1qwjuHMwONyyNAdLDcurPooWLWARQLNHEoSVl/9H98Pb3LlF3kUrSbC1tWXxGnzcgU36h
; 3RvtcOWyuOoYCqxEHud84sZNFeqz6cMPPiyqcVMh+vfKVStBu3xMXQMohalt3bt1Z2clCiVVq0nLYG
; JKIgYPGwwzy5JLJ1tYW2DHrh16N6vKVL9AFz/Q8bBiK35Sk1MxctjIYjOawOKy35Y9z1hR8eegwYOK
; lYGR6Q9sG4ge3XvAqbJTaefcNbiGew2Eh4dLyr8TkTVZvYHDTh6uJQIQre2sceWq/kn9fw1g6heweu
; ktAAAAAElFTkSuQmCC
; thumbnail end
;
; 

; external perimeters extrusion width = 0.90mm
; perimeters extrusion width = 0.90mm
; infill extrusion width = 0.90mm
; solid infill extrusion width = 0.90mm
; top infill extrusion width = 0.80mm
; first layer extrusion width = 0.90mm

; external perimeters extrusion width = 0.90mm
; perimeters extrusion width = 0.90mm
; infill extrusion width = 0.90mm
; solid infill extrusion width = 0.90mm
; top infill extrusion width = 0.80mm
; first layer extrusion width = 0.90mm

M107
M190 S60 ; set bed temperature and wait for it to be reached
;TYPE:Custom
;Begin Start GCode

;set temps
G10 P0 S210
G10 P0 R170
G10 P1 S210
G10 P1 R170

G28 ;home all axis
G29 S1 ;enable mesh


T0


M116 ;Wait for all temps

G90
M98 P"prime.g"
;End Start GCode
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
;T0
T0
; Filament-specific start gcode
M703
M107
;LAYER_CHANGE
;Z:0.3
;HEIGHT:0.3
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.3

G10 ; retract
G1 Z.3 F720
;AFTER_LAYER_CHANGE
;0.3
M800 F"layer"
G1 X145.662 Y139.959 F10800
G11 ; unretract
M204 P800
;TYPE:Skirt/Brim
;WIDTH:0.9
G1 F1200
G1 X148 Y139.164 E.24705
G1 X182 Y139.164 E3.40184
G1 X183.695 Y139.559 E.17412
G1 X185.041 Y140.662 E.17412
G1 X185.836 Y143 E.24705
G1 X185.836 Y177 E3.40184
G1 X185.441 Y178.695 E.17412
G1 X184.338 Y180.041 E.17412
G1 X182 Y180.836 E.24705
G1 X148 Y180.836 E3.40184
G1 X146.305 Y180.441 E.17412
G1 X144.959 Y179.338 E.17412
G1 X144.164 Y177 E.24705
G1 X144.164 Y143 E3.40184
G1 X144.559 Y141.305 E.17412
G1 X145.586 Y140.052 E.16211
M204 P1000
; printing object A id:0 copy 0
G10 ; retract
G1 X149.55 Y161.286 F10800
G11 ; unretract
M204 P800
;TYPE:Perimeter
G1 F1200
G1 X162.467 Y161.286 E1.29245
G1 X163.714 Y162.533 E.17643
G1 X163.714 Y175.514 E1.29889
G1 X149.486 Y175.514 E1.42365
G1 X149.486 Y161.341 E1.41808
M204 P1000
G10 ; retract
G1 X166.286 Y144.55 F10800
G11 ; unretract
M204 P800
G1 F1200
G1 X166.286 Y144.486 E.00644
G1 X180.514 Y144.486 E1.42365
G1 X180.514 Y158.714 E1.42365
G1 X167.533 Y158.714 E1.29889
G1 X166.286 Y157.467 E.17643
G1 X166.286 Y144.67 E1.28044
M204 P1000
G1 X165.45 Y144.67 F10800
M204 P800
;TYPE:External perimeter
G1 F1200
G1 X165.45 Y157.814 E1.31507
G1 X167.186 Y159.55 E.2457
G1 X180.45 Y159.55 E1.32708
G1 X180.45 Y175.45 E1.59086
G1 X164.55 Y175.45 E1.59086
G1 X164.55 Y162.186 E1.32708
G1 X162.814 Y160.45 E.2457
G1 X149.55 Y160.45 E1.32708
G1 X149.55 Y144.55 E1.59086
G1 X165.45 Y144.55 E1.59086
M204 P1000
G1 X166.223 Y144.464 F10800
G10 ; retract
G1 X181.35 Y143.65
G11 ; unretract
M204 P800
G1 F1200
G1 X181.35 Y176.35 E3.27177
G1 X148.65 Y176.35 E3.27177
G1 X148.65 Y143.65 E3.27177
G1 X181.23 Y143.65 E3.25976
M204 P1000
G1 X181.143 Y144.423 F10800
G10 ; retract
G1 X178.573 Y144.695
G11 ; unretract
M204 P800
;TYPE:Solid infill
;WIDTH:0.920626
G1 F1200
G1 X179.929 Y146.051 E.19673
G1 X179.929 Y147.262 E.12415
G1 X177.738 Y145.071 E.31778
G1 X176.527 Y145.071 E.12415
G1 X179.929 Y148.473 E.49335
G1 X179.929 Y149.684 E.12415
G1 X175.316 Y145.071 E.66892
G1 X174.105 Y145.071 E.12415
G1 X179.929 Y150.895 E.84449
G1 X179.929 Y152.106 E.12415
G1 X172.894 Y145.071 E1.02006
G1 X171.683 Y145.071 E.12415
G1 X179.929 Y153.317 E1.19564
G1 X179.929 Y154.528 E.12415
G1 X170.472 Y145.071 E1.37121
G1 X169.261 Y145.071 E.12415
G1 X179.929 Y155.739 E1.54678
G1 X179.929 Y156.95 E.12415
G1 X168.05 Y145.071 E1.72235
G1 X166.871 Y145.071 E.12097
G1 X166.871 Y145.102 E.00318
G1 X179.898 Y158.129 E1.88892
G1 X178.688 Y158.129 E.12415
G1 X166.871 Y146.312 E1.71335
G1 X166.871 Y147.523 E.12415
G1 X177.477 Y158.129 E1.53778
G1 X176.266 Y158.129 E.12415
G1 X166.871 Y148.734 E1.36221
G1 X166.871 Y149.945 E.12415
G1 X175.055 Y158.129 E1.18664
G1 X173.844 Y158.129 E.12415
G1 X166.871 Y151.156 E1.01107
G1 X166.871 Y152.367 E.12415
G1 X172.633 Y158.129 E.8355
G1 X171.422 Y158.129 E.12415
G1 X166.871 Y153.578 E.65993
G1 X166.871 Y154.789 E.12415
G1 X170.211 Y158.129 E.48436
G1 X169 Y158.129 E.12415
G1 X166.871 Y156 E.30879
G1 X166.871 Y157.211 E.12415
G1 X168.165 Y158.505 E.18774
M204 P1000
G10 ; retract
G1 X161.835 Y161.495 F10800
G11 ; unretract
M204 P800
G1 F1200
G1 X163.129 Y162.789 E.18776
G1 X163.129 Y164 E.12415
G1 X161 Y161.871 E.30881
G1 X159.789 Y161.871 E.12415
G1 X163.129 Y165.211 E.48438
G1 X163.129 Y166.422 E.12415
G1 X158.578 Y161.871 E.65995
G1 X157.367 Y161.871 E.12415
G1 X163.129 Y167.633 E.83552
G1 X163.129 Y168.844 E.12415
G1 X156.156 Y161.871 E1.01109
G1 X154.945 Y161.871 E.12415
G1 X163.129 Y170.055 E1.18666
G1 X163.129 Y171.266 E.12415
G1 X153.734 Y161.871 E1.36223
G1 X152.523 Y161.871 E.12415
G1 X163.129 Y172.477 E1.5378
G1 X163.129 Y173.688 E.12415
G1 X151.312 Y161.871 E1.71337
G1 X150.101 Y161.871 E.12415
G1 X163.129 Y174.899 E1.88894
G1 X163.129 Y174.929 E.00317
G1 X161.949 Y174.929 E.12098
G1 X150.071 Y163.051 E1.72233
G1 X150.071 Y164.261 E.12415
G1 X160.739 Y174.929 E1.54676
G1 X159.528 Y174.929 E.12415
G1 X150.071 Y165.472 E1.37119
G1 X150.071 Y166.683 E.12415
G1 X158.317 Y174.929 E1.19562
G1 X157.106 Y174.929 E.12415
G1 X150.071 Y167.894 E1.02004
G1 X150.071 Y169.105 E.12415
G1 X155.895 Y174.929 E.84447
G1 X154.684 Y174.929 E.12415
G1 X150.071 Y170.316 E.6689
G1 X150.071 Y171.527 E.12415
G1 X153.473 Y174.929 E.49333
G1 X152.262 Y174.929 E.12415
G1 X150.071 Y172.738 E.31776
G1 X150.071 Y173.949 E.12415
G1 X151.427 Y175.305 E.19671
M204 P1000
; stop printing object A id:0 copy 0
G10 ; retract
; Filament-specific end gcode
;T1
T1
; Filament-specific start gcode
M703
; printing object A id:0 copy 0
G10 ; retract
G1 X166.286 Y173.714 F10800
G11 ; unretract
M204 P800
;TYPE:Perimeter
;WIDTH:0.9
G1 F1200
G1 X166.286 Y161.467 E1.22535
G1 X163.533 Y158.714 E.38956
G1 X151.286 Y158.714 E1.22535
G1 X151.286 Y146.286 E1.24355
G1 X163.714 Y146.286 E1.24355
G1 X163.714 Y158.533 E1.22535
G1 X166.467 Y161.286 E.38956
G1 X178.714 Y161.286 E1.22535
G1 X178.714 Y173.714 E1.24355
G1 X166.406 Y173.714 E1.23154
M204 P1000
G1 X165.45 Y174.55 F10800
M204 P800
;TYPE:External perimeter
G1 F1200
G1 X165.45 Y161.814 E1.27433
G1 X163.186 Y159.55 E.3203
G1 X150.45 Y159.55 E1.27433
G1 X150.45 Y145.45 E1.41076
G1 X164.55 Y145.45 E1.41076
G1 X164.55 Y158.186 E1.27433
G1 X166.814 Y160.45 E.3203
G1 X179.55 Y160.45 E1.27433
G1 X179.55 Y174.55 E1.41076
G1 X165.57 Y174.55 E1.39876
M204 P1000
G1 X165.657 Y173.777 F10800
G10 ; retract
G1 X176.775 Y161.495
G11 ; unretract
M204 P800
;TYPE:Solid infill
;WIDTH:0.919592
G1 F1200
G1 X178.129 Y162.849 E.19618
G1 X178.129 Y164.059 E.12385
G1 X175.941 Y161.871 E.31687
G1 X174.732 Y161.871 E.12385
G1 X178.129 Y165.268 E.49202
G1 X178.129 Y166.478 E.12385
G1 X173.522 Y161.871 E.66716
G1 X172.313 Y161.871 E.12385
G1 X178.129 Y167.687 E.84231
G1 X178.129 Y168.896 E.12385
G1 X171.104 Y161.871 E1.01746
G1 X169.894 Y161.871 E.12385
G1 X178.129 Y170.106 E1.19261
G1 X178.129 Y171.315 E.12385
G1 X168.685 Y161.871 E1.36775
G1 X167.475 Y161.871 E.12385
G1 X178.129 Y172.525 E1.5429
G1 X178.129 Y173.129 E.06192
G1 X177.525 Y173.129 E.06193
G1 X166.871 Y162.475 E1.54288
G1 X166.871 Y163.685 E.12385
G1 X176.315 Y173.129 E1.36774
G1 X175.106 Y173.129 E.12385
G1 X166.871 Y164.894 E1.19259
G1 X166.871 Y166.104 E.12385
G1 X173.896 Y173.129 E1.01744
G1 X172.687 Y173.129 E.12385
G1 X166.871 Y167.313 E.84229
G1 X166.871 Y168.523 E.12385
G1 X171.477 Y173.129 E.66715
G1 X170.268 Y173.129 E.12385
G1 X166.871 Y169.732 E.492
G1 X166.871 Y170.941 E.12385
G1 X169.059 Y173.129 E.31685
G1 X167.849 Y173.129 E.12385
G1 X166.495 Y171.775 E.19616
M204 P1000
G10 ; retract
G1 X161.775 Y146.495 F10800
G11 ; unretract
M204 P800
G1 F1200
G1 X163.129 Y147.849 E.19618
G1 X163.129 Y149.059 E.12385
G1 X160.941 Y146.871 E.31687
G1 X159.732 Y146.871 E.12385
G1 X163.129 Y150.268 E.49202
G1 X163.129 Y151.478 E.12385
G1 X158.522 Y146.871 E.66716
G1 X157.313 Y146.871 E.12385
G1 X163.129 Y152.687 E.84231
G1 X163.129 Y153.896 E.12385
G1 X156.104 Y146.871 E1.01746
G1 X154.894 Y146.871 E.12385
G1 X163.129 Y155.106 E1.19261
G1 X163.129 Y156.315 E.12385
G1 X153.685 Y146.871 E1.36775
G1 X152.475 Y146.871 E.12385
G1 X163.129 Y157.525 E1.5429
G1 X163.129 Y158.129 E.06192
G1 X162.525 Y158.129 E.06193
G1 X151.871 Y147.475 E1.54288
G1 X151.871 Y148.685 E.12385
G1 X161.315 Y158.129 E1.36774
G1 X160.106 Y158.129 E.12385
G1 X151.871 Y149.894 E1.19259
G1 X151.871 Y151.104 E.12385
G1 X158.896 Y158.129 E1.01744
G1 X157.687 Y158.129 E.12385
G1 X151.871 Y152.313 E.84229
G1 X151.871 Y153.523 E.12385
G1 X156.477 Y158.129 E.66715
G1 X155.268 Y158.129 E.12385
G1 X151.871 Y154.732 E.492
G1 X151.871 Y155.941 E.12385
G1 X154.059 Y158.129 E.31685
G1 X152.849 Y158.129 E.12385
G1 X151.495 Y156.775 E.19616
M204 P1000
; stop printing object A id:0 copy 0
G10 ; retract
M107
;TYPE:Custom
; Filament-specific end gcode
; Filament-specific end gcode
M106 S0 ; turn off cooling fan
G10 P0 S0 R0
G10 P1 S0 R0
M140 S0; turn off bed
;Drop the bed
G91
G1 Z10 F1000
G90
M0
; filament used [mm] = 98.49, 56.76
; filament used [cm3] = 0.24, 0.14
; filament used [g] = 0.29, 0.17
; filament cost = 0.01, 0.00
; total filament used [g] = 0.46
; total filament cost = 0.01
; estimated printing time (normal mode) = 1m 24s

; prusaslicer_config = begin
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = G:\\Rancor\\Rancor\\PrusaSlicer\\BedModel.stl
; bed_custom_texture = G:\\Rancor\\Rancor\\PrusaSlicer\\BedTexture.png
; bed_shape = 0x0,330x0,330x320,0x320
; bed_temperature = 60,60
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 3
; bottom_solid_min_thickness = 0.8
; bridge_acceleration = 1000
; bridge_angle = 0
; bridge_fan_speed = 100,100
; bridge_flow_ratio = 0.9
; bridge_speed = 22
; brim_separation = 0.1
; brim_type = outer_only
; brim_width = 0
; clip_multipart_objects = 1
; color_change_gcode = M600
; complete_objects = 0
; cooling = 1,1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 1000
; default_filament_profile = ""
; default_print_profile = 
; deretract_speed = 0,0
; disable_fan_first_layers = 1,1
; dont_support_bridges = 0
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0.2
; end_filament_gcode = "; Filament-specific end gcode";"; Filament-specific end gcode"
; end_gcode = M106 S0 ; turn off cooling fan\nG10 P0 S0 R0\nG10 P1 S0 R0\nM140 S0; turn off bed\n;Drop the bed\nG91\nG1 Z10 F1000\nG90\nM0
; ensure_vertical_shell_thickness = 1
; external_perimeter_extrusion_width = 0.9
; external_perimeter_speed = 25
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 45
; extruder_colour = #FF8000;#0000FF
; extruder_offset = 0x0,0x0
; extrusion_axis = E
; extrusion_multiplier = 0.96,0.96
; extrusion_width = 0.9
; fan_always_on = 1,1
; fan_below_layer_time = 100,100
; filament_colour = #FF8000;#FF8000
; filament_cooling_final_speed = 3.4,3.4
; filament_cooling_initial_speed = 2.2,2.2
; filament_cooling_moves = 4,4
; filament_cost = 24.99,24.99
; filament_density = 1.24,1.24
; filament_diameter = 1.75,1.75
; filament_load_time = 0,0
; filament_loading_speed = 28,28
; filament_loading_speed_start = 3,3
; filament_max_volumetric_speed = 15,15
; filament_minimal_purge_on_wipe_tower = 15,15
; filament_notes = "Affordable filament for everyday printing in premium quality manufactured in-house by Josef Prusa";"Affordable filament for everyday printing in premium quality manufactured in-house by Josef Prusa"
; filament_ramming_parameters = "120 100| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6";"120 100| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = PLA;PLA
; filament_soluble = 0,0
; filament_spool_weight = 0,0
; filament_toolchange_delay = 0,0
; filament_type = PLA;PLA
; filament_unload_time = 0,0
; filament_unloading_speed = 90,90
; filament_unloading_speed_start = 100,100
; filament_vendor = Prusa Polymers
; fill_angle = 45
; fill_density = 15%
; fill_pattern = gyroid
; first_layer_acceleration = 800
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 60,60
; first_layer_extrusion_width = 0.9
; first_layer_height = 0.3
; first_layer_speed = 20
; first_layer_speed_over_raft = 30
; first_layer_temperature = 210,210
; full_fan_speed_layer = 0,0
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 30
; gcode_comments = 0
; gcode_flavor = reprapfirmware
; gcode_label_objects = 1
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = duet
; infill_acceleration = 1000
; infill_anchor = 2.5
; infill_anchor_max = 20
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.9
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 30%
; infill_speed = 50
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]\nM800 F"layer"
; layer_height = 0.4
; machine_limits_usage = time_estimate_only
; machine_max_acceleration_e = 1500,1500
; machine_max_acceleration_extruding = 1500,1500
; machine_max_acceleration_retracting = 1500,1500
; machine_max_acceleration_travel = 500,1250
; machine_max_acceleration_x = 500,500
; machine_max_acceleration_y = 500,500
; machine_max_acceleration_z = 100,100
; machine_max_feedrate_e = 60,60
; machine_max_feedrate_x = 180,180
; machine_max_feedrate_y = 180,180
; machine_max_feedrate_z = 15,15
; machine_max_jerk_e = 25,25
; machine_max_jerk_x = 6.7,6.7
; machine_max_jerk_y = 6.7,6.7
; machine_max_jerk_z = 1.7,1.7
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100,100
; max_layer_height = 0,0
; max_print_height = 601
; max_print_speed = 50
; max_volumetric_speed = 0
; min_fan_speed = 100,100
; min_layer_height = 0.07,0.07
; min_print_speed = 15,15
; min_skirt_length = 4
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.8,0.8
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_T0-{filament_preset[0]}_T1-{filament_preset[1]}.gcode
; overhangs = 0
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 800
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.9
; perimeter_speed = 35
; perimeters = 2
; physical_printer_settings_id = Printer 1
; post_process = 
; print_settings_id = N0.8 0.40mm QUALITY
; printer_model = 
; printer_notes = 
; printer_settings_id = Rancor
; printer_technology = FFF
; printer_variant = 
; printer_vendor = 
; raft_contact_distance = 0.2
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 0
; resolution = 0
; retract_before_travel = 2,2
; retract_before_wipe = 70%,70%
; retract_layer_change = 1,1
; retract_length = 0.5,0.5
; retract_length_toolchange = 0,0
; retract_lift = 0,0
; retract_lift_above = 0,0
; retract_lift_below = 600,600
; retract_restart_extra = 0,0
; retract_restart_extra_toolchange = 0,0
; retract_speed = 40,40
; seam_position = nearest
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 0
; skirt_distance = 3
; skirt_height = 2
; skirts = 1
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 20,20
; small_perimeter_speed = 25
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.9
; solid_infill_speed = 45
; spiral_vase = 0
; standby_temperature_delta = 170
; start_filament_gcode = "; Filament-specific start gcode\nM703";"; Filament-specific start gcode\nM703"
; start_gcode = ;Begin Start GCode\n\n;set temps\nG10 P0 S{temperature[0]}\nG10 P0 R{if temperature[0] == 0}0{else}{temperature[0] - 40}{endif}\nG10 P1 S{temperature[1]}\nG10 P1 R{if temperature[1] == 0}0{else}{temperature[1] - 40}{endif}\n\nG28 ;home all axis\nG29 S1 ;enable mesh\n\n{ if current_extruder == 0 }\nT0\n{ elsif current_extruder == 1 } \nT1\n{ endif }\n\nM116 ;Wait for all temps\n\nG90\nM98 P"prime.g"\n;End Start GCode
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = 0
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.25
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.7
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 2
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0.4
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 40
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 50
; support_material_with_sheath = 0
; support_material_xy_spacing = 80%
; temperature = 210,210
; template_custom_gcode = 
; thick_bridges = 1
; thin_walls = 0
; threads = 32
; thumbnails = 128x128
; toolchange_gcode = ;T[next_extruder]
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0.8
; top_solid_infill_speed = 35
; top_solid_layers = 4
; top_solid_min_thickness = 1.2
; travel_speed = 180
; travel_speed_z = 12
; use_firmware_retraction = 1
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wipe = 0,0
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 170
; wipe_tower_y = 140
; wiping_volumes_extruders = 70,70,70,70
; wiping_volumes_matrix = 0,140,140,0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
