; generated by PrusaSlicer 2.4.2+win64 on 2022-05-19 at 02:57:15 UTC


;
; thumbnail begin 128x128 11240
; iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAgs0lEQVR4Ae1dCXyM1xafyG6LLHaxpR
; I7FUmIaNUS2tqLqGcp0pKWCi2tpeWpqD61xLMEfWhRBMWTUlvVs1QUUbFHxBJb9n01/3nfuTHpTDLf
; zLfMjKRyfr/zE8nM9917z7nnnv0q8ByUSiWuXb2Gnj16wsLCAgqFwuRoaWmJsWPHIjsrmxsABAONde
; 26tbzjdHZxxr9X/xvZOdmQCKqbN27izTffZGNs1LARps+YjujoaOQX5MMYcODnA2ju3hyVKlXiXR+X
; mi4I/XcosrKzSn1fSYsgEAoKCxC+OxyNmjQq/R76QGFhITb8ZwNq1aollZhKyUxgZYmtW7ZCWSCCAz
; jIzc3F+4Hvo5LFXwtoUckCnbp0wvmL5/V+l2/xVBzQWmz5YQvq1qlbaqw2tjbw6+rHmO/pk6fAM4hi
; XIK01DRM/2Q6HKo7CFofKysrDBo8CLfv3FZBJty5ewcDBg9AJUsNpnv48CFGjhzJXiRnN8tBJ2cnXL
; 1yVdRknimf4d6De+jcqTPbpfaV7fH57M+Rmpaq93v6iP/48WOMHT0Wtja2/OO14NCySMoEjgvE0SNH
; kZOfAyFw4fwF+Pn6sfGKXSM3Nzfs2LlDmZ8vXgLR3NQ/Z2dnI3RlKFtz9uxmzZq9MMIXI7egvl19kZ
; WbxW0o4VuKaBl9KRrd3uiGg4cO4tmzZ5AC9L1jR4+hZfOWosduZW2Fpq80xZdffolr166hML+wSDJo
; ABEtdFkoateqLfb5Ko2flXa2dvho0kdISEyAXDh3/hx8fH3ouSYnsKDjwcLSAjNnz4QUMER4fbs+Mz
; MTc2bNQdUqVWXP1dbWFv379cfmHzYjIyODMeid2DsYPHAwbGxstD77+muvY+WKlWjk2oiP8Cpd60d6
; j2dHT/z2v98gQg3QCSQtxTKA1LNe0Pccazji0KFDMCboUZZUly9dRreu3Yyu9NIZW7dBXYwcPRINGz
; bUen61qtWYtCAGKSgoACmbxCAax4JKyLrVqFEDCxctREZmRumJaYh8Q6BQKORP2JgM4+Hhgbv37sJU
; QItDCx+2OgwuTi6mnHuRvqDx/5YtW+L4r8e1di79nJ6ezo4IJ0cnUc+3srRC7969ceXaFYgBTQYxNQ
; OI3z2cVv9uwLvIzMqEVNC36+/du4eAoQGwtrI225ysra0ROD4QT5484R1zXl4eIs9GootvF9GbxtXV
; Fd//8D17hj7QJLx6jczJAIInZmNtg7Vr18o+4zQnTnrCf/f9F02bNDXXfBnWq1ePmbl8eoomUTgTVJ
; mQkIDPpn+GKpWriHoP6RjvjX0PDx89NPgezQ1iTgYQhTVr1sTFqIsQCvoUvdSUVAR/HAx7e3uzjZ/O
; /bffehsxt2IgFnJycvDz/p/h4e5h6D2qku9s1bqVXouo5DrpYgCxIkiyE8gQ+nX2Q0Z6hsEF4yM+92
; vVuUjO3PHyganGqAtJQfvXN/9ihNQFfLtREwoLCrHtx236PIUqvveTRTN7zmykpacZfI/CCBM2GQPQ
; OT1n5hzOlwmdHjd9u57+JY9dDccaMNX4dKFnB0+c/f0s7/GlHps+Vy4xzpLFS1C1qnTTlKyK115/De
; cv6PeKGoMBTMoIJLbJby4FDh48iBoO5mEAOzs7TPl4CpKSkqCP8IaIH3s7Fn1699EbIzCAWmZk7dq1
; lavXrOaNiygkEk7J87PxsRKnSDWsh5iYGL2Lp8v2zSvMw/yQ+SzeYMoxNmrUCHv37jW46/VBQT4XsN
; kejnp168kZi04fAlkhwwKGIe5uHHQxgP6HWijU9qxpCa0HybEyZMgQMg110l/fAufk5mDwkMHM02j0
; cXG7dOiQoSDT0hDo2/VJiUkYP268pBgBD+qklbu7O37a8xNzQAljAG73tfdqj1lfzGKhSVMRWAhSsG
; rN2jVsVwshvCaQ/e3R0oPNx1jjcXZ2xqqVq8AXnBEyNuUzJU78dgItW7Q01rgMblJ7O3sETw1GUnKS
; fgawsrNC8IxgJKYkIr8wH5euXsJr3V4zKZENTYo8d+fOnRO8wJrw+5nf4VDNAcYYk5+fHy7/eZn3XU
; IUPcqBmP/P+Ux30PEOlZx1MoQkuXx8fHDy9EkdDMCJ+8avNMaen/ewRAI1UPg1KS0Jc+fPNac9XTwp
; C4UFbCy5eHwnP6Qmp4oiPtEhLzcPYavCYFVJetibzKtZM2chPS1dyDt5iU+h765+XfliECqpayQWHR
; 0dSzAAF5YdMmKI8m78XZ0KDYVqSQQfPn4YLVq2MBaRxaDKspIlPp32KfKy80QnY+Rm52LEuyPYPMW+
; m2IUhw8fluWdJFctJd64OBvtODWGXqZgu965tjNWf8eZC7nZWtyri5MLlYWIfxqP8R+Ml2OuiJ1U8c
; 6gcyxifwSkAJ193p282XNecanMUN94SPcYM2YMHj16ZPDZ+nb940eP8e7wd41m3hlvvTnFyO8NP0Rd
; iSIxrxQ6MfpVdl42Nm/fjLr16sJ4A9I78SLkxly/YX3cjRMfNSR9Jio6CiM6NsSJIB/Vz+M6qoa0ra
; Pz3XVq18GmjZtYypwh4CM+uWTJj0EZPSZcI+k465+zkJKeIirJUBNy83LZbiRbU8ZADO76UshJrUGD
; BjEHh5ihF2Sl4+rGL1VEfE0MHdBCVafaX6lg/v7+uHH9hs5nCFVAKeY//dPpctfGtFj4TJu7hTICfY
; yyadb/Zz1q1qppXuI/R7KbKb9N0zTUB5n3byJyzsBSxFcjSYPerRogJCSE5c7pAkEePWVR/p+3l7cc
; Rc9EIr8EQgKQSLz/4D5GjBzxQgivic61nBEZGWlwzLfDl/ISviTGcJ8tzObPtNG3SShbecXyFaherb
; qctZFiBpqeAWjeNMGIAxFwaybrTBPF0bSLHBwc0OetPqXtZk6j9/LywsN43XFw2vXnQ0YKJr4a6Tv0
; XR1rwEt80kn69e1nTEXP9N5XCARSZigbdcbnM0olOBqB8LwcT2K+g2cHnDpzionWiIgINGnSpNTnKN
; 5fkFugZRo+OLYNYgmviaen9VDFH9umKnguDfiIT67V3Tt3w7WBqxxiGBT5lAJmZ2WnVQthFgYgd2fk
; H5HF5pM5iE+7nnb75CmTkZySrDWe+Ph4DB8+XGun0c+7wncxBiCCXQmbrpJDfE28tDRIlZOoW8KkJK
; cgaGKQMf34OpHyBVf9exVOnjiJDu07GE+xhIFdn5aexsqTnnuNzIJEzCZNm2D3T7t5TTDadevWrYOL
; y19OFcqN+/PIT6Cdayzia0qDx2f2F7+fhMGpk6fQpk0bY82bV9xTMcnFCxeL14KCRx9N/AjVqlWTn9
; HMR3xa4Nuxt9F/YH9TTIpX5BNnD3pnEO7dNxxhI7h69SrLsafvTvZrbHTCl8Qb389nR0LMzRiWtiZr
; 8Q2sE+UFzvx8Jisn03X67Nq5C40bNZYnfUo+lF5EGSnhu8Lh2lDWmQYxxCdOpgVduWYlbyoVHzy+dg
; EHgrqanPiaCmJC1HFciroE745app4UP75O4ns088ChXw5phW51QVxcHAYNGMSOS0nSQPNhJGIeP3mM
; jyZ/JCeJQvSuJ3drZ9/OuBB1AWJBrqIn50igd6cnPsGMT2YITTM3yCAkAceMGoP4B/GCS92ISZYvXY
; 5aNWuJt0DUDyFF78T/TqBNW1lnmmhFr0qVKqwkjHQNMUBiWIp5Z2wkBTE7IR6HDx7Wl3IuSDLUrlkb
; mzZsYrSQ4piNuhgFXx9fWFuKUBApzEuu4IXfLJSVhCh24pTl49HcQ1JRJyljL5rwuqRBwpMEvDvsXV
; DEkmcNlHwbwb+nP9NnhMQddAGLzWRkY8rkKeIYgFXYXo1Gm1aSd74kRW/U6FHsuBELpISVJeKXlAa5
; 3Gba+N1GVucoZP2oVjBkfghzq0sNNVMKeXRUNHy9fcVXPKkfQn0Cxr03jlW4GoH4unc9dz5R5HDDpg
; 3Iyxfmv1eDIT9+WZIGiZd+U924dkNdeMq7Ru3atMOp/50yqOjpg/zcfIStDIOTg5NQB5FKJwOwh3Fn
; z9bNW1G/bn1xXMT3cA0kRa9Hrx64duMaxELc/nVlSuQLQYo9ZKUkYf7c+aUaTtAmm/jBRNZlRHJPg8
; JneHD3AQa8PQC21raQSC/dZuD169fx9ptv82mUohW96tWr46uQr5iYEwNS/fhlBWnsGfduMO8daz5h
; UeSsIo+llE4faijIK8D+vfvR2LVxSX1DPgOogcKhi75epFlYITowQQ6Kdu3b4cTJE6LPtxdl3hkb1Q
; pianIqFoYsZIUfUnc9KyVPScfkoMmwtzVSXqa+F9JAz5w+Ay9PL9Ein4m5DyciMSkRYsDYfvyygvri
; CUKAFL3IM5F4te2rLCgkgLjCnFKGXkwRsMTERHz80ceCsoHp2KBKmR07d4g2aVJvnjeJH78sSQPNeI
; IQoF2fn5OPxV8vRvUq1Y3fwk/Pi7VkNmmqe3bvQZPGTfgVPWsr9BvQD3fi7kAsiEnYKO+ojicYAlL0
; Ym/GoneP3qxnglEJL1QClABVbGwshr4zVKutHHElVcosC10mujljeTHvjI2kIJLE4wPKbdi2eRvq1q
; prisxrcQxQMgmS8tupw5WzkzNrzujl7cXajomFv4uiJxXVCqKmNCC9KykhCeNGj4OdjZ3pCF+SAcRU
; 3T7/PK5cvoJF3yxCSkoKxABNmJSi8kQsU6JaQaTCm6PHj8LtFTehip7pJIDg2juR3suy5scvK6iWBp
; Tb+M7Ad+Tb96WxlBnPFMpVa1aV6i4ltvBSKJRlP35ZQSYN0lKwPmw9alQ3XXMLqq6aMH4C97OVAkOG
; DcGDBw9MRvyXVdGTiiyeEPUbrkZfZX2SZCScQNeud63viu1btnPOBXV5uKUCjdwaqfbu2yvZS8UH5d
; GPX1aQTOPM5ER8MesLo5iBnOWm7Pd2P2Zaqo9uRTFnVeLCtPbWmDJ1CpKTkyEXyrsfv6wgrWH6ves4
; fuw4SxOTctYTUlbxkm+WMKeSpt6m0PogtYLhjoRXO76Ks5FnIRVedvPO2KhWEJOTkvHeqPdEJYGSyK
; e8xfNnz5fqYk7HvULnFzlp4ODsgMVLFvPWyOkCMu8qFD3TISmImU/uY9uWbajpYjgjmdLtpk6eitSk
; 1FLWmlrXU/A+4Lk06PN2H5YebggqFD3zoFpBvH3rNnp170VJIDrNO7cmbojYG8EUPX2gMChGOAWxrm
; tdbN22lTe48zL58csK0ppnpybhX1//i5l0anqRshgwJADxd+N5d704Bnh+JFjaWiJwQiCePn2qtesr
; FL0Xh+qEk8jfI9G2dVvUr10fa1euLbq1RCAIYwD1kcBJg+atmuPX479WKHplBNUKYsrjR7h17ZZORc
; 84DPAcq9pb4uu+LcrVIr0MqCvhRIhTTxQD+DVxBHXRKE8L8zKhOuFE1JUxlPPH4s0W+ok/s3vTcrUY
; LzPqSjjRFe29FXMLivTkdJz830nMXzAfb/V7i10eqelooDZqO0a2L1cLUIFFCiKZi7qAMpI3b93MSv
; A18wGQW5CLtKw0RJ6LxLfffovgnq0qFL1yjLoSTsiKe/+D91G5cuWiIJMuDiFlosK8+/uguoD16LGj
; aN++vXZ3kZLEr0jY+Hvi8UldVWM6u5XOL9QkfoUf/++P1BCzqq2lNgOQyK/w4788SKZ8M5cqfzHAo5
; ir+GFCL9WxCd7laiIVKA3n9HhF5VzZ5i8GoKKPc2dPYZSvu2rnqFfL1WQqUDjufa+Dqm+LWtppZTnZ
; OQhbH1bc8crNuTLWDG5VIQ3+ZrhyYEuVR80qpXMKhw0fVsoLaGdVCR90clVFjPMsV5OswNJIu/59H1
; dVNVveOgN+92+Xxo5YP7R1uZpwBf6F64a0Vn0Y8JbKvoq9vltS9McAalezxYxuTVW/BHqVq8m/zHjk
; Ay/V1uBBqjs3/mR3PcU/jGdt9X27+sLaxlocA6iPhLda1FRtebdduVqIlxFJ5Ees+qpUNJB1EcvNxr
; Wr11ijipYeLVnjaYWBKKCW0tDI0R6L+zavUBDLKIaN8FFF/fYL9AGl9REzUMOJU6dOQeHp5WmoK6iy
; pDQY8Wq9CgWxDCHt+g2f/EOVnSGu2SaBgtK+qUHh1OCpRY2HK1mqhBQmejZwYApihTR4sUiK3tFt30
; EqFMUCKFWgkDUlUO39aS/GjhmrpEuMDbUjIQWRzMUKBdH8SIrexkkDVYkP70MO6GoTxzJHEhMSsW3r
; NgzsP5DFjvnMCLWCuDGgbblawPKM4Zy39o1mLip2q5m0zrL8DKAFhUUXHNPt2CFfh7C+/Jo56CUVxI
; VvelQcCSbGRW95qOpVL2oM2adPH3YbqmwGEHJVHLtHIC8H0dHRWLhwIWt8aGtlq9WelKTBO23qVMQT
; TIC6/Ph0RK9YsUJWRbdC7IWRxWZEYaGKrkyZMmUKyy0rTjSwKIonVCiIxkNePz6HdJvar8d+Fd2phX
; 1eCdFdwnQyBCUZHvjlAEaOGYlqjtVYJZE6nlChIErHA+M7GvLjM2zXth0SHyeWKgrRBxmpGcjNypXP
; AJpATY6eJj3F+o3r0dO/JzWWVFbEE6QhKdVkagvx1NJRMHbc2FKtfvQB9W2mizqMygAaN2syvSImJg
; Zr1qzB0L498Vl3t4ojQSBO52IvxQkbQpA7du2r2mPLli2ijoKEhATjMgAf5Obn4uKFs/h+3qQKBVEP
; kqLXy91Fch+gBnUasE7vdEO6EKDjm5cB6FwXq10KUShvXzyD8I/6VEiDEkjmXWNH+R3A/Xv5IzNbeF
; t+nQxAopzOiNDloTh85HDxjRZKHvki1pLI4XzW/w2ZVBFPCCra9aM966tsLI3TDpa6tM+aPQslb4UX
; xQBqePLkCbr36I43ur2BHTt2sKqhgmcFsoivCZF7NmFnoN9LKw3Ij9+mTjWj3hROCqGjkyOOHDki6C
; oagzoA3SXUyacTe3Dr1q3Z7WIPnzyk40Eph/hqoIzkH4MHv1TmIvnxg7s2FqfoiUSqAHoQ/8AgEwhS
; Aul2Svdm7kUcVskCVR2qKocFDFMePHiQmR4kbuTwAh0Jh8JCVHsmdFWdCHrxBDIlkh+/m5uTylSE15
; QEVANo6HIuQQxAYv+Pi3+gTs06sFD8dQsWhY3pssR58+cxF3FerribwEpCbNTv+DHI/297JGj68U2O
; z5t8bdywkcVzZDEAAe3wTRs3oWpl3ZdL0v0BvXv3xrr165CUkgSpQNLgcOjMv5W5qDMf3wzIbVa2ae
; kKO34G4GEOzS4T6rM+JzcHkyZN4s8T4FzAFDauXbs2uxaN7huie+2kwOUju/8WCiIpepwfH+YmvibS
; dbLpGek611mRl53H6z1SPgfN36WkpqD7G92FcaClBVq1bYUlS5YgLjYOz/KfifJXk4J44OvJ5VJBJE
; XvQ99GBv345kAK1M2eNVunQqj4bv13OhU4Pg2ffAHRN6JRq24tg21lis8iDimpZOCAgdi9czfS0tIE
; K41qBZGkQXkh/nM/vtlFvj6kqOHBX0rf06ygkrCoS1GCiK8GyjXfun0r6x0ohRsbNGiAaVOn4eLFi2
; xA9Dw+J5P6KGIKImculvUjQbQf34zYoUMHxMfHazOApYWlytvTGylpKUQIwbZ9QWEBvpz3peTBkB5B
; XqtOnTph7XdrkZhq+H7BYmlQBhVEuX58c+H4ceORm/tXFpGCfkka/GczP1PmFYoz40iU9+vXT+jLeW
; 8e7dmrJ/M1CAWSBmUpnrC0XwvthI3nx56a0QlpjdVY2a4yk4RkRnMb0OxMsGblmmJdTPGcMMoqlavg
; 8OHDEAMUTSLCNW3aVNLVZtWqVcOCkAXIysqCWCgL8QR14aWDvQ3ru1O1alW0bdcWI/4xAl/M+wIbNm
; zAwUMHcTHqImLvxOL2ndu4e+8uYu/FIupCFE7+dhKbv9+Mbxd/i/Hjx8O/jz/q1asHGxsb7T4+RkTm
; KnZ0xJU/rzAmUGj+sblHc0ZQMV49+uzRo0dZa3IxA2nTtg1OnjoJOUDHlTqeYG7ik3nXoaETur/eHX
; NmzsHBAwfx8NFD1mlNaCCm5DqSV5U2w+XLl7Fu3ToEBgYyD6y1rXWRiW1ERqAE38z0TKUWA1B/wNGj
; RyMjM0NUKJgGv2jRIkFWAXF20IdBoOto5YAmk5oznkDm3YqRr6m+W7kMt27dYrd7wri37GgBmW4XLl
; zAvH/OY/cGi7ksQh/Sc2Z8OkNbAqhFBJ9pqA/ys/MxdMhQvcUkDVwbIHxnuKy4weXoyxg+fDiWLV2G
; hKcJxb9XK4gRQa+bVOTvXj5PlZ8n/ep3qUCWUk5ODi79cQmB4wOLG3rIwec3w5f+Q62atXDunMibQD
; ma3ntwDy3btizFBPT/AQMGiFL0SgJprmFrw1CzVk32POJgsm0DhgUoD/1yCJlZmUxqmUpBFFJ4aRZ4
; ViT9yJz7ZuE3cHNzE+aPKUJdirgO8cBppt26dmM+fSXE6QPUSt7Zxbn4WaRwLA9dLiphsSRwYU1lwP
; AAXkWTfu/u7o65c+fidsxtZKen4vDymUZREOUUXpoaaL2zMrOwatUquHu465O+Sj1MoeBd1GmfTkN+
; Qb7eRMOSfgP676qVq2BtZQ1vH292fkkF2tH7/rtPybhcwITUvoVevXox7frs3i2y4glyCy/NBRTtS3
; yaiIVfL4STs5PYo4D/j1WqVcG+vfvE1Z+RTpT3DDvDdyI1NRVSITklGdM+mcYIKoKbVZrM4OLigoB+
; vbF6Yj+IURCNVXhpTmBWBOfHiY2LxdjxY0nZVspmAIrstWjeAnF3pJ/dUiYSeS5S2bFjR4PVyYKQOx
; /tbCuhf5u6qk0CCli3jmin2rNivlFuTyXFjYhC/5oTOMtBGRERwY5FeQzAoVUlKwx+ZzBSM1Jlae9C
; gHoVLF22lOkNsgmvAw0VsK4I8FLdvHBGFvHJjo+KisLasLWYNXMWRo8ajcGDB7Njyd/fH6TLBE8Jxt
; JvlyJifwQePn6IrLwsk6wtWUmjx4w2ZDoK20VU4KHMV5rM5o2NjUXfvn2Ns+v1oK4CVlL0di6aLprw
; agWZbHXacaNGj0Ld+nWZ/sTcv5Ws9G4sKqy1s7VTenbwxJTJU7Bvzz52bDKFWSQ/8MVwKL3/Pxv/Ay
; cnJxkMoChy25L70thAi7dt+zbmIzACgYWeexj4ug92jO/CCi9PR4RDLLBq6YIc/LTnJ3h6ehZZKDK8
; dWR50TMomWZS0CQcO3wM1MTTWHD69Gk0a9ZMOgOQFPDt4svuFTaWuHqa8BQTJk6AlbWopAlZETc7Oz
; uWLEmil5xHUhW9CxcvMN+GsTxzpRiCCxR18e2C7du3i7q9lQ/yn+XjZsxN+Hj7SGQAGpS1JT4O/piJ
; Fblw/LfjaN2mtdkIT9jQtSF+3PajrPFn52Rj9ZrVbKeagvC6kBRikjTkCZRzBFNyb9yDOPj39Nc8as
; UNxt7eHrt27ip+qJgbqggyMjLw1YKv2JFihMURJPJpl/bv1x/Xb16XJb3i7sZhWMAwk0Xq9CEdD6RE
; /hH5B8gVLbkpBDf9pCdJ8PHxYaFphZTBNGnSBLdu34JYIEWF0pRtrUWlRsva+WRRLP52MbJyxIec1U
; B6Cu1AnjPUaIwq5Dn2le0xe85sloshpPKHDyhHs2OHjlDQXbNiB0KcQ4GfzLRMvTnnuiA5NRl93uqj
; bjolyKkjFTt5d8LpM6dltVAhnSd4ajDTHYxERNlMROKb0rsobEwWg1SpRrUcio3fbUTtWuLPM3L1rl
; m1RnxrEg7u3b9HSSTG2hU6kTmw4uQ7sOLuxcHvDT+jx+OlEL4kUg3gDz/8wIkoSKIDAfUIwtXoq+wq
; cgE2uNaupGjc+QvnIRZyC3Nx5NcjJt1VNBfSeGl8cq0WypecOXcmbCubqapHAPHVSGu44KsFWnl+Yq
; C4MoiiSl/NE6mccaahd2dvJCZpJ3cYSixlNnRuDkJXhJpcoXKo7oDQ0FCDNXKGgLJ8Dh47CPdW7mLC
; ryYjvCaSyTh12lRJc9QqDaOzkvLUqOmQ0JdT8ccn0z+RFO6lHgQBAQGkU5g0m5ZZAX37s0CJHCDP38
; OnDzE6cDQsrEzrsRSLZCWQiS5WMdRZG/j0CeegCZxAbkpBL6eIHacl6y4kMSANHsU/Qvt27WXtAKHY
; oH4D7Nq1iyWzygFqebNxK6c71a9tDmkgGG3sbTDnizmijjze4lBqJx6+LRyu9V0FvdzV1RWsdakGGK
; wxoL9yDEtX1Wr4qk2qHNra2CJoYhALN8sBmtq1mGvo8WYPYyiIRpuzk6MTIn6OYFFIIYygMDTJ27du
; Y0DfARDSQZyihoa8bCUdRyRWabBha8JMHgjSRDrmKCtZaqhWzdxpmWkIWRyCKg5VjCUNZDMDpenfj7
; 8vjgH0efRyc3KxbPEyONbQH6al60hCQkIkmSX0jkkfToKtpXb7WVMi1UIsWLCAKaRygJjoxJkTaP1q
; azHSQGkK4hOSn4YqgIT4P4T3B+AcPn+c/QOdvTvrfTmJoFMnTml9l4+5Sh4R1JPI29vbZATXhaQ89e
; zRE9dvXBeV/6gLqEnmh8EfwtLG/NU+mkiStIZjDdyKMeytFd0nMDU5FZ8Ef4LK9pV1D4DbAR28OuDR
; o0d6n6NLP7h7/y569eklqcpILlIm9Pfff89qHuUA5VCG7w1Hg8YNXriCSCl1ho4BSY0iqRgiYl8EXm
; n6Cu+umhg4kTknhJyxpJXv2bsHHh4eJguvCkHySYz8x0g8fvIYcoAWncq/+r/T/8V5EDnma9ehHXNi
; 6QNF+I5wSb5ymuT9u/cxYtgIdVRJE1X0u50/7YShglPSxoOnBTMHlDmVQH3o4e7Byt0454+sM4EaNi
; 5fvRw1XGq8EGlA7XzoaNMHCiJUUJC4Ui1N8V2QX4B1a9ahpkvpSpU6teuwVC8+OP37afh08mHFkOZe
; HENIF2N8/tnnrOBEDpAEPBd1Dl5dvMwqDUiRtre2x4EDB/TWKirUX6AegCdPSivWJH6IvhStokLJkr
; u4t39vlsigeRZR4uTiJYtZlc+LOO+FIs3Ft7MvLv15SXQ8oaSOk5yWjOmzpzNnjVnGz0kcUkb37d9X
; qrmnJig0v0RiOGRBCHPRSoHM9EzMnT2XlUmrn0kS5ptF30BZoGSmIWmmffv31bp6hj7Tv39/jBs7Do
; 0aNBLkczAnOjo4YvXq1UVFMjKAduL+Q/vh1tzNLEeCjZ0Nrly9ondM/wfgvgfSDPGtPQAAAABJRU5E
; rkJggg==
; thumbnail end
;
; 

; external perimeters extrusion width = 0.65mm
; perimeters extrusion width = 0.65mm
; infill extrusion width = 0.65mm
; solid infill extrusion width = 0.65mm
; top infill extrusion width = 0.60mm
; first layer extrusion width = 0.65mm

; external perimeters extrusion width = 0.65mm
; perimeters extrusion width = 0.65mm
; infill extrusion width = 0.65mm
; solid infill extrusion width = 0.65mm
; top infill extrusion width = 0.60mm
; first layer extrusion width = 0.65mm

M107
M190 S60 ; set bed temperature and wait for it to be reached
;TYPE:Custom
;Begin Start GCode

;set temps
G10 P0 S210
G10 P0 R170
G10 P1 S210
G10 P1 R170

G28 ;home all axis
G29 S1 ;enable mesh


T0


M116 ;Wait for all temps

G90
M98 P"prime.g"
;End Start GCode
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
;T0
T0
; Filament-specific start gcode
M703
M107
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.2

G10 ; retract
G1 Z.2 F720
;AFTER_LAYER_CHANGE
;0.2
M800 F"layer"
G1 X145.785 Y141.625 F10800
G11 ; unretract
M204 P800
;TYPE:Skirt/Brim
;WIDTH:0.65
G1 F1200
G1 X146.844 Y140.663 E.06931
G1 X148 Y140.393 E.05752
G1 X182 Y140.393 E1.64763
G1 X183.375 Y140.785 E.06931
G1 X184.337 Y141.844 E.06931
G1 X184.607 Y143 E.05752
G1 X184.607 Y177 E1.64763
G1 X184.215 Y178.375 E.06931
G1 X183.156 Y179.337 E.06931
G1 X182 Y179.607 E.05752
G1 X148 Y179.607 E1.64763
G1 X146.625 Y179.215 E.06931
G1 X145.663 Y178.156 E.06931
G1 X145.393 Y177 E.05752
G1 X145.393 Y143 E1.64763
G1 X145.761 Y141.711 E.06495
M204 P1000
; printing object A id:0 copy 0
G10 ; retract
G1 X149.132 Y160.932 F10800
G11 ; unretract
M204 P800
;TYPE:Perimeter
G1 F1200
G1 X162.614 Y160.932 E.65333
G1 X164.068 Y162.386 E.09965
G1 X164.068 Y175.868 E.65333
G1 X149.132 Y175.868 E.72379
G1 X149.132 Y161.022 E.71943
M204 P1000
G10 ; retract
G1 X165.932 Y144.132 F10800
G11 ; unretract
M204 P800
G1 F1200
G1 X180.868 Y144.132 E.72379
G1 X180.868 Y159.068 E.72379
G1 X167.386 Y159.068 E.65333
G1 X165.932 Y157.614 E.09965
G1 X165.932 Y144.222 E.64896
M204 P1000
G1 X165.325 Y144.675 F10800
M204 P800
;TYPE:External perimeter
G1 F1200
G1 X165.325 Y157.865 E.6392
G1 X167.135 Y159.675 E.12402
G1 X180.325 Y159.675 E.6392
G1 X180.325 Y175.325 E.75839
G1 X164.675 Y175.325 E.75839
G1 X164.675 Y162.135 E.6392
G1 X162.865 Y160.325 E.12402
G1 X149.675 Y160.325 E.6392
G1 X149.675 Y144.675 E.75839
G1 X165.235 Y144.675 E.75403
M204 P1000
G1 X165.905 Y144.52 F10800
G10 ; retract
G1 X181.475 Y143.525
G11 ; unretract
M204 P800
G1 F1200
G1 X181.475 Y176.475 E1.59675
G1 X148.525 Y176.475 E1.59675
G1 X148.525 Y143.525 E1.59675
G1 X181.385 Y143.525 E1.59239
M204 P1000
G1 X181.32 Y144.105 F10800
G10 ; retract
G1 X179.439 Y144.314
G11 ; unretract
M204 P800
;TYPE:Solid infill
;WIDTH:0.659419
G1 F1200
G1 X180.413 Y145.288 E.06778
G1 X180.413 Y146.16 E.04291
G1 X178.84 Y144.587 E.10945
G1 X177.968 Y144.587 E.04291
G1 X180.413 Y147.032 E.17013
G1 X180.413 Y147.904 E.04291
G1 X177.096 Y144.587 E.2308
G1 X176.224 Y144.587 E.04291
G1 X180.413 Y148.776 E.29148
G1 X180.413 Y149.647 E.04291
G1 X175.353 Y144.587 E.35216
G1 X174.481 Y144.587 E.04291
G1 X180.413 Y150.519 E.41284
G1 X180.413 Y151.391 E.04291
G1 X173.609 Y144.587 E.47352
G1 X172.737 Y144.587 E.04291
G1 X180.413 Y152.263 E.53419
G1 X180.413 Y153.135 E.04291
G1 X171.865 Y144.587 E.59487
G1 X170.993 Y144.587 E.04291
G1 X180.413 Y154.007 E.65555
G1 X180.413 Y154.879 E.04291
G1 X170.121 Y144.587 E.71623
G1 X169.25 Y144.587 E.04291
G1 X180.413 Y155.75 E.77691
G1 X180.413 Y156.622 E.04291
G1 X168.378 Y144.587 E.83758
G1 X167.506 Y144.587 E.04291
G1 X180.413 Y157.494 E.89826
G1 X180.413 Y158.366 E.04291
G1 X166.634 Y144.587 E.95894
G1 X166.387 Y144.587 E.01213
G1 X166.387 Y145.213 E.03077
G1 X179.787 Y158.613 E.93258
G1 X178.915 Y158.613 E.04291
G1 X166.387 Y146.085 E.8719
G1 X166.387 Y146.956 E.04291
G1 X178.044 Y158.613 E.81122
G1 X177.172 Y158.613 E.04291
G1 X166.387 Y147.828 E.75055
G1 X166.387 Y148.7 E.04291
G1 X176.3 Y158.613 E.68987
G1 X175.428 Y158.613 E.04291
G1 X166.387 Y149.572 E.62919
G1 X166.387 Y150.444 E.04291
G1 X174.556 Y158.613 E.56851
G1 X173.684 Y158.613 E.04291
G1 X166.387 Y151.316 E.50784
G1 X166.387 Y152.188 E.04291
G1 X172.812 Y158.613 E.44716
G1 X171.941 Y158.613 E.04291
G1 X166.387 Y153.059 E.38648
G1 X166.387 Y153.931 E.04291
G1 X171.069 Y158.613 E.3258
G1 X170.197 Y158.613 E.04291
G1 X166.387 Y154.803 E.26512
G1 X166.387 Y155.675 E.04291
G1 X169.325 Y158.613 E.20445
G1 X168.453 Y158.613 E.04291
G1 X166.387 Y156.547 E.14377
G1 X166.387 Y157.419 E.04291
G1 X167.854 Y158.886 E.1021
M204 P1000
G10 ; retract
G1 X162.145 Y161.114 F10800
G11 ; unretract
M204 P800
G1 F1200
G1 X163.613 Y162.581 E.10211
G1 X163.613 Y163.453 E.04291
G1 X161.547 Y161.387 E.14378
G1 X160.675 Y161.387 E.04291
G1 X163.613 Y164.325 E.20445
G1 X163.613 Y165.197 E.04291
G1 X159.803 Y161.387 E.26513
G1 X158.931 Y161.387 E.04291
G1 X163.613 Y166.069 E.32581
G1 X163.613 Y166.941 E.04291
G1 X158.059 Y161.387 E.38649
G1 X157.187 Y161.387 E.04291
G1 X163.613 Y167.813 E.44717
G1 X163.613 Y168.684 E.04291
G1 X156.316 Y161.387 E.50784
G1 X155.444 Y161.387 E.04291
G1 X163.613 Y169.556 E.56852
G1 X163.613 Y170.428 E.04291
G1 X154.572 Y161.387 E.6292
G1 X153.7 Y161.387 E.04291
G1 X163.613 Y171.3 E.68988
G1 X163.613 Y172.172 E.04291
G1 X152.828 Y161.387 E.75056
G1 X151.956 Y161.387 E.04291
G1 X163.613 Y173.044 E.81123
G1 X163.613 Y173.916 E.04291
G1 X151.084 Y161.387 E.87191
G1 X150.213 Y161.387 E.04291
G1 X163.613 Y174.787 E.93259
G1 X163.613 Y175.413 E.03077
G1 X163.366 Y175.413 E.01214
G1 X149.587 Y161.634 E.95893
G1 X149.587 Y162.506 E.04291
G1 X162.494 Y175.413 E.89825
G1 X161.622 Y175.413 E.04291
G1 X149.587 Y163.378 E.83757
G1 X149.587 Y164.25 E.04291
G1 X160.75 Y175.413 E.7769
G1 X159.879 Y175.413 E.04291
G1 X149.587 Y165.121 E.71622
G1 X149.587 Y165.993 E.04291
G1 X159.007 Y175.413 E.65554
G1 X158.135 Y175.413 E.04291
G1 X149.587 Y166.865 E.59486
G1 X149.587 Y167.737 E.04291
G1 X157.263 Y175.413 E.53419
G1 X156.391 Y175.413 E.04291
G1 X149.587 Y168.609 E.47351
G1 X149.587 Y169.481 E.04291
G1 X155.519 Y175.413 E.41283
G1 X154.647 Y175.413 E.04291
G1 X149.587 Y170.353 E.35215
G1 X149.587 Y171.225 E.04291
G1 X153.775 Y175.413 E.29147
G1 X152.904 Y175.413 E.04291
G1 X149.587 Y172.096 E.2308
G1 X149.587 Y172.968 E.04291
G1 X152.032 Y175.413 E.17012
G1 X151.16 Y175.413 E.04291
G1 X149.587 Y173.84 E.10944
G1 X149.587 Y174.712 E.04291
G1 X150.561 Y175.686 E.06778
M204 P1000
G10 ; retract
G1 X164.371 Y175.9 F10800
G11 ; unretract
M204 P800
;TYPE:Gap fill
;WIDTH:0.585842
G1 F1200
G1 X180.629 Y175.9 E.70456
M204 P1000
M204 P800
;WIDTH:0.632417
G1 X180.741 Y175.877 E.0054
M204 P1000
M204 P800
;WIDTH:0.632418
G1 X180.853 Y175.853 E.0054
G1 X180.9 Y175.629 E.01081
M204 P1000
M204 P800
;WIDTH:0.585842
G1 X180.9 Y159.371 E.70456
M204 P1000
G10 ; retract
G1 X165.629 Y144.1 F10800
G11 ; unretract
M204 P800
G1 F1200
G1 X149.371 Y144.1 E.70456
M204 P1000
M204 P800
;WIDTH:0.632417
G1 X149.147 Y144.147 E.01081
G1 X149.123 Y144.259 E.0054
M204 P1000
M204 P800
;WIDTH:0.632418
G1 X149.1 Y144.371 E.0054
M204 P1000
M204 P800
;WIDTH:0.585842
G1 X149.1 Y160.629 E.70456
M204 P1000
; stop printing object A id:0 copy 0
G10 ; retract
; Filament-specific end gcode
;T1
T1
; Filament-specific start gcode
M703
; printing object A id:0 copy 0
G10 ; retract
G1 X150.932 Y159.068 F10800
G11 ; unretract
M204 P800
;TYPE:Perimeter
;WIDTH:0.65
G1 F1200
G1 X150.932 Y145.932 E.63656
G1 X164.068 Y145.932 E.63656
G1 X164.068 Y158.386 E.60352
G1 X166.614 Y160.932 E.17448
G1 X179.068 Y160.932 E.60352
G1 X179.068 Y174.068 E.63656
G1 X165.932 Y174.068 E.63656
G1 X165.932 Y161.614 E.60352
G1 X163.386 Y159.068 E.17448
G1 X151.022 Y159.068 E.59916
M204 P1000
G1 X150.325 Y159.675 F10800
M204 P800
;TYPE:External perimeter
G1 F1200
G1 X150.325 Y145.325 E.6954
G1 X164.675 Y145.325 E.6954
G1 X164.675 Y158.135 E.62075
G1 X166.865 Y160.325 E.15011
G1 X179.675 Y160.325 E.62075
G1 X179.675 Y174.675 E.6954
G1 X165.325 Y174.675 E.6954
G1 X165.325 Y161.865 E.62075
G1 X163.135 Y159.675 E.15011
G1 X150.415 Y159.675 E.61639
M204 P1000
G1 X150.65 Y159.17 F10800
G10 ; retract
G1 X163.891 Y158.891
G11 ; unretract
M204 P800
;TYPE:Gap fill
;WIDTH:0.400111
G1 F1200
G1 X166.109 Y161.109 E.08946
M204 P1000
G10 ; retract
G1 X178.886 Y162.381 F10800
G11 ; unretract
M204 P800
;TYPE:Solid infill
;WIDTH:0.6687
G1 F1200
G1 X177.892 Y161.387 E.0702
G1 X177.007 Y161.387 E.04421
G1 X178.613 Y162.993 E.11342
G1 X178.613 Y163.878 E.04421
G1 X176.122 Y161.387 E.17593
G1 X175.237 Y161.387 E.04421
G1 X178.613 Y164.763 E.23845
G1 X178.613 Y165.648 E.04421
G1 X174.352 Y161.387 E.30097
G1 X173.467 Y161.387 E.04421
G1 X178.613 Y166.533 E.36349
G1 X178.613 Y167.418 E.04421
G1 X172.582 Y161.387 E.42601
G1 X171.697 Y161.387 E.04421
G1 X178.613 Y168.303 E.48853
G1 X178.613 Y169.188 E.04421
G1 X170.812 Y161.387 E.55104
G1 X169.927 Y161.387 E.04421
G1 X178.613 Y170.073 E.61356
G1 X178.613 Y170.958 E.04421
G1 X169.042 Y161.387 E.67608
G1 X168.157 Y161.387 E.04421
G1 X178.613 Y171.843 E.7386
G1 X178.613 Y172.728 E.04421
G1 X167.272 Y161.387 E.80112
G1 X166.475 Y161.387 E.03982
G1 X166.431 Y161.431 E.0031
G1 X178.613 Y173.613 E.86053
G1 X177.728 Y173.613 E.04421
G1 X166.387 Y162.272 E.80111
G1 X166.387 Y163.157 E.04421
G1 X176.843 Y173.613 E.73859
G1 X175.958 Y173.613 E.04421
G1 X166.387 Y164.042 E.67607
G1 X166.387 Y164.927 E.04421
G1 X175.073 Y173.613 E.61356
G1 X174.188 Y173.613 E.04421
G1 X166.387 Y165.812 E.55104
G1 X166.387 Y166.697 E.04421
G1 X173.303 Y173.613 E.48852
G1 X172.418 Y173.613 E.04421
G1 X166.387 Y167.582 E.426
G1 X166.387 Y168.467 E.04421
G1 X171.533 Y173.613 E.36348
G1 X170.648 Y173.613 E.04421
G1 X166.387 Y169.352 E.30096
G1 X166.387 Y170.237 E.04421
G1 X169.763 Y173.613 E.23844
G1 X168.878 Y173.613 E.04421
G1 X166.387 Y171.122 E.17593
G1 X166.387 Y172.007 E.04421
G1 X167.993 Y173.613 E.11341
G1 X167.108 Y173.613 E.04421
G1 X166.114 Y172.619 E.07019
M204 P1000
G10 ; retract
G1 X162.619 Y146.114 F10800
G11 ; unretract
M204 P800
G1 F1200
G1 X163.613 Y147.108 E.0702
G1 X163.613 Y147.993 E.04421
G1 X162.007 Y146.387 E.11342
G1 X161.122 Y146.387 E.04421
G1 X163.613 Y148.878 E.17593
G1 X163.613 Y149.763 E.04421
G1 X160.237 Y146.387 E.23845
G1 X159.352 Y146.387 E.04421
G1 X163.613 Y150.648 E.30097
G1 X163.613 Y151.533 E.04421
G1 X158.467 Y146.387 E.36349
G1 X157.582 Y146.387 E.04421
G1 X163.613 Y152.418 E.42601
G1 X163.613 Y153.303 E.04421
G1 X156.697 Y146.387 E.48853
G1 X155.812 Y146.387 E.04421
G1 X163.613 Y154.188 E.55104
G1 X163.613 Y155.073 E.04421
G1 X154.927 Y146.387 E.61356
G1 X154.042 Y146.387 E.04421
G1 X163.613 Y155.958 E.67608
G1 X163.613 Y156.843 E.04421
G1 X153.157 Y146.387 E.7386
G1 X152.272 Y146.387 E.04421
G1 X163.613 Y157.728 E.80112
G1 X163.613 Y158.525 E.03982
G1 X163.569 Y158.569 E.0031
G1 X151.387 Y146.387 E.86053
G1 X151.387 Y147.272 E.04421
G1 X162.728 Y158.613 E.80111
G1 X161.843 Y158.613 E.04421
G1 X151.387 Y148.157 E.73859
G1 X151.387 Y149.042 E.04421
G1 X160.958 Y158.613 E.67607
G1 X160.073 Y158.613 E.04421
G1 X151.387 Y149.927 E.61356
G1 X151.387 Y150.812 E.04421
G1 X159.188 Y158.613 E.55104
G1 X158.303 Y158.613 E.04421
G1 X151.387 Y151.697 E.48852
G1 X151.387 Y152.582 E.04421
G1 X157.418 Y158.613 E.426
G1 X156.533 Y158.613 E.04421
G1 X151.387 Y153.467 E.36348
G1 X151.387 Y154.352 E.04421
G1 X155.648 Y158.613 E.30096
G1 X154.763 Y158.613 E.04421
G1 X151.387 Y155.237 E.23844
G1 X151.387 Y156.122 E.04421
G1 X153.878 Y158.613 E.17593
G1 X152.993 Y158.613 E.04421
G1 X151.387 Y157.007 E.11341
G1 X151.387 Y157.892 E.04421
G1 X152.381 Y158.886 E.07019
M204 P1000
; stop printing object A id:0 copy 0
G10 ; retract
M107
;TYPE:Custom
; Filament-specific end gcode
; Filament-specific end gcode
M106 S0 ; turn off cooling fan
G10 P0 S0 R0
G10 P1 S0 R0
M140 S0; turn off bed
;Drop the bed
G91
G1 Z10 F1000
G90
M0
; filament used [mm] = 62.16, 37.20
; filament used [cm3] = 0.15, 0.09
; filament used [g] = 0.19, 0.11
; filament cost = 0.00, 0.00
; total filament used [g] = 0.30
; total filament cost = 0.01
; estimated printing time (normal mode) = 1m 51s

; prusaslicer_config = begin
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = G:\\Rancor\\Rancor\\PrusaSlicer\\BedModel.stl
; bed_custom_texture = G:\\Rancor\\Rancor\\PrusaSlicer\\BedTexture.png
; bed_shape = 0x0,330x0,330x320,0x320
; bed_temperature = 60,60
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 4
; bottom_solid_min_thickness = 0.6
; bridge_acceleration = 1000
; bridge_angle = 0
; bridge_fan_speed = 100,100
; bridge_flow_ratio = 1
; bridge_speed = 25
; brim_separation = 0.1
; brim_type = outer_only
; brim_width = 0
; clip_multipart_objects = 1
; color_change_gcode = M600
; complete_objects = 0
; cooling = 1,1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 1000
; default_filament_profile = ""
; default_print_profile = 
; deretract_speed = 0,0
; disable_fan_first_layers = 1,1
; dont_support_bridges = 0
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0.2
; end_filament_gcode = "; Filament-specific end gcode";"; Filament-specific end gcode"
; end_gcode = M106 S0 ; turn off cooling fan\nG10 P0 S0 R0\nG10 P1 S0 R0\nM140 S0; turn off bed\n;Drop the bed\nG91\nG1 Z10 F1000\nG90\nM0
; ensure_vertical_shell_thickness = 1
; external_perimeter_extrusion_width = 0.65
; external_perimeter_speed = 35
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 45
; extruder_colour = #FF8000;#0000FF
; extruder_offset = 0x0,0x0
; extrusion_axis = E
; extrusion_multiplier = 0.96,0.96
; extrusion_width = 0.65
; fan_always_on = 1,1
; fan_below_layer_time = 100,100
; filament_colour = #FF8000;#FF8000
; filament_cooling_final_speed = 3.4,3.4
; filament_cooling_initial_speed = 2.2,2.2
; filament_cooling_moves = 4,4
; filament_cost = 24.99,24.99
; filament_density = 1.24,1.24
; filament_diameter = 1.75,1.75
; filament_load_time = 0,0
; filament_loading_speed = 28,28
; filament_loading_speed_start = 3,3
; filament_max_volumetric_speed = 15,15
; filament_minimal_purge_on_wipe_tower = 15,15
; filament_notes = "Affordable filament for everyday printing in premium quality manufactured in-house by Josef Prusa";"Affordable filament for everyday printing in premium quality manufactured in-house by Josef Prusa"
; filament_ramming_parameters = "120 100| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6";"120 100| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = PLA;PLA
; filament_soluble = 0,0
; filament_spool_weight = 0,0
; filament_toolchange_delay = 0,0
; filament_type = PLA;PLA
; filament_unload_time = 0,0
; filament_unloading_speed = 90,90
; filament_unloading_speed_start = 100,100
; filament_vendor = Prusa Polymers
; fill_angle = 45
; fill_density = 15%
; fill_pattern = gyroid
; first_layer_acceleration = 800
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 60,60
; first_layer_extrusion_width = 0.65
; first_layer_height = 0.2
; first_layer_speed = 20
; first_layer_speed_over_raft = 30
; first_layer_temperature = 210,210
; full_fan_speed_layer = 0,0
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 40
; gcode_comments = 0
; gcode_flavor = reprapfirmware
; gcode_label_objects = 1
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = duet
; infill_acceleration = 1000
; infill_anchor = 2.5
; infill_anchor_max = 15
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.65
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 70
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]\nM800 F"layer"
; layer_height = 0.3
; machine_limits_usage = time_estimate_only
; machine_max_acceleration_e = 1500,1500
; machine_max_acceleration_extruding = 1500,1500
; machine_max_acceleration_retracting = 1500,1500
; machine_max_acceleration_travel = 500,1250
; machine_max_acceleration_x = 500,500
; machine_max_acceleration_y = 500,500
; machine_max_acceleration_z = 100,100
; machine_max_feedrate_e = 60,60
; machine_max_feedrate_x = 180,180
; machine_max_feedrate_y = 180,180
; machine_max_feedrate_z = 15,15
; machine_max_jerk_e = 25,25
; machine_max_jerk_x = 6.7,6.7
; machine_max_jerk_y = 6.7,6.7
; machine_max_jerk_z = 1.7,1.7
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100,100
; max_layer_height = 0,0
; max_print_height = 601
; max_print_speed = 100
; max_volumetric_speed = 0
; min_fan_speed = 100,100
; min_layer_height = 0.07,0.07
; min_print_speed = 15,15
; min_skirt_length = 4
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.6,0.6
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_T0-{filament_preset[0]}_T1-{filament_preset[1]}.gcode
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 800
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.65
; perimeter_speed = 45
; perimeters = 2
; physical_printer_settings_id = Printer 1
; post_process = 
; print_settings_id = N0.6 0.30mm QUALITY
; printer_model = 
; printer_notes = 
; printer_settings_id = Rancor
; printer_technology = FFF
; printer_variant = 
; printer_vendor = 
; raft_contact_distance = 0.25
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 0
; resolution = 0
; retract_before_travel = 2,2
; retract_before_wipe = 70%,70%
; retract_layer_change = 1,1
; retract_length = 0.5,0.5
; retract_length_toolchange = 0,0
; retract_lift = 0,0
; retract_lift_above = 0,0
; retract_lift_below = 600,600
; retract_restart_extra = 0,0
; retract_restart_extra_toolchange = 0,0
; retract_speed = 40,40
; seam_position = nearest
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 0
; skirt_distance = 2
; skirt_height = 3
; skirts = 1
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 20,20
; small_perimeter_speed = 25
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.65
; solid_infill_speed = 70
; spiral_vase = 0
; standby_temperature_delta = 170
; start_filament_gcode = "; Filament-specific start gcode\nM703";"; Filament-specific start gcode\nM703"
; start_gcode = ;Begin Start GCode\n\n;set temps\nG10 P0 S{temperature[0]}\nG10 P0 R{if temperature[0] == 0}0{else}{temperature[0] - 40}{endif}\nG10 P1 S{temperature[1]}\nG10 P1 R{if temperature[1] == 0}0{else}{temperature[1] - 40}{endif}\n\nG28 ;home all axis\nG29 S1 ;enable mesh\n\n{ if current_extruder == 0 }\nT0\n{ elsif current_extruder == 1 } \nT1\n{ endif }\n\nM116 ;Wait for all temps\n\nG90\nM98 P"prime.g"\n;End Start GCode
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = 0
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.25
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.55
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 2
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0.3
; support_material_interface_speed = 80%
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 50
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 50
; support_material_with_sheath = 0
; support_material_xy_spacing = 80%
; temperature = 210,210
; template_custom_gcode = 
; thick_bridges = 0
; thin_walls = 0
; threads = 32
; thumbnails = 128x128
; toolchange_gcode = ;T[next_extruder]
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0.6
; top_solid_infill_speed = 45
; top_solid_layers = 4
; top_solid_min_thickness = 0.9
; travel_speed = 180
; travel_speed_z = 12
; use_firmware_retraction = 1
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wipe = 0,0
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 170
; wipe_tower_y = 125
; wiping_volumes_extruders = 70,70,70,70
; wiping_volumes_matrix = 0,140,140,0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
