; generated by PrusaSlicer 2.4.2+win64 on 2022-05-19 at 02:37:02 UTC


;
; thumbnail begin 128x128 10904
; iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAfuElEQVR4Ae1dCXxM1/ef7HsiklRWIW
; KJEEEECVJKiZbqr6jad+FftfZXbe2qllbpZudH/YofWkoRFLWrNfY9lkSQRJDInvnOf86NGZNZ33vz
; JpmQ43NsSd7cd8+5537Pdq9EIpFI5QyeLORndLKdjR3GjR0HqVQKQyTV8026viaTE33p4oWLaN+uPa
; ysrCDm+Pmwm5sbZkyfgWfPnsEQFRYW4vHjx9J538yDR2UPYXNrZ4fefXrjVuItrZ8hMeJlRFUCR0dH
; bNm8hZMScBW8Qvj5+flYuXwl/Hz8IOaY+XLD8IbYv2+/3nek8aq+F31vdnY2jhw+gujm0bCwsOD9uf
; QzdUPrYvMfm0FzIZYCiM6hoaG4cvUKxBD+i4mUJd1LQr/e/WBvZ19m7+Vg74C4YXF4+OAhuApe/esF
; BQVIuZ+Cz8Z/BidHJy6fK1P/PxcXF4z/dDxS01J5K4BU7U+TsKWFJbp26YrCvEL5LECQ4BVE5nPH9h
; 0IDQmFKcdsiAMDA7Fu7TomQKHCV/kaTv5zkj1T6Hho+2vRogWOHD0iK5IWcVYAdeGbTBFcnVzx0w8/
; yVUeOpXAkMnPy8vDtBnT4OrqClONk8tEv/fee7h+/bpOk68qeEOUl5uHNb+sga+vryjjq1KlCubNn8
; dJAaQG/i06u7u7M00HfzjAiCb822++ZQDI1GPVxh4eHvhu3nds79ZFXFc9UUpKCgb0HwBra2tjx1Zi
; W7C1tZVKOAqd79eNY0sJIptFltirDK169f/Lzs1Gn359YNJxauGo5lE4duyY3lXPVfi0je3ZvQchIS
; GCwJ8+4avIUOt/qv+9dNlCjgdsLPHxyI9B5lwf0NNlRgulhbiXdA/1G9ZnCmXqMTs5OTFXNi0tDVwU
; 1dCqz3yWiUkTJzHvSOSxqslVPtmOro5wdnXW8Q1lpwjyl5du/XMrcgtyQYBF12TqoqKiIhw9ehQ+AT
; 6QWJlunLVq1cIfW/5gn8eFDAG9hDMJaBHdApaWlsaOTWZQjhFRETh49KD09LnTaNO2jVkIXvXzg4KC
; cP3Wdd7CV6Vly5fB1s5W9DHa2Njgox4f4c6dOzo/m8+qz8nJweKFi+Hp6Wmy+dTgB2kP5FhLisKiQq
; RmpGLKjClwdnYuLSEbZFsrW3R6pxObHCFEc56VlYVPx34qxopSsncVbyxZvAS5ublcx6FX+Hfv3EX3
; bt31RSllogpeweqTlZOfg137diG0fpn4zxqDtbKwgoONA+Z/M19WkFcAIUQ++MOUh4iOjIaVpXFhYA
; Jjb7V5CwkJCZyjlvqEX5BfgK1btjJLp+dzuQpf3eQbtuJaB1VUgHsP7mFw3GAxXA/Bwle8lIXEAl6V
; vXD44GE5uoMw91D+M0cOHYGPn3A8QHGFyZMm48mTJzo/ho/Jf5z+GGNGjzGFu8p9+9Y1OAJdmTmZWL
; N+DfwCTBpDl3LUaLSIaoH0tHQIJZLHho0bYO/APywcVj+MuWR84vi6vo/A4vFjxxERESG2e8cft+kb
; MGGD/MJ8XLx2Ee90fsfYgfIRvkyizezJV+7w/xuukdDgSqTU2fnZmPDlBM4ZQcohDB40GPfv34exgi
; fKfp7NglSUFRRR8MKEr6oA+oh86vTH6Zg4caJYWwLnVV+C5f68nYMd1m9Yrze2ro/yi/KRmp6KLl26
; GASF/n7+LPwqRhyf6Pq163j3nXdFBaNGCZ+LAtA7UTDm+D/HEd0iuuyEr8JB1YNw8epF5BXmQQiRCb
; 51+xZqBdWCjaWNxvMJKJKgrl65KgrQo/lbv249/P399b23UKBnnDz0vBMLRWZkZOCHn3+Ah6cHjP4w
; /Saf17O6de+GzMxMCCXKy9epWYdlIFWfW9m9MubMmcNcR13EZ9U/fPgQQ4cMFSuOL9QV5K8AtM9eu3
; 4NH3T7QAygIm5QSR69tLK1wpxv5jAl5UNZmVmYOX0m3vB6Q+O9IptE4tChQ6LF8UnJ6terz2X++MwP
; N/dOqAKQeXz+/Dk2/rYR1apXE+NDBA2WQJqvny+mfTUNrWJaaX6PHA+QVYrfFc85BHvp4iV07NBR6X
; YFezoypnj7qJGjkJqayuk5hlY9Kdm0qdNYfkCE+ePv2wtVAAI7yfeT8fEnH1Oq0JSC12vKKMT6Vtu3
; cPbcWTYu8ru//PJLVtGi/r3NIpvh4f2Hcs3VLRB6LyoJC6waqARgXcO8cWB4U9n2QRGyDTM+QV6m8b
; 49fen8ufNo/WZrseP4eufTwc4BLvYuwoJcioFTSHP/wf1oFNHI2IELFj5NWqVKlTBl+hQ8efpEY3Lj
; d8azsjHVnyHzOqDfAJ0h2eSkZAzoO0AZ3na2s8LMDrVkJHxVTvhuuCwn7b5OwRsi+vwVy1awQgsR5o
; 8z16lVB9u3bcf+vfsR0SiCLVxeWzbtVeTizZ47WwzfVJ/w9a56AklhDeTBlr179Jp08sf79+/PrITi
; Z8mkr//feo0I4Y4/d6BB/QZKnz/c1xXbB0ZoCF/BR8a+JXtwdJuG8A2Z/KSkJPTq2atU4/h2tnbo3b
; M37ty+o8RBqY9SMWLYCCZHzhbo/MXziO0YK1TYnAarbwJIWx0cHDBk2BCkPEwBFyKAunrVavj5+imf
; 4ePvg0sXLkFaJMWTjCf4/LPPS5RSj4wO1Cl4db66erqsIDuTk/DPnDmDmjVrijF/nPd6nyo+WLZkGa
; s4Uh8e/Xv92vUIDgousUh0MgEtEwpfr+tCKyawWiD+u/a/yM3jllVTpcuXLiM2NpYpgJWNFdrHtseB
; AwcQExOjfHkCef/rHc5Z+Ao+NbO3LO3s3wbHQD7+/Pnz4ebqpk+gYswlW9Vt27TFuYRzBgNhN2/cRJ
; fOXeDo4GjIGphE8AYngAT0bmd5sOXaVRhD5K9/Petrhh0sLC3g7OLM3ET6DAXQE8q0JSTtXQeFNdBF
; ZHVOnzyNyMaRfF1mzkCPFGzalGkMEHP1eqiQdMG8BSx1rScOIbrw9a560kZPL0/MnTcXmVnCAzmqlH
; grEdFRL6OUBPS+fy9EZozwDQFEbfTs6TOMHzMetjacPCjOFiI8LBx79+xlW5+Qxpl/jv+DllEtdQFE
; wQrAm0kLI5tG4vDRw4JeRJ3oGZs2bEKd2nWUZq5DbS+IJXht1sAQESDbuX0nalSvYbTgqaFk6KChSE
; 5O5h3wUieWeh41Bk52TurRT1FWvd4XI61zcnbCqLGjkJaeBjEoLTWNBW/I9Cs+5/M2QTJTCF/dGqhv
; CdrcxftJ99GjWw9YW1nrmiO9QC8wIBC/rvlVURQLY6iwoBCJ1xMR+3asttyH0cLXq9EE9GrWqonft/
; yO/AJhaVx1OnTwEKKaRSn3NaFAzxhrkJbwt8E4AZnsZYuX8WrspHeiErgrV64IzngqSa43+Tn52LB2
; A6r6VVVXRs4KIHjV057TvUd3JN5OhBhEIeo5s+YwUKPYy/pH+OFAKQlenW9u+E5mCCDKSXb5wmXEtI
; ihbUpvGJcSUfPmzmNJLmNXfVFhEdIfpWPYoGFwsnfSB04Fr3q9QM/Hxwc/L/5Zb3cMH6LUbOd3O5eI
; 46/oVl9WVsJXMLmLWfeuGRx/dla2dOrEqVJHe0eti6V5ZHMcPXJUcLGLKlHt5KH9h1A/pD5srQ0CUv
; FWPTG5dzFvxuDUmVMQgwj8/LLqFwRVC9KI45sLqwNE9a1BEUyiVXlg3wHUrV1XuSKp05fA2aOHjzi7
; d7qI3NHnz55Lp0+eDjdnN41Ut1bW0mosOI5PRZNfTPwCGU8yIAZRT9yQQUOUSSBdcXxzYQKIuekpBv
; MHaY/SMLDfQIaN6EwEUYBefiGuXLyC1i1bw96WR83jhvUbEFwjmIvJ1/kQAi716tdD/O54o90VBe2O
; 341G4Y2U8XUy+fri+OZkDbhEEGmeKG5g7Hyxiq2cPKxcuhLent78M4L0AKpV6/qvrrpSwHqBnr29PQ
; YMGsDSyGIQTcrkiZPh6fGyO4ZPHN9cmCNANIpoS0lJSkGvD3vB0c4RVD7PUfAyVQVgtocQ9vfzv2eV
; MlyETyszICAAq35Zxbk7xhAlnE1Au7faKRXRXICeUOYKEIVQfm4+du/Yjdo1asPG2oar4DVZ9aEEQi
; hsKHdZZPoSCAT0OnTsgIuXL0IMIuRLPXEB/gFKcGRuQE8oc80ncCUCes8ynuGzcZ/B2cGZG9DjqgBE
; hGCpxXnCvyfA1cVVA+hVrlwZX8/+Gs8yDZ9yxYUon92zR09lG7TYcXxzYa75BH1EbWQJpxLQvElzdr
; KaUYJXVwB114WiUNu2bkO9uvWKTb61FRo1boS/D/5ttLuioC2/b2Fn+Jg6jm9O1kBRcMKHqKElLzsP
; P87/EZ6VPI3ub9RQAF0hTYIH1LUaNzQOcf8Xx7lo0hClp6dj3Jhx7CgYxUBKI45vLqxacGKIyEu4dv
; MaOsR24OfeCd0CtFJRsfkRg44dOYaW0S3LLI5vLsy14IRo+bLlLEwsuvA5K4AIRP39333zHXy8fcwi
; jm8OzLngRG6JLyRcQHSzaONBX1kowI1rN/D+e++zmIFi1Zdn905sJoDIxV2kfoMvJ3wp5qGXUpMqAI
; HFtf9dyyKN5hrHNxfmWnBCwZ+9u/eids3afAI/2oVvSgtAyY3hw4YrD2sk9+51AnpCWVvBidb5ffCI
; HYGrI8dftlvAvr/2oUnjJiXi+K8j0BPKXPMJBMzX/GcNqrxRhd+qN5UCUCHDjKkz4OXlpfyA8hjHNx
; fWlk/QkmrGtSvX0LZ1W2HtaKqncRpDdBZ/bPvYVyaOby7MNZ+Qm5OLWTNmwdmJ+wlvb3jK8z5NmjXB
; 4SOHIZQoYrh86XLWePmqxfHNhV8ARIPYgB2MeegowuqF6e1PIEsR1TQKxw4dk//bSoJKnpUw91v+df
; rsLP4+/ZRaZ+4FG+WdiwtODOcTqAR8xLARUm1ZQsrvjBk5Bo8fPWZFoxL2BTpL11rCDoLiemEDdaSS
; pnFtvKxgcdhQPkGR3qdS8N83/o6q/lWVq55ORNmyaUuJo/YkSu2gdiq5NfAP9Ge9erqKE+nImAmfTm
; BZwQqgV3bMNZ9wO/E2unTqgr49+uLerXsa5yhINPYIuRLYONhg8NDBSHlQsluXzvB/M+ZNoxsvK1gc
; NpRPULUGVDOo3j5PHoVEK1CwKN4S6jWoh7/2/sXi+D8s+IG1Y1cAPfNioQUnCndSotdVkFsDF3cXhI
; eHsx5+BdB7FQs2yjvzKThRjSVIDPqLFi///qoXbJR35ppPUCXDCvCCK+L45Ye5NrAyBTB0oEEF0Cuf
; rMgnGGpgldCVKjNnzcTb7d5W5usV/LoXbLwKrKs/QeEhSAjh0+VK/Qf2VyYTKuL4rxbryydI4vfEs3
; tlFau+wr17NVkXQJQojjOtiOO/HqzqLtJpLcwLqObuUBHHf42YrMG2lQsQFR1VrABVXOwwuV2wbO+w
; yHL1IhXMn/cMbSL7Kra2LNi7sqI0v3jvt7e2xL/qe8s29mlYrl6ogrnzlv6NZF0bBcpo21dx/0v6/b
; W9nPBDl7oV1uAV4+86hcjCq3pqOwJAM/jjZm+NgZH+sj8HNi5XL1nBmkyrfmjTQJmXq7OumkHtEUDa
; EtoEe2BZt3oV1qCc8tKu9WQR/m4azaR0BgSd6PIi8Kch/BKHGQbKPYR/vxkkix/cpFy9/OvMBPTGxg
; TJqrg6lJAtgb4O7Tsg4VwCnuc9x9nzZ0sogM7bqMgadAzxkq3rVZETMHfeIAfxsfX8Zeq3kbpXcsf0
; 6dOVB3hRyzmxRKJ55p/u40vl1uBruQtRsSWYJ899N0TWQA70VO8JILQf0TiCXcSh7eRRCRfBq1sDAo
; gV7qL5MAG9gU2ryqq4u5QAenTqSlxcHJKSk6AzG8hH+KocXc29AiCaARPQaxpUReMCarqN/NdffzV4
; EYeEr+BVmSKIFQCxbJiA3siWQbLAN9xL3FVEdxXQtbiXrlzidPikMQogUwWIZA3K0wSWZ/7Ph2GyNn
; V8ZIo6TVUeMmQInmVxP8BLouWuG0EsB4iyinyC6Zni+HX9PHReAdOgYQM8SnukUQKuUwGS7yRjycIl
; aBrVlF3HaswdtxX5BNMxAb3eEVVllVyc9fb90df69e+H7Mzs4g4gQwqg6BShkyfOJpzF1KlT0ahRI2
; XMWMuZNAYBY5iPi6winyAe/ySfyzA/V9jYcjsRlHoC169fz8kKaJwPkF+Yz46NPXrsKEaPGo3qVavL
; HGwduPaey1QBYkU+wTimVT+kaYDMxZ6/VaZTVy9dvsRfAZg1KCpiCJIqSjMzM2Xx8fHo168fu8xZaX
; 4s9A5AWgEQjWNy7xr7C8dnJCcq9KW7lfRZAk4nhJAyFBYV4unTp1i7fi06dekEBxeH4q5iDtsDRRAJ
; IFa4i4aZ3LtJbYNlHo5GX97NrPaMaTNQmFuo83JtQUfEkDLcuHUDc+bPQet2rRVBCKkhgEjWoAIg6m
; aK479dy1NmrOBVmS7b2Lp1K4yyAOqkaDYolBYiJzdHeurkKenESRPRsHHDYi9Cz/ZA1qACIGoyFWxQ
; MY6YwmdsJUFog1DcSrwlngKokurlynn5eTh64iiGfzwcVQOr6rxNW5FPqACIKkDPzlp84atsBXED4+
; g+IZYBFFUBtBFZhqznWdi8eTM+6v4Ru9xRmxfxuucTjAV6fNjGygYrVqxAdn52CSWQ8L3tQ/qCeHw/
; Hjx4gEVLFyH2nVh2t71yYBavZz6BgN6IqEBRgB4f9vf3x+kzp0vIRzJ08FBs276N+f6K1atP+BBI9K
; N0n93dW3ex4LsFCAsPg6WtJSzl28HrVHBCcfyoQHeZpBQFr2AK7r3Z+k08fPTwpQLs3bcXgYGBiG4e
; jWXLlyEtIw15hSWvMeO76vVrQvEf1JN48sRJTJkyBaF1QxleIIA4vX2tV3ZLmN6+poyacMpC+MSK21
; wnT5rMLvSkeA/DADt37mS3dNE+XSO4BiZMnICbt28qrisXT/haiF2f9uwZ/t73N4bFDUPtatXRp3HA
; K+UuEtDrEe4rs7WyhEQiKXN2dnYGBfdoETIFIFCwadMmuDgXX9BoKR+oo6ujtFPnTtJf1/7KjoBlwp
; KKcyegOpF+KaKPFGz6bfNv+GpUfyz7MLzcWwOK49f3djELwatyWFgY7ty989ILyC3MxY8Lf4SLExts
; 8dXmFsUuRI2gGhg5ciSOnzqO7JxsdnOVKUkq/0WW4erJ41gzumu5dBdLw70ziq0l6Nm758s7g9gNlH
; I/vn/f/sxl0PZD1FJE17Yv/GkhqzMz4c6g0ATkZD7FrkVfyTYOblFuhE/uXVkBPT7M7iBSzvULad6/
; fx9NmzXV/8Py6JKbhxt69e2FnTt2sosj6Sw6U1JiwnGsHNLWrN1Fcu9myEFs1UrOkEgk5YNVha+gEy
; dPIKBqgP4ffBHutbO1Q2i9UEyePBkXzl94eaWcCYwDswaLZ5olQCxuvKwqE/E6l9JhXQh/1apVsHfk
; 8TLyzKCbuxvatW/HrntPe5gGaYFUtDsGVUluDWS/9I8yG4Cop/GyfFgAbZSVm4VPxnwCSxserssLq0
; D+JtUOjBo5Cvv27iPgKLo9IGuwdebHZQoQadXHRVWTeVd2E3ZZgzkrACHx5AfJiG4VzfZ8IQ+nS41s
; rW2l1Jny7bff4t69e8wikNupD0AaOtpMlf7ZvAoEEEvbGhDQa1HTW+NktVdGARR05foVw3jAACtWB5
; 0w/sEHH2Dbjm3IeJYBsSjlxiWsHf2vUgGIBPTGvRksq1alss5sp5mx1CgFoJX6x5Y/lEEiMT60Vu1a
; OHHiBMQkBUA0ZT5B0XhJLVeGDthUsoVEa31EiWYO62LsQBbTyqKUlcrQxJIC0E0iU6ZOKdF0KISpWK
; Rnr55sKzAV3Tp7DGuHvy36lqCt8VIbk2AVymFrZwuXSi4s8dXxnY4YMmwIvpz4JeZ/Px8//fwTFi5a
; iCVLlmDx0sX4+quvMXXiVHYVXGyHWBapo7gLXdpNzyM2icXhMqmkBI9SH6HTu50E9w14+3izZBMFm0
; xNCoAohrtIQK9fhJ+skpOd9lWvAnzdXNxYSf3w4cOZF3X2wlk8lY+FunJZuJuwzwv/WNU7UubnpcXl
; +fS91NNHYXHq5V+zZg2LxEZGRsKjsgfXwlzxFEBBt2/fRs2aNXl/SNt2bXHu/DmUNhkLEAno1fdz0V
; b8Wmyu5auTAmKdOnVi17PcTbxbfDHDC1KvvhFCqopC4fGUlBTs2LED48aNQ1DNINjZ2xl3nTx4EGnv
; 7j274enpyenhdGvo1GlT8fTZUxhLOdk5ePLkCe88RMrNyzK+AJGAHrl3AV5uWlcZTXpMdAyWLlrKil
; 2UHo2JI+PqRBbi0NFDGDd2HIKDgrnjEqEKwF6wAJgxYwbsHOz0PjisQRj27t0LMejqtat4//33ERwc
; jLGjx+LM6TNsNRgihTupjCByyCewxsva2hsvSaG7vN8F+w/sL75TqZQFro3YtlIoRdaTLGzctJFhDV
; 7bNPiS/KWzcrLQpVsXZgI1VoedHYYMHcJWhrFEk7xu/ToEVgtU7rPEDvYOaNasmXTJoiVITk7Wqgza
; YgkEEFcMbqtzS9BovHyB4O0d7NG1e1fQyeqmiGyKQi+UkbADLZBBAwexcRvECVTjL4QSbycypKr6sI
; CAAFD9gLajSPiSXIGkccPjNA4+KLEPU8TRx5d1Le3YvuPlTWdS6FydZA3++PazEgCRgN5HjUs2XjI0
; b22BZtHNEL8rHkLnqawoPy8fiYmJGDhoIDw8PXQrwI07NziZU21EYV5vb28W6OnUuROuX79e4ut8In
; oKohUm3zqkDcIbcN7T6POJw8PDZVRidvvmbYOdsafjN4HyCVSwoR7HJ+HT/cc///yzshimPBLzPPKL
; cOrkKXT/sDtzS9XmTioZMHBAcesQXx14gQfWrVmHBQsWKItKjSE5qJFOnzEdbpWMK5Wm/btjbEds3L
; gRDx490IrGHzx8gBH9e8LHo2Qcn7J5HTp0wPmL501f71BKRIsqpyAHu/bsQmSzSMXCKg7W0R2By5ct
; hyCSQrQ98fz589J2b7fTllSRClUECyv5FhHgy5JadD8y1cAxC7N/L5o0aaIRx/fz88OixYuQnZsNUx
; BtI2WlVIpFQJ7D7NmzpR4eL7YF8iGDAoJw+vRpUfxWvkRCWb5iOXx8fYQI2XDVjcXLbaJVy1YMoFKj
; impUjf5OnbSnzpwyCcijLTY1PRXXbl7D2XNnmTIePnyYgcqrV68y357Am2L+maKYwMVQpP7pj9OnTi
; O6ZTS9f/EhEDFtYpD6JNXk9X6qRFfV9Onbx+gQMy+roIYrSBkozP044zHEIlIiCnxRmLdf334IrROK
; qr5V4WjnyA5voDGQp6HALhTdC64WjFYtWmH8+PHY+PtG3LpzS4nNFAWzxpC2uo/MZ5nFCkBMQpg6eS
; qk+VKdrcRiEb3Yn9v/RJ2QOtqAnmCTz1cRGjVshF27dxnttShO3aRAFYWAm7doDld31xLbmZaTVkqO
; R2JRYmzuru5o0rAJJk2cxBJnZCnFWpyqyiBRnXRHB0fm8piS0tPT8dmEz+DkbIJOWI5M7zl06FDcTb
; oLY4nmks7dXb5yOUJCQkQrDCGFUCgFLc5mTZph7qy5uHfnnqjblKTEB8tj3vXC6rF6cVOAlX9O/IMW
; LVsICVnq2+t5WYzq1arjlzW/GDxAkQvRXn3g4AG0a9euVGoDaN7opO/xY8fj8pXLemXEtZlHov4hVj
; ZW6NmnpyhunYLoWT/8+AO83vASIkBRyqtpFXXu3BkXLl0QBexSfmPW7Fmc8yJiM8UpRowYgTt37hS7
; 5AJfSaLt4QRQli1dJoqpuXHzBrp27SrENIq26snlmTt3LkvNikHnLpxjGcDSBK+6uIp3Fcz6ehYyUj
; NQkF/Au4tPouvB3lW8WTDEGCJXo3bN2kIEKMqqJ6WLah6Fg4cPoqDQ+PA0AbHVa1ajevXqwjJvJmL5
; WKSUfNvz1x42Rj6RXZ0KQKHRlq1aFqdgBeAB8mOfZD1Bt27dWK8hR8GLJnxqgBwzZgxSHqZADCLAOH
; jIYHMsAlXOqYOjA0aPHo2MjAzk5eUZf1YwNX1MmzQNedncq3jUbRBtAcF1grUWVZhC8MRkdTb9b5No
; 1UfUBkfdUpZm0t2rj8kyNY9qziqJKCFkKJ4kMSQISr1S+5cxtHPXTqm7u7sQ4fOOCdAEUMSPDkkUy5
; OhOMHmHZtRo04NLopsFkzYYPNvm1lzjj6ScHlYSN0QVhMoaPKKCpifPHP2zFIto/b19mVBmfyCfIhB
; pEy37t5Cj749WJq4tN7DmEVBx/FQRlNfoIuTAlBjSK8+vTRKu7geHkHeBGEJKlIw5jBqvkxbGIVik1
; OSIRZlZmdi0YpF8PLxEqco0wSCV2XCcnO/matTCSScH+Rgi5WrVgoujCA9SUpKQlj9MJncEpRa6zRt
; CaEhoSzkK7TuQZ0ojnDq/CnEtIsR3DVVmkxFNbPnztbawS3h8yBPL0+NU6bUhGzQGhw+dJgdR1Pak+
; Dk6IQvvvhClAJV9q7yX+lP0jFxxkQ4uTqZyhqIkxeRj436ExYuXKixgCVhoWG8Hta6TWupUDxA0SpK
; Ni1fvrxUtwIFs5SwPON25uwZ0VLfdLp6/L54hISFiA0QxU2KyZXAz9ePpaEJlynWqiTpbhIG9h3Iy7
; /9/PPP6YhYThOkXhZGeIBA4ccjPy6z3jovz+JyLzHcRAUMSnogn8e4gbCyE+WdTJYRjYiIwP1H95ni
; MgWg3+j8vtUrViPAL4DTYOgcgM1bNlM5sqC6BZqwlOQUxLSKgbWldYlUaGkxhXG7/qsrEu8kiuYuUi
; XR6nWr4RvoK9QamDwVTlbwk08+YYEiov8HoVKk1kwoLxkAAAAASUVORK5CYII=
; thumbnail end
;
; 

; external perimeters extrusion width = 0.65mm
; perimeters extrusion width = 0.65mm
; infill extrusion width = 0.65mm
; solid infill extrusion width = 0.65mm
; top infill extrusion width = 0.60mm
; first layer extrusion width = 0.65mm

M107
M190 S60 ; set bed temperature and wait for it to be reached
;TYPE:Custom
;Begin Start GCode

;set temps
G10 P0 S210
G10 P0 R170
G10 P1 S0
G10 P1 R0

G28 ;home all axis
G29 S1 ;enable mesh


T0


M116 ;Wait for all temps

G90
M98 P"prime.g"
;End Start GCode
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
; Filament-specific start gcode
M703
M107
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.2

G10 ; retract
G1 Z.2 F720
;AFTER_LAYER_CHANGE
;0.2
M800 F"layer"
G1 X147.785 Y143.625 F10800
G11 ; unretract
M204 P800
;TYPE:Skirt/Brim
;WIDTH:0.65
G1 F1200
G1 X148.844 Y142.663 E.06931
G1 X150 Y142.393 E.05752
G1 X180 Y142.393 E1.45379
G1 X181.375 Y142.785 E.06931
G1 X182.337 Y143.844 E.06931
G1 X182.607 Y145 E.05752
G1 X182.607 Y175 E1.45379
G1 X182.215 Y176.375 E.06931
G1 X181.156 Y177.337 E.06931
G1 X180 Y177.607 E.05752
G1 X150 Y177.607 E1.45379
G1 X148.625 Y177.215 E.06931
G1 X147.663 Y176.156 E.06931
G1 X147.393 Y175 E.05752
G1 X147.393 Y145 E1.45379
G1 X147.761 Y143.711 E.06495
M204 P1000
; printing object Shape-Box id:0 copy 0
G10 ; retract
G1 X151.132 Y146.132 F10800
G11 ; unretract
M204 P800
;TYPE:Perimeter
G1 F1200
G1 X178.868 Y146.132 E1.34407
G1 X178.868 Y173.868 E1.34407
G1 X151.132 Y173.868 E1.34407
G1 X151.132 Y146.222 E1.33971
M204 P1000
G1 X150.525 Y145.525 F10800
M204 P800
;TYPE:External perimeter
G1 F1200
G1 X179.475 Y145.525 E1.40291
G1 X179.475 Y174.475 E1.40291
G1 X150.525 Y174.475 E1.40291
G1 X150.525 Y145.615 E1.39855
M204 P1000
G1 X151.105 Y145.68 F10800
G10 ; retract
G1 X177.44 Y146.314
G11 ; unretract
M204 P800
;TYPE:Solid infill
;WIDTH:0.658716
G1 F1200
G1 X178.413 Y147.287 E.0676
G1 X178.413 Y148.158 E.04281
G1 X176.842 Y146.587 E.10915
G1 X175.972 Y146.587 E.04281
G1 X178.413 Y149.028 E.16969
G1 X178.413 Y149.899 E.04281
G1 X175.101 Y146.587 E.23023
G1 X174.23 Y146.587 E.04281
G1 X178.413 Y150.77 E.29077
G1 X178.413 Y151.641 E.04281
G1 X173.359 Y146.587 E.35131
G1 X172.488 Y146.587 E.04281
G1 X178.413 Y152.512 E.41185
G1 X178.413 Y153.383 E.04281
G1 X171.617 Y146.587 E.47239
G1 X170.746 Y146.587 E.04281
G1 X178.413 Y154.254 E.53293
G1 X178.413 Y155.124 E.04281
G1 X169.876 Y146.587 E.59347
G1 X169.005 Y146.587 E.04281
G1 X178.413 Y155.995 E.65401
G1 X178.413 Y156.866 E.04281
G1 X168.134 Y146.587 E.71455
G1 X167.263 Y146.587 E.04281
G1 X178.413 Y157.737 E.77509
G1 X178.413 Y158.608 E.04281
G1 X166.392 Y146.587 E.83563
G1 X165.521 Y146.587 E.04281
G1 X178.413 Y159.479 E.89617
G1 X178.413 Y160.35 E.04281
G1 X164.65 Y146.587 E.95671
G1 X163.779 Y146.587 E.04281
G1 X178.413 Y161.221 E1.01724
G1 X178.413 Y162.091 E.04281
G1 X162.909 Y146.587 E1.07778
G1 X162.038 Y146.587 E.04281
G1 X178.413 Y162.962 E1.13832
G1 X178.413 Y163.833 E.04281
G1 X161.167 Y146.587 E1.19886
G1 X160.296 Y146.587 E.04281
G1 X178.413 Y164.704 E1.2594
G1 X178.413 Y165.575 E.04281
G1 X159.425 Y146.587 E1.31994
G1 X158.554 Y146.587 E.04281
G1 X178.413 Y166.446 E1.38048
G1 X178.413 Y167.317 E.04281
G1 X157.683 Y146.587 E1.44102
G1 X156.813 Y146.587 E.04281
G1 X178.413 Y168.187 E1.50156
G1 X178.413 Y169.058 E.04281
G1 X155.942 Y146.587 E1.5621
G1 X155.071 Y146.587 E.04281
G1 X178.413 Y169.929 E1.62264
G1 X178.413 Y170.8 E.04281
G1 X154.2 Y146.587 E1.68318
G1 X153.329 Y146.587 E.04281
G1 X178.413 Y171.671 E1.74372
G1 X178.413 Y172.542 E.04281
G1 X152.458 Y146.587 E1.80426
G1 X151.587 Y146.587 E.04281
G1 X178.413 Y173.413 E1.86479
G1 X177.542 Y173.413 E.04281
G1 X151.587 Y147.458 E1.80425
G1 X151.587 Y148.329 E.04281
G1 X176.671 Y173.413 E1.74371
G1 X175.8 Y173.413 E.04281
G1 X151.587 Y149.2 E1.68317
G1 X151.587 Y150.071 E.04281
G1 X174.929 Y173.413 E1.62263
G1 X174.058 Y173.413 E.04281
G1 X151.587 Y150.942 E1.56209
G1 X151.587 Y151.813 E.04281
G1 X173.187 Y173.413 E1.50155
G1 X172.316 Y173.413 E.04281
G1 X151.587 Y152.684 E1.44101
G1 X151.587 Y153.554 E.04281
G1 X171.446 Y173.413 E1.38047
G1 X170.575 Y173.413 E.04281
G1 X151.587 Y154.425 E1.31993
G1 X151.587 Y155.296 E.04281
G1 X169.704 Y173.413 E1.25939
G1 X168.833 Y173.413 E.04281
G1 X151.587 Y156.167 E1.19886
G1 X151.587 Y157.038 E.04281
G1 X167.962 Y173.413 E1.13832
G1 X167.091 Y173.413 E.04281
G1 X151.587 Y157.909 E1.07778
G1 X151.587 Y158.78 E.04281
G1 X166.22 Y173.413 E1.01724
G1 X165.35 Y173.413 E.04281
G1 X151.587 Y159.65 E.9567
G1 X151.587 Y160.521 E.04281
G1 X164.479 Y173.413 E.89616
G1 X163.608 Y173.413 E.04281
G1 X151.587 Y161.392 E.83562
G1 X151.587 Y162.263 E.04281
G1 X162.737 Y173.413 E.77508
G1 X161.866 Y173.413 E.04281
G1 X151.587 Y163.134 E.71454
G1 X151.587 Y164.005 E.04281
G1 X160.995 Y173.413 E.654
G1 X160.124 Y173.413 E.04281
G1 X151.587 Y164.876 E.59346
G1 X151.587 Y165.747 E.04281
G1 X159.253 Y173.413 E.53292
G1 X158.383 Y173.413 E.04281
G1 X151.587 Y166.617 E.47238
G1 X151.587 Y167.488 E.04281
G1 X157.512 Y173.413 E.41184
G1 X156.641 Y173.413 E.04281
G1 X151.587 Y168.359 E.3513
G1 X151.587 Y169.23 E.04281
G1 X155.77 Y173.413 E.29076
G1 X154.899 Y173.413 E.04281
G1 X151.587 Y170.101 E.23022
G1 X151.587 Y170.972 E.04281
G1 X154.028 Y173.413 E.16968
G1 X153.157 Y173.413 E.04281
G1 X151.587 Y171.843 E.10914
G1 X151.587 Y172.713 E.04281
G1 X152.56 Y173.686 E.0676
M204 P1000
; stop printing object Shape-Box id:0 copy 0
G10 ; retract
M107
;TYPE:Custom
; Filament-specific end gcode
M106 S0 ; turn off cooling fan
G10 P0 S0 R0
G10 P1 S0 R0
M140 S0; turn off bed
;Drop the bed
G91
G1 Z10 F1000
G90
M0
; filament used [mm] = 77.63
; filament used [cm3] = 0.19
; filament used [g] = 0.23
; filament cost = 0.01
; total filament used [g] = 0.23
; total filament cost = 0.01
; estimated printing time (normal mode) = 1m 24s

; prusaslicer_config = begin
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = G:\\Rancor\\Rancor\\PrusaSlicer\\BedModel.stl
; bed_custom_texture = G:\\Rancor\\Rancor\\PrusaSlicer\\BedTexture.png
; bed_shape = 0x0,330x0,330x320,0x320
; bed_temperature = 60,0
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 4
; bottom_solid_min_thickness = 0.6
; bridge_acceleration = 1000
; bridge_angle = 0
; bridge_fan_speed = 100,100
; bridge_flow_ratio = 1
; bridge_speed = 25
; brim_separation = 0.1
; brim_type = outer_only
; brim_width = 0
; clip_multipart_objects = 1
; color_change_gcode = M600
; complete_objects = 0
; cooling = 1,0
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 1000
; default_filament_profile = ""
; default_print_profile = 
; deretract_speed = 0,0
; disable_fan_first_layers = 1,1
; dont_support_bridges = 0
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0.2
; end_filament_gcode = "; Filament-specific end gcode";
; end_gcode = M106 S0 ; turn off cooling fan\nG10 P0 S0 R0\nG10 P1 S0 R0\nM140 S0; turn off bed\n;Drop the bed\nG91\nG1 Z10 F1000\nG90\nM0
; ensure_vertical_shell_thickness = 1
; external_perimeter_extrusion_width = 0.65
; external_perimeter_speed = 35
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 45
; extruder_colour = #FF8000;#0000FF
; extruder_offset = 0x0,0x0
; extrusion_axis = E
; extrusion_multiplier = 0.96,1
; extrusion_width = 0.65
; fan_always_on = 1,0
; fan_below_layer_time = 100,100
; filament_colour = #FF8000;#FF8000
; filament_cooling_final_speed = 3.4,3.4
; filament_cooling_initial_speed = 2.2,2.2
; filament_cooling_moves = 4,4
; filament_cost = 24.99,0
; filament_density = 1.24,0
; filament_diameter = 1.75,1.75
; filament_load_time = 0,0
; filament_loading_speed = 28,28
; filament_loading_speed_start = 3,3
; filament_max_volumetric_speed = 15,15
; filament_minimal_purge_on_wipe_tower = 15,15
; filament_notes = "Affordable filament for everyday printing in premium quality manufactured in-house by Josef Prusa";
; filament_ramming_parameters = "120 100| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6";"120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = PLA;!Off
; filament_soluble = 0,0
; filament_spool_weight = 0,0
; filament_toolchange_delay = 0,0
; filament_type = PLA;PLA
; filament_unload_time = 0,0
; filament_unloading_speed = 90,90
; filament_unloading_speed_start = 100,100
; filament_vendor = Prusa Polymers
; fill_angle = 45
; fill_density = 15%
; fill_pattern = gyroid
; first_layer_acceleration = 800
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 60,0
; first_layer_extrusion_width = 0.65
; first_layer_height = 0.2
; first_layer_speed = 20
; first_layer_speed_over_raft = 30
; first_layer_temperature = 210,0
; full_fan_speed_layer = 0,0
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 40
; gcode_comments = 0
; gcode_flavor = reprapfirmware
; gcode_label_objects = 1
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = duet
; infill_acceleration = 1000
; infill_anchor = 2.5
; infill_anchor_max = 15
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.65
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 70
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]\nM800 F"layer"
; layer_height = 0.3
; machine_limits_usage = time_estimate_only
; machine_max_acceleration_e = 1500,1500
; machine_max_acceleration_extruding = 1500,1500
; machine_max_acceleration_retracting = 1500,1500
; machine_max_acceleration_travel = 500,1250
; machine_max_acceleration_x = 500,500
; machine_max_acceleration_y = 500,500
; machine_max_acceleration_z = 100,100
; machine_max_feedrate_e = 60,60
; machine_max_feedrate_x = 180,180
; machine_max_feedrate_y = 180,180
; machine_max_feedrate_z = 15,15
; machine_max_jerk_e = 25,25
; machine_max_jerk_x = 6.7,6.7
; machine_max_jerk_y = 6.7,6.7
; machine_max_jerk_z = 1.7,1.7
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100,100
; max_layer_height = 0,0
; max_print_height = 601
; max_print_speed = 100
; max_volumetric_speed = 0
; min_fan_speed = 100,100
; min_layer_height = 0.07,0.07
; min_print_speed = 15,15
; min_skirt_length = 4
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.6,0.6
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_T0-{filament_preset[0]}_T1-{filament_preset[1]}.gcode
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 800
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.65
; perimeter_speed = 45
; perimeters = 2
; physical_printer_settings_id = Printer 1
; post_process = 
; print_settings_id = N0.6 0.30mm QUALITY
; printer_model = 
; printer_notes = 
; printer_settings_id = Rancor
; printer_technology = FFF
; printer_variant = 
; printer_vendor = 
; raft_contact_distance = 0.25
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 0
; resolution = 0
; retract_before_travel = 2,2
; retract_before_wipe = 70%,70%
; retract_layer_change = 1,1
; retract_length = 0.5,0.5
; retract_length_toolchange = 0,0
; retract_lift = 0,0
; retract_lift_above = 0,0
; retract_lift_below = 600,600
; retract_restart_extra = 0,0
; retract_restart_extra_toolchange = 0,0
; retract_speed = 40,40
; seam_position = nearest
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 0
; skirt_distance = 2
; skirt_height = 3
; skirts = 1
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 20,20
; small_perimeter_speed = 25
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.65
; solid_infill_speed = 70
; spiral_vase = 0
; standby_temperature_delta = 170
; start_filament_gcode = "; Filament-specific start gcode\nM703";
; start_gcode = ;Begin Start GCode\n\n;set temps\nG10 P0 S{temperature[0]}\nG10 P0 R{if temperature[0] == 0}0{else}{temperature[0] - 40}{endif}\nG10 P1 S{temperature[1]}\nG10 P1 R{if temperature[1] == 0}0{else}{temperature[1] - 40}{endif}\n\nG28 ;home all axis\nG29 S1 ;enable mesh\n\n{ if current_extruder == 0 }\nT0\n{ elsif current_extruder == 1 } \nT1\n{ endif }\n\nM116 ;Wait for all temps\n\nG90\nM98 P"prime.g"\n;End Start GCode
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = 0
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.25
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.55
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 2
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0.3
; support_material_interface_speed = 80%
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 50
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 50
; support_material_with_sheath = 0
; support_material_xy_spacing = 80%
; temperature = 210,0
; template_custom_gcode = 
; thick_bridges = 0
; thin_walls = 0
; threads = 32
; thumbnails = 128x128
; toolchange_gcode = ;T[next_extruder]
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0.6
; top_solid_infill_speed = 45
; top_solid_layers = 4
; top_solid_min_thickness = 0.9
; travel_speed = 180
; travel_speed_z = 12
; use_firmware_retraction = 1
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wipe = 0,0
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 170
; wipe_tower_y = 125
; wiping_volumes_extruders = 70,70,70,70
; wiping_volumes_matrix = 0,140,140,0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
