; generated by PrusaSlicer 2.4.2+win64 on 2022-05-19 at 02:49:28 UTC


;
; thumbnail begin 128x128 14592
; iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAqh0lEQVR4Ae1dB3xNZ/+/JDJJBIksxI
; i9WiFUtIrqqy1Vb23+iNXSvkWNFn1VK7R9K4oYNRK09ioam1Zbe0fEDhJiBNmRhPPL/3yf5Nyee++Z
; N0krlcfn93GT3DOe5zee334MBoOBNAKn47uKYO9gTyEhIcQ94YieEhH/n/ng8gc+//bbb+Tp6Wm83t
; bWllzdXGngwIG0e9duLiU5hZ4+eWpyLVk5srKyKCYmhr6Z8Q21DGzJ2djakE1pG7ItbUulS5UW1kFy
; LRwdHSk4OJhu3LxBBR1Pnz6lnzb/RA0bNCQbGxt2/3Jly9HI90fSnYQ79OTJE5Kbptz8Hzx8QAd+O0
; ALFy6k6dOmMxwY/mrkC+Dh7kH79u4jLoezIADzCeRk59D8efPJwcFB6r04fpG4cWPHUVR0FEMguxx3
; eErWD/769LR0OnTwEI36zyiqVaMW2Zex50AMpUqVkp0X/vbCCy/QtshtlJOTQ3oHx/9LfJBIY8eMJT
; c3N3bP0qVLk39Nf1q9ajWbH4hD8loJxOO7N27coNGjR5NfdT8ylBK9b95nVcQXOvIFaNasGSXcTjCZ
; gBz1Ps56TMOHDScHewfxe3HGiZQ2cA5ODtThtQ4UHh5O9+/dV5Qwega/iFxycjIXGRlJw4YMoyreVa
; iMbRnFuZUvX54mTZ5EDx480P4c7ikdPnyY2gS1oTJl8u5vb29P3bp2o0uXLjGC0sP1KakpNHvubPLw
; 8FB6V0XkU5EBjzSbMjY0bPgwxuFaxPbtW7fp5TYvmyJf+FwqH/I5pmbNmvThhx+y7SMzM5OsHSbvlS
; 9V7t65S+vWrWOIqVChAnteqdKlQIQmc8RW1b5Dezpy5AipTS89I51CZ4aSt5e38XovTy+aNXMWpaam
; MpEv937maweuj7kYQ126dmHvpoILkfgylCKbUjacv78/N3feXGr5UssiJQAsmKOTIy1ZsoTLzs5m4k
; 8BEfQk+wl34ugJztfXl2PXl1ImVohjRwdHatKkCX0781u6cvWK7ELKLa7kH57mQdbjLLoZd5Nmz55N
; 7V9rT2Xsy0huDz4+PhQ2L4zS0tMsn8H/A3d3e6ebcYsD4bRp3YaOHD7CuF6PyH/8+DGtXLWSfKv6as
; VF3gcoOLxY4wYHD6aEhAR2o/iEeBo9ZjQ5OTsVHSHwotunig+dOXuGcp5KizhONKDsRUREcE5lnTjG
; caXUnwHuLG1bmonC/v/Xn/bt3ye7qOLnkdLgLBf+9NnT9PU3X1Ojxo3Izt7O5B2A3F69e9HlK5eN14
; DoV61cRf61/I2cWt61PI37eBwl3k+UVfSk3g8/3rp1i0lU82cblKW6AVxPXpW9OFBORkaGkUtw07SM
; NNr400aqXbt2YSPf+DKlbErR651ep7TUNFmKFyaM//GOY0aPEfQBzWBrZ0uvdniVTp08JasXFMSCYF
; KKXzuI7EOHDtFH//mI6tevb5R2gPoN69P6jeuZpfDe8PfIxcWFvRuUywb1GtCWzVsYYejheqzZ3n17
; qVGTRpoYwgR484Z7vePr3OXLl//UoM1Gdk42Xbh8gXr36U1l7MoUiSSwK2NH076cRumZ6UbKN6d0MR
; HcvXeX2rdrr2WPY8QmKGWPHj2SXdiCIF88gDwgBbpN0qMk2r59Ow0YOIAqeVQimJXOZZ2ZWQtRL0iH
; fn370Y3rN3QrepjP51M/p7Llylq39l99/RWjWDWTBRpqUkoSzVswjypXrlxgrpcCmD179+41EflyE8
; e4cvkK1a1TV/GZIBDoAJHbIxUVKbOfLZCglzbM74H1vXr1KrVp08ZizvPmzaOUtBTKeZKj6f2EkZKS
; Qv3699PP9WJ8YO9S2g9NXoT/B416/vz5zOmhE/GqVgWU0BdfeJHi4+M5mF7iyUstAsd/ZctPW9i+me
; +kMQG848DggWxvJHlEWSAfyDp48CDTyq/FXmNzxu/0KJDm9zwbdZY6/asT2dmZ7s9uFdxo1txZ9ChJ
; XjIp3fvU6VPM9LUtY2sNM3IGPZSdlpZGIdNDmOmj80Gav89zLDdk8BDKSM1g9rfiAsDfw9v6n03+jG
; 0h4mf6+flRxLIIppzJLaz5vYX9+5uvviHPyp5Mo8fW8c4779DGzRvp4cOHpHdkZWfRksVLqHq16rIO
; JBBFl7e7UNS5KMX3kxu8j4KmTJ3CiEk3TrQ8AO8B9+jr/3rd6KAoAuQbv4s9cVn4MsrJytEkehMfJl
; KP7j3YAuP93njzDTp37pzSfCy4HsiPOR9Db7/1tqRyCd2narWqNG78OPrj9z+YsmziIoDIJ7HLgGMm
; 4sABA8nZ2VnTGtSsVZOW/7AcEke3LgIpvmv3Lu6FZi8o6UWWkljtxhB9vNlFvlV8FV2gViKeM8hsD1
; X9qtKJkyc0770Q86+99hrN+GoG2xulBifjNIGU+GH5D1Szek1FpRLzh1++bNmyFNgykG2F/HbFiAf7
; t2DGQl/6edvP1KRRE6MfXys4OTlxMOXi4uPImgETfujwocy/ogknSje7nXCbaa8SNytS5AuL3blzZ0
; pKSiKtA+JbqwYtcD28i3DvItCiB1EAEEvFihVpyNAhtHXrVkpJT2F+/E8mfGLcJvGdGn416IvPv6AG
; 9Ruwn0EUEszEie8bEBBAO3bukFUMlQasuR9+/IFq1KxBBjX9S+oG4Ao8vEFD/oVtSmtdEK1xAynES1
; 4Lk2nKlClWBVXMkG3B9bjnnl176MWmL5KtjW4FygKwRfjX9WfxDWGbZHv7W13oQswFZtsj7jHivRFs
; i4MJKJI2kusGCwF7uzW6Bwa/bXOdu3RWNt3NL4JCMXHSRHIt71oUXG/+fVWigRK2a88uqzhBjushVT
; 7/7HNyr+heYMTLQWWPyvS/r//HtiOx9QD38bo166hqlaogAo6XBorzBzF1fL0jHTtxTJcpKsw9NY1X
; av/3Dbl7WM6V6TrixTl16hS9/MrLRgdFISNfius1Xd+4YWO6ePEi6Rly5t3pU6epY/uOFuZYYQHWrl
; VgK6Yoynk1QRBXLl3h3u78NkMwrlHTr6pWrUoLFi5gQSO1eUtZD8gDaPVSK+P24+3tTeFLwvMIAHtG
; WFgY807pVPSsFfmaQVC8sM9C89aCeCmRD1v++wXfUxXfKpI+g8IAVxdXGv3RaLp3754mPz5c3zO/nc
; n0BS1EwDyGvOPn6rWrsnMnhXH//n36eOzHedvS+QvMhDZcv36devTswbJ0dEzWWkXPaiJwdnKmsLlh
; qkEcs58ZIq7HXqd+ffqxexQEwXKAvbxenXq0cf1G3X787KxsWr92vWbzGmvRqFEj2rR5E3uWcF+tPg
; NmsUCnwrd5MPjX9tfqTxcjVC/iqTCIoKpvVTp25BjzAGpZXAzE4sVpVWKoVcmJgTXvY+RKfh/t1aMX
; Xbt6TbcfH8hf/eNq8vb01iN5GSCINHbcWEgbzciXGgYJBBUUpBM2CuPepQwcdBSIWKWFFY87d+7QSy
; 1fsljgdxt70oH3A3MjgwNy8bmsvT57Hffz8faheXPnUXp6ui6ux6/uJtylIcFDVDOLlNYZCiTW4/c/
; ftfszlciADWkkhXfLdyUMj7oUdquNI0aM4qliKkhH9647KfZdCbqDFOicA8gOuRftXOBfDHMfrterm
; c5bdsgkNaubTs6cfyE7oQNiOD9e/ez0K9erpdbV+huobNCmR9E7zDoeZAkJ/Cx/AaNG3C8giIn8gsP
; 8uPq9o723MZNGzk10xAE8OTpE8rKyWIpXG3qeBM43hz5AuBv/6qjbBpWcKtAkz6dxGxzvQkbqSmpNO
; WzKQXVRSTXleUOdutG52POU2ERAKeGjIoeFSk0LBSxeS58WThXrVo1UHWB9noNRADRR3Xr1qXY2FhN
; k8TiX1k7Uxbx5vBpuxq55lsCngnX7vbI7bq5Ht+NjoqmV9q8okff0s2MgNp1atPK1Stlg2BaCEAT1w
; e1DeIOHz/MkkXYJHn/d1R0FNfpjU7MwVEEyDd5L3s7e+rfrz/bf5VGWtwlOjq5q2bkC7C0e6PcoOp5
; 0TVwbPDAYIqLi9Ot6D3OfEyLFy5mTieEuwswd83fR6xixMgRdOv2LdJLAKoPcnZxpgmTJ3AJdxMsxR
; z/LzklmaZ/NZ35yAsZ+Ra/hzNn7py5LPNGasTvW016EW++JQwJqkMRvANGKW9CTtGLvxlPvXv0Lqir
; 2SpmgqRpEdiC9uzdo5jHYND6ICRW1m1Yl9uyfQuX+TjTJE3LwvHCS4P9v+6nFs1b6I6G6V0AL28vlj
; 0rHjkZqXQm9P3cgiBfDKdnvpebcf+WZuSDICO3RbLoYgEVvYKuHWPEaSHTZBNODFoehGTK/oP7c1ev
; X+V4pYoTI17OCQFbHfnzSHy0kghU3wsePXjQXn3lVVYIgnHn0DYqLMSL4eCY9rmQKEqEjx8fPXzEqn
; r0JqwWBfIF4J1MXKc3O7HsISkCkL+YV/S8q3rToohFXEpqinHCnAbPE9yMly9eZsUTVig+mhYA3IWa
; PQBKn2KWfZ5bFMgXAyRLTrplvgHS1Y8fPU4tAloUxNVcNIpzPiBLavHSxSYudVkCQBi445sduZNnT3
; K84mOBeCUCQGxh7bq1VNu/tl4RqK7pSiRA1nEvR2v7vVDkyBdLg8TTvxrnm5mRSbO+nUVu5d0KgtjC
; Rr5sAevAQQMJIQBGACh8NElZ4hfYxc2Fps6Yyt1/cN8C4UqIx5/u3L1DH/7nQ81pULoWIN8P4FTWia
; Wnubq60sAAHzrwFyHeHGBaXomOorfeeIvl9RcAUUXK+eYApmzatClt3baVWFbwhnUb8riVV/SaBjTl
; du/fzfGeNgtFTwn50JD3/8Irfi10K37aFqB0nvlZt35d2r17NyVdO0+/ftI198D7gX8rRPRskutfqf
; AcO9gukUDq5Ohk7b00ExMYyCBwLnLWFy1ZxMXdijNJyVZDPn6NJJIZM2ZQpUqVCjR5Ja6HIiqkeMft
; XUUH/mbEi0GIJxR03khv/3Lql/Qg8QEtWLCAfHx9iiIP0xTMuVwP1+NP56LPsSxcndnC2l44v5zK09
; uTlq9YTmkP71P0wnHPDOLNQWM8gZPi+mYvNqNDfxwylrTDdkcWULsO7fSk5ekHc0SrIV0Y0CSRdw/N
; skgUvXyRj3QopKSn3LhAUL6eVeSLpYHgQZSZu8nvnJyc6IMRHzCuF6qOxQP9BSZ9NikvRc/6CiB1Ah
; CQr4Z45uG6FU/Bg4OlOnYoTtagQ+S7lHdhHkXk1F1dF/rMI94cPmxdTRxPsCB6ME2N6jWY/vU056li
; Iwu425Gki+LPQpcGIsSqEsGTnCes0BG1dmoZrQXh+iYvNKHff/+dkq6fpxMh/YoV4sWAeIJUwglc2O
; gHcCP2xp9dTFQGopqxN2LzGM/eofCsBq0iH2XiU7+YyhQVnQ/RzPWoax/5wUiW8BH/jCl61oI44QRc
; 717JnebOnktZmVma2tcIIW0UnWBdUEVcAJNTXgKoDYih5cuWs6TKQkV+PtejEmjDhg2UnvSgUP34zw
; pAQez8ahCdOnFKc+8ixFSAeKz9/v37OVRCF2JCK2eUAKRxwNZHWvWbnd5Us/U1cz06d7zT7R1mhib8
; sfUfwfVyACX2zsFtmkS+gHwU5P538n/J2dG5cBFvlABWdNFCUwI0cxDamFmLfLeKbjRn7hzWju3i8i
; +KFTILApgrIpZSAyKfcf2TbBS4cugYVggRVUlgW8naNWvRfEk3ESAxAn3+EPIVIV6zoocGVCdOnKDk
; GzFWJWwUd4ByK44niLk+KzuL+37h9xz0hQKEkxWZko8JcMhVMKBdyQcjP6D7d+9b1VgR1bG8HcvBnt
; WCfEdnRxo/YTzLqbu+bdE/WuSrgRBiRnSRKXpPcuDp5Lq/290ax5om5IOgfH18ubA5YcyXY2CiwNaG
; mjdvTr/u/1V3Y0XoEIgnrFm1hmrVrCX9Evlc71/Hn7VqeRQbXazNu8KG06Hv5T66Hk2RP0eySuJCV/
; TyAXkB7dq2444fO27MEjKIObSie0WaHjKd0lLSVKWBVDIEGiy82+3dP6k3n+vREBIlTcipi9vzzzDv
; Chv2jQzK7dOsapEgHlCxQkWa+MlEJnnFqDOYfxGlxJ06daLz584rNnKWIwykPs8KnUXuld0Z8j08PW
; hp+FJKfXDvuVL0rAWYi3qLVJSQz7KZGzfhtv+8nTnyzIdB6iYIC1fzq0YR4RGU/TjbSARaTUaIl4OH
; D9KwEcPo3PlzzI//PCp61oJKPEEzlHUuy7Fs5ptxkuV0sgQggIOjAw0aNIhux9+G84KzxlK4Ugz9+M
; 8KmMUT1LjepMOIXzU/DuXfavUBBoPK3sE7arhGjRtxOyJ35HmwNBIB8vFLFL2Cg1w8QQrxAHt7ew6O
; unNR51TrBSHRDZr2E16ZK+9WniZNnETJj5JVFcSC5uOXgCnIFLBaMGtlj8pcyJchLEFHbbcWtnODVm
; UCgGaEbdu2Zf5sKQUR3q1nOWGjuINcwgkqsVoEtOBgxqs1szTX4wxaxIoJIFXcx5vmhc2jzPRMIxEk
; XTpRLBI2ijuYF7C6urhySCjBMTI6wjpsoD2tqg4gB+go0qNHDxbTvrq2RNH7q+HTdjVzm9avyxxwQq
; cQrVzPilVjollfRYMmrpeB2h5lacOAZsVq4f5JcHRq79z7p37RhfzMx5kUviycNbcoY8McdtZlkwod
; Nkrg7wVjPEEiumiW5Etxt+JY408HOwfRKWgaT90QAJoolJHitEjPAyCJJjPxtiTXwx+zfed2qle3Hu
; N6dvKZoRTbwg09+/SkWv61WKtUcehRKiAB5aM4LcrzBhIFrKwq+JNPPyGXsi7isw8ZoFmlAe3Mk9OS
; WWPmRYsXsaANum84OTiZXICuGcVpMZ5ngDTISkuiE6dOUFDrILKztWO4lMwtYFphfiIC/gfVwH14/v
; x5WrpkKY0Z0IvW/YWFlyVQOPDrf17J7dy0OkM8zoSS3dbF4sJMgaDYrd+XiPxiDh+29lOOJ5DEKPHj
; /7NAMZ5gjvwSP/4/E2QLWI2mQokf/7kAi3gCMxWKSeFlCRQOQBq84JN3YKXhVvwtirsQRUuHdMjdN7
; xFsZpICeiHPcOa537xun+ut0u+FEDr06CgIPpwxHD6vO9ruev7l5h8/1T4aeCLuW/V88g10QHEniE4
; Chr6uNHcrvVLpME/DEI718ut4y5ZXmZpGrg52dHgwCq5PweXRPqKO4Drh/K4LGcv261U2kHgYFua2t
; WqSIu7NyyRBsUUFr3bMLeZr+rhX8rRv2pujjS+bY3cnUOaF6vJP88ARW9UG7/cik6aDsZS/gL0Agc7
; G3qjnnvu6r5Ni9VCPI+wjlfiN303NRfnFaPAp1y5cqzOQzcBILcctX5LlixhJ4q1a9+OGvt50vROdU
; q2hGcUFvbhQ8Lb1hmbTaHqO/ZaLIWEhFBAiwDWJRR4NWvda4l89OJHj99LFy+xilVUlaAm4HzUeZob
; GkqTujQvMRefIYCiN2vwm7mJt0XnDXOmgT1UAv/yyy/00UcfUf169RmO88PDpsjHsemh3+adP2NMMe
; bozxZm/Gecbr1n+RxaG/xSiTT4mwGK3t7VS0jrADGgQHTLli00cODAPwkAbdeDXgqiw4cOaz4S5dbl
; aFr50TslCuLfAFD0Fr3fJTfuUjRZO4BKRgDo/IUe9zhZUs9BSBgZqcm0c8GXueuHBBWrBSzOENGzce
; 7aWZ/nUiEMA/aBQQMHsRbveo5EMR9XTx/i4wntS7aEIoY5PZvnnv51pzIydNSHMAmAY0X27t0ry/la
; b5bJS4Mt304oURCLAKDoLfyod25GSrIqHpDOl5iYmI9AUizvNyA9GHljjRs0Zh08hO/oQbz5OLlzA6
; 0YWKIgFhaE8bGZAL9KtGb1Gk2dRe/evcuk+tdffU03rud1I+UtOUl8MgmAgBDyxYcOGUoZjzPQsKgg
; +Gcj4cp52hryQUk8oQBg7sevVb0WXYq5pFoDiOReSIHAwECqVq0aN2LECO748ePMFDS/1mgFgAhcyr
; lwK35cweGkTS0EgJo0pe9hS9i1MKREQbQCpPz48Oh16dKFFXXKDaG1LPoMXrl2hRo2bMgaTKM7Gw6O
; Wrp0KTtPUMCb2A/ASsR8fX1ZN1AtikTUuSiKiIhg1oOSAnnt9GGWcFJiLqoDzLvPOtSy9OPnN9wqY1
; +Gpk2blncEvMKAFABOdu/ZzRp6si7j+ecvePl6Ud/+fem3334zEoBJfeBbb76l6SBiSIBly5dRQEAA
; TZw0kS5eusioT4x8YS8xSoMSBVEW4MfvWLtSrqzfPp8IKlSqwLx6UlXB5ns38BE2L4xJAIEAhHJAdC
; 2XdAWjU9iXIV8aj4VVG/Pnz6ey5cqSh4cH9ejVg3bs2sGlpKTgjEEybywEaVCiIFqCQsKGJBEEtgqk
; hDsJJg0hpBQ3/ColOYVGvD+C9WqUqAOVfhDOn925c6eqqGHcnZlJM6bPIEd7R1gUnL2DPdeoUSP6du
; a3FH0xmu1HJt/npUGJgpgHGhI2pIN1tqXZ+cBYexzrp6az4ayloDZBUpFB+YcAibhQzjsoHhnpGdSr
; ey/OvJc9ztLr9K9OtHz5cgtd4ejmZQQF8XmVBhoTNmQB7XlX/7hatRmUMI4dP0ZeXl5kpvfJPwAdP2
; EapqWnKT5E2Otv3LhBTZs0NbkHCAJ+BtzL09OTiaIDvxxgbdBxz1uXztGqUd2eKwURit6Il6ppTdiQ
; A6a38WYeRUdriwegEDg8Ipxt8YY/9T7lB9mVsaMfVvwg2WVSQL7oMx0+cpgqV65sKq7MSs3RvTKwZS
; DNnDmTkJaezHutdi2Y9lwknMCP/1I1t9wCIN4E4Mp/o9Mbf3r+lAaPKV6558ZPGM+Jzh9Qf4ivjy+d
; PHmSpLje/Bk4Q3fBwgWsh5CWe5cvX5569uhJmzZuouP7ImnF8Nf+sVsC8vH93BwLBfHmDDV9xnRtHc
; J4Qf4o8RG9/trrwtEz6g8AB6OhUOLDREXk51FA3lm6ONyIaZ1q9y7NTgDn0Mkap5d+/J8P6ftRvf9R
; 5iIUvV5NvXPtCnbil2IrH0jdPXv2SLqJzfH1JPsJh1Z/NWvU1EYAjMp4apkyZQqXnJqsqnEigwjept
; ZtWpOGFjQcxJiQpoTPsEA+De5OqwYVf3MRfvzGXi4F5XLVPk5YNzSDuBV3y6SHo0RXd/Yz9K+1a9dq
; JwC8hGt5Vw4OCJiGakQAcYTz6n2r+CoRgcXEXFxcaFrINEpKSmLxhE2TBxRLcxFcP3vwG7k/hi9ieZ
; VfhXxFE8ZOoH93/ze1at2KvLy9mGKMsxr0rI8aEQwdPJQeZzyWRL75QAqAQeNDOOEBzZo1o7j4OE2m
; B4hg5eqV7LRvVUnA/63pi03p119/NfE9FMd4Asw7lrBhlkrHtmB+3bAuOBEUetXceXNZ5y70aXJ0cr
; Qa+QKUdS5LK39cqTmYZ9CAeIsjRwYFD2JmnJYBd+Xoj0crnngJhRFOjYSEBFnJUhziCTDvkLBx8cSh
; P19cFI+XGyAIuN4PHT5EEydOpAb1G3AFOSiqik8VOnPmjOoxwIgXGNS4XgpwZOyiRYs0tyZ9cP8BtW
; vXzjwdmQHOC1y7bi0TR2rjWY4nQOSv/2qc1WlaWEt49BgxpKTS7t27qWvXriyvXwfyGc6wzlhvKO1q
; Pf4NepEvgJenF/3xxx+atgJMLvpCNDVo2MB4PSTCO/9+hy5duqTZk4WBNPWfV4fTvG7PTska/PgHf1
; 5HhT2wFZ4+fZqGDx/OsraYG1eDrgDpASb9bMpnFm5482HQi3hhv8bLdHitA925d0dWxIlFECazefNm
; puG7VXCj72Z/pyniKB78tsMtCV/CIWTtzIdFg1v4/q0KIrg+bFhn03x8nUPLZg0GiYmOob59+1I513
; J5+pQ0zjgxg1WoWIG2bdumyGAG3cgXEQEOgxo7bmze6dcqE8OPOH4GXsVjx46pOi3MFyD2eiw3YNAA
; HIhgcnB1az+3v6WAFYre1sWh9FcOuHJ/O/gbtX21LfOd8OvAKeEPkqBp06YUHxcveTQ9hoEPKFjVKJ
; oBT4mV3CvRxo0bVcOSor+RrknzusG2yG1cgwYN2IREzQ6N71y5nP1fVsAKRS/ig64W+fiYv3D2HwDK
; r5AxJYB4fazOueOvSnqUxC36fhG5u7tjTRRxhzUbMmRI3tlPEmc8GDas30D+tfzJKgLgAUml6CyK9C
; Nr5yQ37t67y3068VPmGxBpxZITRjl7URewImFj85wvTBQ9bGOHDx+mWbNm0eAhg5nHNKBZADVu1Bin
; dVGrlq2od6/eNPHTibT5p83MhBbO8TGul8ZlExMOYjPR56K5l19+mRX1KJ0wCr8/ikUlTw3D/VADCH
; +8tadVQiT37dM370j0QhjQF44cO8K9/Ere5MQiX+1dUM5eFAWsrPAyX9FDosz12Os04ZMJVK9BPbK1
; s2WgZLqBUSCykTjTPKA569979OhRys7MJmvObwYhYJ3QCxgmNJ4v52eBKx/xnDOnzlhKAOEDDnDGca
; LI6tFJAGwLgdY5Z/YcTQkkSiMpOYmbEzaH86jsYc71WrcpDtIACmJhmIvmhZf37t2jL6d9mbdO4hQr
; Hdum4BRDPB8SAtyZeC9R0zmNUlsHwvVz589l5zrJEQCyvjt26MgO/ob9b0EAGNjHjh45Sq+++qrWQ4
; uNHkLE/D3cPejIkSNWbQVQ9C5evsj16NmD5arp4Xrz9xGgoAqiuPAS74fimRYtWphyuo5W+3LX4Cwm
; bMOhM0MpJSmFRVSlhpLewA6CCA8nb09vyTVjOOKlxMTJE4XUf0sCEAYyd7Bn6XFCgMpABNiT4ObUMy
; A11m1Yx9WsVVOs6OlVTiW/a42CCEUP5p2g6OEULmTiVqpUST+yNQLmjLnXq1+P1qxZQ2mpaZy54qi2
; jiCcjes2kqurqyzhuVZw5SJ3RBodRAa5m0GDjYyMpIYNGuqaBPbsMWPG5Ck6Gvw7mFj8rXjGAVZyvS
; rU4r2N3386VFM8wbzwEo4YJFzo1I8K8v4sp7L/gP4UdSZKVhrIDTATurw7O8snmDZunFcFpkgAwoCy
; M2jAIGZ/a50EKDByC09lOZyigiNQNZSq+Qvn56UuFwLXCwCCAvJOnDhBWY+z6OqpQ4oNMcWFlxD5Gz
; dtpBo1auhGYEGQL3xGi/eqvlXZieJ6lWsQQci0ECHt2+KdsC79/68/y9swkIaBkqKIpRHk4+OjeTLo
; QnHzxk3Nh0+j6cTw94YX6iJjAbCV8eLU6A2TKmCFord88vBclLoLA98/f/E8denWhUm1Ika8+fXsM3
; IwULr/9ddfU3KSelGoeMA85UPDskElMFvY3DB1AhAnEJw9fZZxlFRQxxzgKu7eo7uFu1cmd52DZnr7
; 9m2W1KCigOpaaCxA+3btWa2c2CUqFLAiYUPJj//w0UP6JvQbquheUatiXBDEW3Irr1vhxI/3hr9Hjz
; Mf6/IZwLyv7lfd8r3zawuqVKtChqizUbJauxSyYEZAvCCXT3Fi/ANs7W2JN+nyEkiIk0V+3gdiVawo
; S8NZNhKLbbXHEvdCyhTq4sTVNEg40eLHxxZ14OABCmwdqBjWLgTkS78/70PAFjxyxEjKSMtg26pclM
; 9kjfnvgcthbkoxLfsdMnYWL1pscsq0msYJhO7ft585NGRfPJ/KPDw96PjJ4xZVQpLPgMrAxxVW/bCK
; nJ2cdS+UGmBLgMMKkkavqYrv30q4RaPGjSLncs4FfSerrkXexJiPxzCCFI74kUV+/nryfhXWC1r2vj
; Z2NuzGvXr3ops3b+rqC4CikZHvj2Ttx5QI4aXWL3EJdxPE5xLJxwqeciylCYkR+Zp3oVoEkAZIPt2x
; Y4eugJQwMjIzuPWb13O169bWtBUWFvIFQMbPshXLKCObt+U59feHFRERHkG2NjJ6DI8cQRxwtevU5h
; Cy1ROfh+RYu2Yt1aheQ2qiRkfR+Anj2eJJUa75AH0kJiZyHTt2ZOKvMAlAAIjFCeMnMA7RSvNifejS
; Vd593renUGShFfGK0TutgLWOuRBj8k6SIz8CeOfuHapSpYr0/RBn5gMXxpdBvH706NG6nDl4hwsxF+
; jf3f4taMwWk8N9Gdc9faLlfmxSSGuq619X8gzDwgBwMFyxyM3TQ/TCSE5JprCFYeTp7alXcS2QFIDn
; MHhIMLYCdcrlpwUzErEe5mQzZyh+z+V27tjJwrrCJFjlTmAgi3Lp2Suh8c8KncWZecyMlF+zZk26dP
; mS7PXmYVLoGpM/m2ytqNUEmHPFChVp9uzZJnqQ+J0Upsze8ejJo9S2fdu8DF915BcM8nQrzt3DnaKi
; ojQ523Kyc2jhgoXMmrBgJigKUCpQWYLmA+LqURAFKnzT09NVH2IMU/L76qGDh6hNmzaWk+dfHh1IHz
; 18JHVMnUmJGawNiGgog+zQwyLaCgSAvoEcvOvXr1vVJ+nu/bs0acokcnF1Ebuyi+x9obfN/m62bKKH
; +di1cxc5OTpZEqfwhZTUFBo8dLBFWBEL81bnt+jKlSuazUX8zEfNuPFjxzOlxeTFeXNm/oL5zDMHhc
; /8emwRx04co1atWimfeFlE0qBa1WpIcEGoVXdE63HWY/p518/UsElDTmQuFgkhgCG6d+9O2Vkaejjw
; Mzl+9DhaAFkm1IiQRgm3E6CxW9SQ4yI/Pz9auWqlSbhX0a6nvGyerVu2skOLxfdzr+ROhw8ehmgyuT
; 49I51Cvwtlf1c98bLogHOwd6CRI0dS4oNEXVsgc2g9fcrF3oil4GHB4NIikwIggFaBrSglJUX9Hfk/
; nz11lhFA/nb653uZTYBOnTrFSo6lHgpzb9jwYawNmVbxiK9du3qN+vXtJ/ZNU8uWLTkQHAYUMGQUdX
; 2nK9mXsc9DPu8GhfQQRP9fJQUEwEIhn+7gwYNaM59N1iM1LZULXxHO0t5V2rWrEqQkAdiUog4dOzBJ
; qmULOLD/ALN8LO4l9eWfNv8kG1LEwjRp2oTbt2+frr0SDSSQx+bl6cWUQmwtEyZMYI2LURdQvVp149
; Hm8DJOmTqFzp47S8silrG+90h2wDV/kTvWCEhHmzFjBouHaEG8yXbG60Nnzp2hNzq/IacgWvVOcLCB
; qAYNGsQUPLWBbXXt2rWcpL9G6gK4S5H1IuZY85cCQqZ+MRUiSLOuxC8IB5MLpckgJOgDHTp0MDmp/M
; VmL9KOPTsoMyuTBO8hlNRr167R9OnTKejlIJbzLibIorQSADBt4ZNAEyy9MXoMFGhM/2Y6uVV005Vo
; Iwn5HlaYguFLwlXFP/QsJIsMGT6E9/oZLBNY5C7Eftynbx/ZkGL+wnDtO7Snc+fOKb6IuXmHhJM+ff
; qY3AvUOXT4UIq9GUtKziIQ5+Gjh2nyfycTEkgcHB0YgqwopdJdeOnt5U3LVywXsn11KYlI6d53YB8F
; BAYUPJ7AI7F+/fqslE5+0SmvOyj6ASQ9YnWXkvdSemkkDcBRorR4WBiEiRcvXixZ3iWxN7LqXzfXP7
; kBCuaKlSsoNSOVpDqLWc4tL80a9YkHfjvA2qJCbzFLIC0S4BmCGzhgIPOucRynRxdiX42/HU8fjPpA
; yH3QDVgzbM8L5y+U7doiXncE2DZv2kxQbHURAK5nIvvUSWYaqXGOnb0d9evfj+Lj440LI14cKFLRMd
; FMlArmHfzTMDGxT6KESc1FLD9bnsofPKIN6zYwjxcqYowSoZTBXOwVOIgDJPCWDbdnzx7OyngCrVm/
; hmr61xQURM0VWdAlJk+cTDlZOaqhYTAKuop27txZfuuRS9gQO3bCl4VLa5BmAO6rV68ebd22lZlDwv
; 2wB0UsiyAfbx+joofv49iS7du3M/tZp0SVHk/zool3b91lmbY456isS9m8TiWlCz9hA2lXkyZNYj4U
; ve+PdY25GMO92/Ndtp+rPp/f91Fm/98p/2VOMi3Ix1a6Zt0aKudcjkobZCSjecqWlEgDgqZ+OVVr3x
; 8OyaTjx49nGj7y/XA0iYOdg1HRE3+/efPmzP9gTW68zMxN6vGjoqNoxtczuIDmASbKo5WIlyT6NkFt
; 6MzZM7riCcI6P0p+RN+FfcfC5lJcKiTbelX2ynNXSySFyG1DFy5doDq16yjHUtBSBHuJucg2vzn8/F
; DcFJQtk2gXvgeNHsmeAtdLuXOxgKM+GkWZ6ZmFQwASA4hB7jwSPD/++GPWQNkkzctym9CEfAGAODiv
; 0DGVZxbds4Bz7dDRQxT0SpCJuQhHGPwibVq3Ye51qSGJM/7fvcR71KVrF3XlGJW6ffv25TZt3MRBlA
; lNIc3ds6h3i70eyzJK9ebCq/nxIUpXrVqlT4xaQSwgBOgaaRlptGf3Hnr//ffJw8uDbOwt2rRYFb2D
; n+Ldd9+lm3E3rdrSoFhOmDSBxRPA9eVdytO4seMkI7NyDIsBZh0wYIBWy8jA5XfqIhRgfjH1C7p65S
; on1uhZC3IurwX5gT8OkF8NP+sKIhQAuWvgUC0LB+cHHEtaKmks/pbfTl3opo1tav2G9ax3T35/wwKF
; biENEK/fsnWLMeFECVnmAxHJbdu3Ubdu3WjLT1t0J62gt9Lg4MGazeL/B/OChQoQKqPAAAAAAElFTk
; SuQmCC
; thumbnail end
;
; 

; external perimeters extrusion width = 1.10mm
; perimeters extrusion width = 1.10mm
; infill extrusion width = 1.10mm
; solid infill extrusion width = 1.10mm
; top infill extrusion width = 1.00mm
; first layer extrusion width = 1.10mm

M107
M190 S60 ; set bed temperature and wait for it to be reached
;TYPE:Custom
;Begin Start GCode

;set temps
G10 P0 S210
G10 P0 R170
G10 P1 S0
G10 P1 R0

G28 ;home all axis
G29 S1 ;enable mesh


T0


M116 ;Wait for all temps

G90
M98 P"prime.g"
;End Start GCode
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
; Filament-specific start gcode
M703
M107
;LAYER_CHANGE
;Z:0.5
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.5

G10 ; retract
G1 Z.5 F720
;AFTER_LAYER_CHANGE
;0.5
M800 F"layer"
G1 X142.509 Y136.88 F10800
G11 ; unretract
M204 P800
;TYPE:Skirt/Brim
;WIDTH:1.1
G1 F1200
G1 X144.109 Y136.108 E.35183
G1 X145 Y136.007 E.17768
G1 X185 Y136.007 E7.92415
G1 X186.732 Y136.402 E.35183
G1 X188.12 Y137.509 E.35183
G1 X188.892 Y139.109 E.35183
G1 X188.993 Y140 E.17768
G1 X188.993 Y180 E7.92415
G1 X188.598 Y181.732 E.35183
G1 X187.491 Y183.12 E.35183
G1 X185.891 Y183.892 E.35183
G1 X185 Y183.993 E.17768
G1 X145 Y183.993 E7.92415
G1 X143.268 Y183.598 E.35183
G1 X141.88 Y182.491 E.35183
G1 X141.108 Y180.891 E.35183
G1 X141.007 Y180 E.17768
G1 X141.007 Y140 E7.92415
G1 X141.402 Y138.268 E.35183
G1 X142.416 Y136.997 E.32212
M204 P1000
; printing object Shape-Box id:0 copy 0
G10 ; retract
G1 X146.743 Y141.743 F10800
G11 ; unretract
M204 P800
;TYPE:Perimeter
G1 F1200
G1 X183.257 Y141.743 E7.23368
G1 X183.257 Y178.257 E7.23368
G1 X146.743 Y178.257 E7.23368
G1 X146.743 Y141.893 E7.20397
M204 P1000
G1 X145.75 Y140.75 F10800
M204 P800
;TYPE:External perimeter
G1 F1200
G1 X184.25 Y140.75 E7.627
G1 X184.25 Y179.25 E7.627
G1 X145.75 Y179.25 E7.627
G1 X145.75 Y140.9 E7.59728
M204 P1000
G1 X146.716 Y141.009 F10800
G10 ; retract
G1 X180.984 Y141.991
G11 ; unretract
M204 P800
;TYPE:Solid infill
;WIDTH:1.10883
G1 F1200
G1 X182.562 Y143.57 E.44621
G1 X182.562 Y144.986 E.28308
G1 X180.014 Y142.438 E.72028
G1 X178.598 Y142.438 E.28308
G1 X182.562 Y146.402 E1.12063
G1 X182.562 Y147.819 E.28308
G1 X177.181 Y142.438 E1.52097
G1 X175.765 Y142.438 E.28308
G1 X182.562 Y149.235 E1.92131
G1 X182.562 Y150.651 E.28308
G1 X174.349 Y142.438 E2.32165
G1 X172.932 Y142.438 E.28308
G1 X182.562 Y152.068 E2.72199
G1 X182.562 Y153.484 E.28308
G1 X171.516 Y142.438 E3.12233
G1 X170.1 Y142.438 E.28308
G1 X182.562 Y154.9 E3.52267
G1 X182.562 Y156.317 E.28308
G1 X168.683 Y142.438 E3.92302
G1 X167.267 Y142.438 E.28308
G1 X182.562 Y157.733 E4.32336
G1 X182.562 Y159.15 E.28308
G1 X165.85 Y142.438 E4.7237
G1 X164.434 Y142.438 E.28308
G1 X182.562 Y160.566 E5.12404
G1 X182.562 Y161.982 E.28308
G1 X163.018 Y142.438 E5.52438
G1 X161.601 Y142.438 E.28308
G1 X182.562 Y163.399 E5.92472
G1 X182.562 Y164.815 E.28308
G1 X160.185 Y142.438 E6.32506
G1 X158.769 Y142.438 E.28308
G1 X182.562 Y166.231 E6.72541
G1 X182.562 Y167.648 E.28308
G1 X157.352 Y142.438 E7.12575
G1 X155.936 Y142.438 E.28308
G1 X182.562 Y169.064 E7.52609
G1 X182.562 Y170.481 E.28308
G1 X154.519 Y142.438 E7.92643
G1 X153.103 Y142.438 E.28308
G1 X182.562 Y171.897 E8.32677
G1 X182.562 Y173.313 E.28308
G1 X151.687 Y142.438 E8.72711
G1 X150.27 Y142.438 E.28308
G1 X182.562 Y174.73 E9.12746
G1 X182.562 Y176.146 E.28308
G1 X148.854 Y142.438 E9.5278
G1 X147.438 Y142.438 E.28308
G1 X182.562 Y177.562 E9.92812
G1 X181.146 Y177.562 E.28308
G1 X147.438 Y143.854 E9.52777
G1 X147.438 Y145.27 E.28308
G1 X179.73 Y177.562 E9.12743
G1 X178.313 Y177.562 E.28308
G1 X147.438 Y146.687 E8.72709
G1 X147.438 Y148.103 E.28308
G1 X176.897 Y177.562 E8.32675
G1 X175.481 Y177.562 E.28308
G1 X147.438 Y149.519 E7.92641
G1 X147.438 Y150.936 E.28308
G1 X174.064 Y177.562 E7.52607
G1 X172.648 Y177.562 E.28308
G1 X147.438 Y152.352 E7.12573
G1 X147.438 Y153.769 E.28308
G1 X171.231 Y177.562 E6.72538
G1 X169.815 Y177.562 E.28308
G1 X147.438 Y155.185 E6.32504
G1 X147.438 Y156.601 E.28308
G1 X168.399 Y177.562 E5.9247
G1 X166.982 Y177.562 E.28308
G1 X147.438 Y158.018 E5.52436
G1 X147.438 Y159.434 E.28308
G1 X165.566 Y177.562 E5.12402
G1 X164.15 Y177.562 E.28308
G1 X147.438 Y160.85 E4.72368
G1 X147.438 Y162.267 E.28308
G1 X162.733 Y177.562 E4.32334
G1 X161.317 Y177.562 E.28308
G1 X147.438 Y163.683 E3.92299
G1 X147.438 Y165.1 E.28308
G1 X159.9 Y177.562 E3.52265
G1 X158.484 Y177.562 E.28308
G1 X147.438 Y166.516 E3.12231
G1 X147.438 Y167.932 E.28308
G1 X157.068 Y177.562 E2.72197
G1 X155.651 Y177.562 E.28308
G1 X147.438 Y169.349 E2.32163
G1 X147.438 Y170.765 E.28308
G1 X154.235 Y177.562 E1.92129
G1 X152.819 Y177.562 E.28308
G1 X147.438 Y172.181 E1.52095
G1 X147.438 Y173.598 E.28308
G1 X151.402 Y177.562 E1.1206
G1 X149.986 Y177.562 E.28308
G1 X147.438 Y175.014 E.72026
G1 X147.438 Y176.431 E.28308
G1 X149.016 Y178.009 E.44619
M204 P1000
; stop printing object Shape-Box id:0 copy 0
G10 ; retract
M107
;TYPE:Custom
; Filament-specific end gcode
M106 S0 ; turn off cooling fan
G10 P0 S0 R0
G10 P1 S0 R0
M140 S0; turn off bed
;Drop the bed
G91
G1 Z10 F1000
G90
M0
; filament used [mm] = 356.10
; filament used [cm3] = 0.86
; filament used [g] = 1.06
; filament cost = 0.03
; total filament used [g] = 1.06
; total filament cost = 0.03
; estimated printing time (normal mode) = 1m 33s

; prusaslicer_config = begin
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = G:\\Rancor\\Rancor\\PrusaSlicer\\BedModel.stl
; bed_custom_texture = G:\\Rancor\\Rancor\\PrusaSlicer\\BedTexture.png
; bed_shape = 0x0,330x0,330x320,0x320
; bed_temperature = 60,0
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 3
; bottom_solid_min_thickness = 0.8
; bridge_acceleration = 1000
; bridge_angle = 0
; bridge_fan_speed = 100,100
; bridge_flow_ratio = 0.9
; bridge_speed = 22
; brim_separation = 0.1
; brim_type = outer_only
; brim_width = 0
; clip_multipart_objects = 1
; color_change_gcode = M600
; complete_objects = 0
; cooling = 1,0
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 1000
; default_filament_profile = ""
; default_print_profile = 
; deretract_speed = 0,0
; disable_fan_first_layers = 1,1
; dont_support_bridges = 0
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0.2
; end_filament_gcode = "; Filament-specific end gcode";
; end_gcode = M106 S0 ; turn off cooling fan\nG10 P0 S0 R0\nG10 P1 S0 R0\nM140 S0; turn off bed\n;Drop the bed\nG91\nG1 Z10 F1000\nG90\nM0
; ensure_vertical_shell_thickness = 1
; external_perimeter_extrusion_width = 1.1
; external_perimeter_speed = 25
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 45
; extruder_colour = #FF8000;#0000FF
; extruder_offset = 0x0,0x0
; extrusion_axis = E
; extrusion_multiplier = 0.96,1
; extrusion_width = 1.1
; fan_always_on = 1,0
; fan_below_layer_time = 100,100
; filament_colour = #FF8000;#FF8000
; filament_cooling_final_speed = 3.4,3.4
; filament_cooling_initial_speed = 2.2,2.2
; filament_cooling_moves = 4,4
; filament_cost = 24.99,0
; filament_density = 1.24,0
; filament_diameter = 1.75,1.75
; filament_load_time = 0,0
; filament_loading_speed = 28,28
; filament_loading_speed_start = 3,3
; filament_max_volumetric_speed = 15,15
; filament_minimal_purge_on_wipe_tower = 15,15
; filament_notes = "Affordable filament for everyday printing in premium quality manufactured in-house by Josef Prusa";
; filament_ramming_parameters = "120 100| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6";"120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = PLA;!Off
; filament_soluble = 0,0
; filament_spool_weight = 0,0
; filament_toolchange_delay = 0,0
; filament_type = PLA;PLA
; filament_unload_time = 0,0
; filament_unloading_speed = 90,90
; filament_unloading_speed_start = 100,100
; filament_vendor = Prusa Polymers
; fill_angle = 45
; fill_density = 15%
; fill_pattern = grid
; first_layer_acceleration = 800
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 60,0
; first_layer_extrusion_width = 1.1
; first_layer_height = 0.5
; first_layer_speed = 20
; first_layer_speed_over_raft = 30
; first_layer_temperature = 210,0
; full_fan_speed_layer = 0,0
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 30
; gcode_comments = 0
; gcode_flavor = reprapfirmware
; gcode_label_objects = 1
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = duet
; infill_acceleration = 1000
; infill_anchor = 2.5
; infill_anchor_max = 20
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 1.1
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 30%
; infill_speed = 50
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]\nM800 F"layer"
; layer_height = 0.5
; machine_limits_usage = time_estimate_only
; machine_max_acceleration_e = 1500,1500
; machine_max_acceleration_extruding = 1500,1500
; machine_max_acceleration_retracting = 1500,1500
; machine_max_acceleration_travel = 500,1250
; machine_max_acceleration_x = 500,500
; machine_max_acceleration_y = 500,500
; machine_max_acceleration_z = 100,100
; machine_max_feedrate_e = 60,60
; machine_max_feedrate_x = 180,180
; machine_max_feedrate_y = 180,180
; machine_max_feedrate_z = 15,15
; machine_max_jerk_e = 25,25
; machine_max_jerk_x = 6.7,6.7
; machine_max_jerk_y = 6.7,6.7
; machine_max_jerk_z = 1.7,1.7
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100,100
; max_layer_height = 0,0
; max_print_height = 601
; max_print_speed = 50
; max_volumetric_speed = 0
; min_fan_speed = 100,100
; min_layer_height = 0.07,0.07
; min_print_speed = 15,15
; min_skirt_length = 4
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 1,1
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_T0-{filament_preset[0]}_T1-{filament_preset[1]}.gcode
; overhangs = 0
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 800
; perimeter_extruder = 1
; perimeter_extrusion_width = 1.1
; perimeter_speed = 35
; perimeters = 2
; physical_printer_settings_id = Printer 1
; post_process = 
; print_settings_id = N1.0 0.50mm SPEED
; printer_model = 
; printer_notes = 
; printer_settings_id = Rancor
; printer_technology = FFF
; printer_variant = 
; printer_vendor = 
; raft_contact_distance = 0.2
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 0
; resolution = 0
; retract_before_travel = 2,2
; retract_before_wipe = 70%,70%
; retract_layer_change = 1,1
; retract_length = 0.5,0.5
; retract_length_toolchange = 0,0
; retract_lift = 0,0
; retract_lift_above = 0,0
; retract_lift_below = 600,600
; retract_restart_extra = 0,0
; retract_restart_extra_toolchange = 0,0
; retract_speed = 40,40
; seam_position = nearest
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 0
; skirt_distance = 3
; skirt_height = 2
; skirts = 1
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 20,20
; small_perimeter_speed = 25
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 1.1
; solid_infill_speed = 45
; spiral_vase = 0
; standby_temperature_delta = 170
; start_filament_gcode = "; Filament-specific start gcode\nM703";
; start_gcode = ;Begin Start GCode\n\n;set temps\nG10 P0 S{temperature[0]}\nG10 P0 R{if temperature[0] == 0}0{else}{temperature[0] - 40}{endif}\nG10 P1 S{temperature[1]}\nG10 P1 R{if temperature[1] == 0}0{else}{temperature[1] - 40}{endif}\n\nG28 ;home all axis\nG29 S1 ;enable mesh\n\n{ if current_extruder == 0 }\nT0\n{ elsif current_extruder == 1 } \nT1\n{ endif }\n\nM116 ;Wait for all temps\n\nG90\nM98 P"prime.g"\n;End Start GCode
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = 0
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.25
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.7
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 2
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0.4
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 40
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 50
; support_material_with_sheath = 0
; support_material_xy_spacing = 80%
; temperature = 210,0
; template_custom_gcode = 
; thick_bridges = 1
; thin_walls = 0
; threads = 32
; thumbnails = 128x128
; toolchange_gcode = ;T[next_extruder]
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 1
; top_solid_infill_speed = 35
; top_solid_layers = 4
; top_solid_min_thickness = 1.2
; travel_speed = 180
; travel_speed_z = 12
; use_firmware_retraction = 1
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wipe = 0,0
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 170
; wipe_tower_y = 140
; wiping_volumes_extruders = 70,70,70,70
; wiping_volumes_matrix = 0,140,140,0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
