; generated by PrusaSlicer 2.4.2+win64 on 2022-05-19 at 02:52:02 UTC


;
; thumbnail begin 128x128 14580
; iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAqfElEQVR4Ae1dCXxM1/cfSQhZrEmE2E
; NssQWtrZS2aitF1V5Li7baonbaInTT4q9VO7WVau1BLbX+EFtIrUUsERHElkWIuGf+73snb7yZeW/e
; ezOTkjY3n/NJjDfvvXvPcs92zzEYDAbSAUzn9Tbg5uZGRfyK0O5du4k9YURPSHEwYTx69Ii+nfwteX
; p68u/nypWLggKDqGu3rrRl6xZKSUmhjIwM4WLT9eL3yIHx8NFDOnLkCIVPCKda1WuRZx7TM91yuZG7
; mzvlMuRSXAe8V/Xq1WnturWUnp5Ozg4m/Ny8dZMGfTKIChYoaF67SiGVaNVvqwjr8uSJ/OIpzR8fpz
; 5IpYSEBLp65SrFXonFfTUj3mnkmyGXgcLCwig+Lp5IwJ01EbDMIf47+X4yvdPjHXJ3d7e4T548eahS
; pUpsYvhE9tfxv+hR+qOnC8D4Kjq6+vQg5QHt27uP3h/wPpUuUZpyu+cmDzcPEIPddcifPz8NHzGcbt
; 26RY6OJ+wJ7d27lxrUa0AeHh78vnk981LnTp0pJiaGHj9+TEo0Lof8xxmP6eiRozRsxDCqWq0qFS5c
; mPLlzUf5vPJpIgDXIV4CQCYW9/Gjx6oTwEexsbFUq1Yt8nD3sCZKlsstF3nk8WDNWzan+Qvm082bNy
; njcYaJsBwlAskAMteuXct6dO9BAf4BlCd3Hs7xSnMD0po0aUL79u8jvcIIEu3bb76lwKKBTyVe8SCa
; 8cOMp9JOZlgzDQYkxLnz56jnOz05whXe959HvghePl60eMlisyizJ7pxzY7tO6h4seIWyDe/p5sJcu
; fJTcWKFaOhQ4fSwQMH6UHqA3J2iGsL0X7rxi1aMG8BtWvbjvL75n86HzeTZJPOD+8x7f+mUXJKspZn
; 0JkzZ6htm7bm7S63R25q2qQp515wvR6Rn/YwjRYtWUQlgkqo4cFqLxP2OTd3N9agYQPy9vHOMuTzxR
; IWLahEEB0/dpwJk2NqCyRICzZvzjyWN29eJllsa2Iwc04ezzxUr149mjx5Ml2+cpnv8Xo4Uo6ruEQR
; 8AAJc+HcBZo+fTrVrVuXvLy9ZIkAyOz4Vkc6c/aM4nPSH6fT4kWLKbhcMN/n8b1CBQvRmFFj6Pbt25
; zr5d5b7v3wz6tXr1Kfd/vwLVIDLiRiOZc7xA1buXIl3b13l9ZFrKPKVSpnNRGwFq1aUFJSEt/77CLj
; CWMp91OoV69elMnxuIddKQVCwHZTqEgh6t6jO/2x5Q/+LC3It3tB5vaCyx4+fEhRx6L43l+zVk1ZQq
; hYsSKt+HUFv9b8DOHnWvw16vdeP/L18TXhQHjX6tWq06aNm3RzPa6HYly5qi6cmRZJUHBYm9Zt2MWL
; F7mGyTlOUB7OXzxPPXv11EpNesCMOPc87jT287H8uXIKjjWlx8XFsfr165NHbg/tW1SmxAksFkgLFy
; 6kJxnKC+uoFYH1wj69c+dO+nDgh1S8eHGzEofn+/j60MCPB1J8fDzn6s2bN1NYzTCzXuOVz4v69u5L
; V2Ov6lb0ICnGjB2jJrVt1wsmjmBmsKlTp1JKagp/sHSAK+8n36e5C+byPc3FRGCGQoUK0Y5tO7gmL0
; 6eSYYUORhHjx6loKAgzfeHaA2rE0bbtm/jXKWgbDqtMuIWQC70hdu3blPEhgjq1KkTBRQN4ATo5uFG
; L9R7gXr37k1FihQxS6nSpUrTgvkLKC0tTRfX41lRUVHUpGkTG6mjCerWqctg+0I0KT0Y42G6YCMfO0
; Kvt3jdvE85yPWKXFu7dm2KT4jHezA1TgSRYN+0UMQUAOZO/wH96fr162QHcS6wF54OrKW4nvh9JfYK
; zZs3j6pVq2bxbrlz56YWr7eg6Ohorgvo4XrgbNbsWeQX4Oc480F0gFq1zD/jSQZ3TkDUOLAlqIpriM
; I+vfrAWSHL9TbvI1D/6NGj7b5LueBytHTZUr69aF1YICw5OZmbniA0PEdJEdM6oIDOmjnLRoqWKl2K
; Dhw6QI8eP9Ks6IkDmv5X33zFHWsOM6SSXSk38B4nTpygZk2b2ThlnEW+CILWzLBHpz9KV9+PBQa7e/
; suvdL0Fe6tkz4P5mDbdm3tat9yGjTW4+SJk9S6VWvugYPH8ffffuemnFZGsbin8HP58mXq0a0HeXl5
; yc45uHwwLVi4gB6kPbD7fgpzoB07d1DdF+rqwclTSUwaByY/Z+4cKh5U3K4TRPFBOq4tXbo0nTpxij
; LSM1QXAe5k7IEVgiuY3ysgIIAmfz+ZK2QKi2ZDWOB6iNSF8xdSmVJlLLY5/A1JMmTIEDoefZwepj3U
; 5GCCxFy7Zi2FVglVRU6+fPmoT98+3FwV35F0jBs3btCHH33IlIjMoMSMWm4uaN3UrXs3EuxvrYgngz
; 4nkgWhwLPXomULupFwQ9NCQ1GF+ePv70/wX+z9317Fa5W4HrZz3159ycfbR/E9gURvb296qdFL9MMP
; P1Ds1VhRWaXHTx6bzVhwfeLtRBr66VCu3GpdBxCwYEayiI0RNsq4lgEmhalZIaSCHJPKM6O9G4IrIi
; IiqFLlSnoVP6bxGuuXYlKuC58YzhUjLQMLtnv3bkpMTFS8Ro7rsWibN26mGtVqaBKh4sLid9GiRalb
; t260e89uup90nxMB4MCBA/RSw5e4godrEVSqWqUq9+xJ76G0bgULFuR6FojIkQH3b4eOHaS6kbIkVr
; rJ3bt3adjwYTy44WLEyyFf9nswkzZt3uS0P1+J6+/cuUNjR42lIoUdVqI4YKGrVq1Kn437jMLDw0V3
; NYdigYI7eMo0unP7Dq3+fTWVLVOW+wasiM0GQbim2SvNKPJgpEPKZ2pqKk2bPo0FBgbax4nMYtHhw4
; e5KDU7MVyLfNKCfJFTEDWECaWGVD3Ih7Q4cvgINWvSjAd2nEG+BeQymBGLtYMUOBh50OzRA1y6eIne
; 6vAWJxpcI8zR7rrB1/HjjB8V9Rl788Y4EClIo8YvyeKSSyLpl+CEQPACSlQWKHpM42c2L9mjRw/umt
; aKZOkCSD8DAh48eMAjayWKl9AzR10A62H40OF8O5IzHxGg+vGHH5mfnx8DYtS2V8+8ntS5S2cu2rUi
; X/pvmPojRo6wkOZ4bqsWrUwEgOtjLsZQ+/bt9dr3jop8Xd+HZgulS6soVBL5iKV3ebsLd7k6g2AlAP
; djr9+wbgPXLex59CAVoo5GUcMGDc1bghpBVqlShX77/Te7Pg0lyYj5r1+/nqqGVuVb3uRvJvOcBwNe
; 8teVv3IzR4ei5wzidYeY8V7lg8vT/n377RKBEtcDGdh/K1esrNd/oRkQb+/ZvSdduXxFsx8ff95OvE
; 2jho/S/F6+vr40aPAgntWjNne5AYvu1MlTxDJM2ViGDz78QG/Y16WKntZ7ISXrtVde4wumtrDSBUZy
; iDStSgq96wTRxw1LG308HScKcG2pEqVozuw5fHvR48fHR/HX4rmTCPPT+kwQC3S0Xbt3KcY1tA5DFn
; n05JDvdHKJYFaxkSNGasoiEsfhQ4cttHJAeT8vWtCpmnHPBy9ywN/4zIH3oeavNqfo49H607SE67dt
; 2UYVK1R0WBcRdDWGfEmYoI4Og0bEulzDdwiE2L+nlyct+2WZqFypUj588DNmzDDv+29VDyQR8VLY1L
; eOEf+n9V38CvvRhHET6N7de7oTNpLuJfFkDztpWlrXmetscHmfOHmCHBkGrQ+yB+4e7qI549Rerwpu
; JgiuEEznLpxTxb/ooUt7lEbDP/2YRjcLNsohXwrT21U2Bvp6Ks9VkJiI4W/ftl13wgaujT4WTQ3rN7
; SOXTiEfCkEBwfT4qWLeYBIzzAYtHGyIkIav9KYrd2wlglUyDI9X1lLBIIUQCJIl65dKDUtVXWCcMve
; jz1D+z59RRX5UmnQqKytCxdu4gH9BpgTOvSIfMQPfvrxJ66BS9LLnUa8FGAt9evfj7u1nSUApoIE8i
; ngQ2MnjKUbt27wCSelJNF3U75j8MdnCeIl74U9M2+evDRt6jRVn3nMb1M1I94aRAWRB4PKlqNlS5bZ
; zZtQUvRiL8dSx/YdpRnNjsxb05riXWvXqc1T35ChpJcAVB+EQE1ozVC2eftmJiyG1KRhPJ99316eiJ
; kF5pZN0ie8ZIcPHpZ1FadcPUdHv+zhMPKlCuI7bV6ls2fP6lb0YH6uW72ORxedcDo5pEAjCDVu/Dju
; 7tZKAKoPyZ03N737/rvsUuwlcxavjZKDEy2JN2nIp0PIx8fH5Yi3JoLGjRvbmIZxO1aQs4iXwn5h+7
; i6/Rd6nJoki3g5RQ/vNOijQebTRc8CuJXSvDkdPnJYkXANmpAviPwSZUrQwmULWXJqsnnC1r+tqX/N
; mjVUuVJlZ6nf7jWQNEMGDeGi+fGDZDo1e7jRlciXQvTUD4wPb8dbIN963kg2jdwfyRVFJxQ9l5jNIp
; QsWZKnjiFAJEcAdh/k5u5Grdq1YtGnouG+tEjTUloE00oIsYXUNPr+2+/1BpU0LwDS2HFcK79Pftow
; 82var0PRc0YaJByIkJ03fPxwsRbIX8AliHMlIJcDafFw+ctJAFmuL1ikIH39/dcs8U6iJq6XcAbXlN
; 9//32e6eIA8jVfDy4b06x8liPeGv5eHG6ExOHzFXbD83+fpxbNW+jy6DlC9M5CaLVQWrN2jfkAq6FK
; 5So2F0HRq12vNtv1v13sUfojC0VPbs+TDphHSL1Ghq+KIsh0L0Bmbj/eL2++vBQS4Esre9T8x5EvAp
; TMhCN/0vJly6l4YHHVRA8da+EKULwnooLI9UCCr+HC+QuEQ4+ispLXOy99/OnHLO56nIWip4Z8fIwk
; kgnhE/jpU50TU78uE/keeTy4rbtj+ija88GLxmcNf37QwNilVhA5EU+wmTsyh5xIvdcEYE7kCfBwMJ
; IN5s+fTw1faki/rv6VWadlS38rIR957dA4xbQnV1CqGTI9gEElg2jB1Il0aELXZ454a4AH0ZF4ghSA
; dBwLW750ObVp3caR0Lx+SSIiEdwu7AsWhzS1IB8RsLnz5lLJUiX1Ilm7yHfPRW3eaEN753/5XHC9Eu
; iIJ9jMG8mmQ4cM5WnuPN39jkmaFixU0LETP3oIwFq8a+V6HJzo2bOn+TizTmolLcgvUKgAfTtpPB2f
; Neq5RbycNFDYEmyIXsx1WL92PT15/MSipgEcT9v/3E41w2pyvSdLCMB6X7eHdHFAg1y/YT2Fhoba26
; uc5vo6devQjtVLKXJMu2yDfKk0sIon2MwbIr7z250pLjbOnKAhN67GXaX+7/c3HUHPCgLQw/XIcxs5
; aqTebGEy6OB6z3yeNHjIYDo694tshXQ5EOIJNgoiTykPKEqzZ86m9IfpmiqZIMq3bPkyKlu2rGqZGl
; 0gIl3NvIOfPzIykh+KcNCxY/+aTK4vG1yWVsyaQofCnz9Fz1GQJpxA+3658ct0IvrEU65XQT7WHmFt
; fr5w1izX5jSSxnEv6R692/dde8hnznA9jk0j8zVy8XfPtaLnKGBL6F6nFE0YPYonhGitX5TBMnhULy
; k5iY0aOYoXi3IR8vWdDcS4f/8+d3WK59o1PUCF6wFF/IvQjP/7jqKmf5KtkOoIRE9535h2K14V+Swz
; mSU9I52b2PXr1XdlhPUpbvSeuoFmumf3HmpQv4GS50uXogdnxJ7ff9aVsJHdQYwnKA2JyGczfpxBhQ
; sVzrIzDIaE6wl2izUqDRRbQBQO9qsurs9EvrevNy8Lc3zBhGyFPFeCNJ7AuV74wYlicL1gYrP27do7
; 4ljTJJF5NnPJUsyA2nt/bvvToZp6CMGu+n0VhYSEaEN+JtdXqlKJ1i+aJZh3bbMVwrICEE9IPL7bzP
; WIvaxft55KlyztbN6gIvIF85Mhm/l41HHh3wJHFi5SmGe4mpUTHQOWw7m/z1GXzl2UXZcSPz7OwB/9
; Zdq/UtFzFLAlxP75C928FksfD/zYlUkkNkzp7+fPxn8+nmczQ88wiP8B5Lz22mvcPNEqDaRmI+IJSH
; oUK1xKuZ5X5yoeSD/PnUlHvn03WyHnn4Sfe7xoDCrolSXIh/UWViuM4SyCtCqMwZpTkT0yd85cevhA
; uQqGks8ANz508JCpZIu7m1nko7DU/5bkcL0W0Hs+QQvX+/r4sgHvDaBr167ZpIYZ5G6CWDtCxHBRWk
; sDLa5i1NYd89kYKl6yOH09+Ws6Njv7+PGfF7ATT9AMcNMHlwtmSxcrF8kyKH5Z4GAUPYhYH8GDFOyJ
; fU+h9UC84MLRPTmKnhOgdD5BgestOF9wGLF2b7SjM6fP2C3/Z1C7ef6C+WnE8BFMDFNqHZcj5uaIfB
; eBygFWG5EPPQwOu+SkZNUj9aoEgAd45PagRg0b0aHIQ6oKoqvy8XPAEhQOsForeqxBvQYMfQ60lP+D
; RDdoViYEBTEwMJCmT5vOCwvIEYGr8/FzwBIkCqKNyEe538GfDKabN27qqilk0CpWREAJ9g7tO1DM+R
; izNMjqfPwcsATpAVbEBypXqsxW/7ZaU2k5qR4H3cCgpkzIAUy78hXK08oVKynx1KF/JB8/BywB0qBZ
; xaLUtXNXXvrGnqInN5BfMGfeHAsC0J1kMLRZSLZatH8jnF74hVHuyJoS1+PPK1ev8MKfnrk9zQSgC/
; nWFTZy4NkClG4o33KIlyIfRTfXR6ynkAohvAmW6RCLzoxTpQobOfBsAdswlHDzaSUrrr995zYNHTaU
; fL19xe5nVLlyZTIUKFyAxwHUDiLADoXykZ0W5b8IOMCalvj0ACvCywePHKR6L9ajPB55TP0PM3MLWr
; 7ekgwxl2No9drVNHLkSGrUqBEVKFCAV88EleDwJS5sUdE/h+uzEYgJJ2gSOXXaVPIv4m+BTxF4hpGY
; epQZi6aEGwm8l83YMWPp5SYvP5ODlzngGlj0blNjEW8vs8iXle58jxB+pB27QBT3Lp+mg2OzXz5+Dl
; jCyh61jC+VLay8vcuZDTl+/H8XwGeAopiy8QQp4nP8+P9ukD3AKiI/x4//3wCbhBMg//yB7bTlvbrZ
; aiI54Dhs71/X2Lhcpl7w6OEjOvrH7zS+eQXj0q41stVEckA//Ny5unFAvVLGiv6Z6fy93unFcwDXL5
; tH4W1rGqe8Udm4Y8AL2WpSOaANvm1V0RL5AO4gEBwCqClXoVxp6lU/2Ahp8HvPWtlqcjmgDOt6hxk/
; bVzW+Fa1QKOvp83ZTiuzQIgN1CtdiIa9XM44963QHGmQzWHGm1U419cuoVi6Tt5BEJg/L/V7saTx29
; aVjBv71s5Wk84BE9ePahrMub6Il91aQ8oBoLwebtQ8xM+YoyBmL4DkBtc3KF3IqCHCqx4CLl0oH33U
; sDRXEHPMxecXYN5NfD3E+EmzKsaebZtr6qxuXwJ45qWmTZtSw0YNqWB+b2pbtWiOgvicAkT+xw3LGK
; d88LYx9f593lYHTbC/+vorqla9Gs/l1EwAiBejz86PP/xIKQ9SeFgRnabCJ4RT11fq0XBhb8lREJ8f
; mCpIZoj8P1fMz4zm0dP0fWY6t4l+yv0H9OeNucHYknoDlsjHIULUsEGzJXNLlMwbsseMd/TeGbGGvu
; rxao6C+IxBVPQm9mxhTIy33yUEEV7gEv2I0dG8c+fOvPexBQEUKliIRo8czTtN2rREYeYb8fEg+T5F
; zAg3ftM+jCuIOdLgnwVR0Vs5bbyRHBjALwp6G8TMkOqh1WlTxCbdjZBijh+g77s3yVEQ/yGAovf5q+
; WNg18NNf599AA5OwzYC3DQA1U/9bZEEceD5Hu06tvhXEFc0b2m8Vkv0r8VRD/+ovBPHeJ6WQKABKhR
; vQZduXJFN+ItrhN+Tv9vK016M8w4s0PVnC3BxSD68fdH/KaKi9SUVN7DQDMBIB7Q771+vOOFI8iXjr
; sJcfTLF+9zBTHHXHQeRD9+17CSxgO7tNVyioqKokmTJtHlS5e50s4VeAVcGtDDDqnC3vm8aemypTw5
; 9ElmMQBycKQJCuKOxdPpmw61cxREJ0Dqx0fafscOHSktJU2VAHAAZNnSZRRcPpjee/c9OrD/AHucLq
; /bma0AEEHJEiXpSNQRhsqU0iRRLUOOYC4ej6QZA97gCmKOuagdlPz4SNfHuf+H6Q+V8UCmLG9cs/Dn
; hVSgYAGW2zM3NXqpEWfwxJuJvLGVDQFkWgOsdZvWdO/ePdIyzl84TxdjLtq9BtJg408TcxJONIJdP3
; 5m+fw/d/xpd80zU/3R7ocmTJjAG0ah3Lx7bnfyD/TnHVd27tzJez2IBGA+G4i8gPDx4RZUojTQlHDI
; kCE0bNgwiv4rmvfoZRL5JD2bBmkgmos5W4ItwLyDotenTgnLhA1JmF4suoV+TCjUqWWXhhfwzfZv8u
; +JFdsM7qb71K1blxOAzcFQUNmWrVs0bQM4cwavkiBq+IlTtCxNTkkmJlNSCNIACmJOPMESVBI2bKQA
; OHngxwN57Wbpvi6rtwmfXLp4icLCwp4SgJZgEAIIaFSghcquxV+jli1b8hOnggRhNWrVYNBC8f209D
; Sbe+xf/TM3F3PiCU/9+NUCfbVE7szSAD0VVq5cyYtx2WtkzWlAMAn379tPxYoVk2s/I/8QeAd79+7N
; A0FqxQfw8JgLMVS+bHkmKJOmBs+CdYGmEuhtv2LFCrp586bFd65fOM0VxP9qPEFHwoYioHnE2TNnVQ
; kAAzicOXMm5c6TW3s4GL2Afv75Z96oQI0I0Gxq48aNvD26BSG5mbp7lipVijeSBCWihSle+IFJQTT+
; 18xFnQkbigDTEN3FtCrt6PnQq08vUQowVQIAFwcVC6ITJ05oqhqKX99P+d6iZrDoZxAPJ6IObq2atW
; j69Onc+wj3c0zUfyOeICZsQNErUygfOYN8EYFw5U+aOElTfSDgMO5aHNVvUJ9JOpyqU9nrzV/n1afk
; kG/9WVJSElcK1eoNwCzBUfTu3boTqmPfjI+j378ZRv/WeMJvgtKLhI03qgQY87i7tikkWsVv2rxJdR
; vg/r0Mxo4dPUalgkqJTKn+AOQIfP755+Z+s4wpVA3NzBuA8lerdi1Nrc5AKJAK5cqVY8OHDadl0ybS
; xHa1/lXxBIcUPR0AKdCkSROKvRprV1KLf2c8yqBlS5YxHy8fbQQAKJi/IG8Vh3r2dt3EmUSwY+cOXm
; VUQwkaJhABg9IJYoBLukndGjTyzQbZPp6gy7xTF/dMjQgGfjjQVOT7iTLyReaFf2Dw4MHaCQAQVjuM
; ocKUFqsgLS2NuyJ98vuYbM9cihOz+bxOnTq0e8e2bK0gioreJ51bUuOXGlOlkEpUMqgkeXl5ESqvWm
; yRLuoM6uvrSwvmLzB1IyP1YB6KgWglADMFIrgA6tFSihRE0PfdvrwGkYwDwgb5qFI+aPAgunHjhvke
; Ug9idlAQxYSNMe0bGK+cOUEZjzN4RA79AVG7F2IaXtPFSxbToEGDqEGjBrxhh9lTp4Pr5aB8ufKmln
; TM0iOrxKhaCMDiJdAjaMGCBZoLEwKZguRQpXL0C0Rfe7my5vAgbhKkwfMeT5BN2BATNGUWH4D5xl+P
; p42bNnLiL1OmDII+zjSGZILSztDJXW3AbW/QwvXWUKJkCTp8+LAmLyGuOXb8GG9EIXcvlKXv1LmTpm
; qXkAbwID6P8QRzwsZG9YQNuTWCRIWSfe/+Pdq0cRN1796dCuQv4FC3MJjh48aPwz2Z2nMNWrjeGvBS
; KCCVkJCgeYLzF85niBdI78P7Bf40g28pWgekwaIx7z038QRR0dOSmas2zAzATGt27tw5bn0V8SuiSZ
; kW/0ZUF17YtevX8qaT9oZBD+KlgKghegijxZm9Ie4/D9Ie0KhRo8zNDxs3aUxHo45q0iWkC3Th4gXW
; vUd3alDO75kfYBUTNsz5+A4Oe8oa1gdu9C8nfUnFg4rLKdQ2khoMCtMd8RxuGtoZBi0i3wYyQ5Pobf
; /rb79yRUduUhaVqYXw8u3E29ShQwcaM3YMTz3XM9CiTqBoVrFSRU5EvAGzr+czOcAqzce/eu4UOTM0
; Z14JV507f44GfTqIfAv4iozElBgY65PPKx/16d2H0h+lmw+JWD/ToJfzLUCIK1etVpUHgqwnJTcxRK
; W4BfFYO9fjNtcTrrOhw4cyH18fqfnE31k8wDq6WfA/oiAq5eOL0xV/Q1o5kVUnvxbCDyq67Nq1iwlb
; MAOXq+kIiOfMnz+fnqQ/MSmjVmqWQXDFMsV+fxoAShxcv4gaZi6Ay2YN//a+A/tYg4YNyGqyNgSb1Q
; dYRT8+8vGP795i8Z6QTkjQEBBDS5YuIbR7nfL9FJo6ZSqvvrJ161b668RfPAiGPdmZNeLfFb4Nhw9C
; 7oLtz9Tc7qVKlqK/ov+S9RIa8FJzZs/h3UAcJQIcPIQyh8RDV4279+7SlGlTyM/fT9o02a6kgjSAr9
; 3V8QTRj4+Dl4hgYoA4T548SePGjaM6L9Sh/AXy83WQQwYIF25XwcRjnd7uRFOnTqXTp0+boqJPmEN9
; GqHhg/Bw5q9CSAU5P4sZEI197dXXZLddQ+bNKOpIFL9IjZoUgPn7+fOegc4OvMvps6dZ+w7tuaJpLf
; K1QPVivlxBdEU8wfrgJd4PjpzevXrzpAzRgaMl7sHBzSQ18d1mzZrRzB9nUkJ8Au/MpsWPL/03z/0T
; CPHUmVPUolUL07vIPBM1gpGsM+6zcdwhJU3bsygUeef2HRr3xTieyKGXCBBebNiwISUmJpKjQ7AU2C
; 8rfmFIdBAVPYM+j5j5WiiInWoU4woilDZHFD1r8+7O3Ts8ydLf3//pM3MZ9Llyra4H4ZQsVZJGDBtB
; V2OvOtTIG4Rw49YN6vx2Z8Vm0yACSKmNmzeKqf+2BIABZ8S2rduoZo2amiclxvyRtjz006GKTQrtTQ
; ARxA8GfsB95Y5wvdy11gqiVmkgp+gdOXKEmjdvzqWSXubQApizn58fd+DEXY2DoizL9fbWEAyMDqFK
; UhySp3pYdXbxykVlAhAHqBGnhZBSrGWx+QOE+DJcxTh+zN9Xo6pz7do1Bukh4XqnkS+FYH9fGtm8iq
; qCKHfwEqnTs2fP5oqUq95HkZEy5y5YVgyRV37ES6e+eP/eferWtRtXmmXfS5A+8DJiXnYJAAPBHCFu
; TKVLldY8MVAfOlFcvnjZFJWyI9JEcxEWRNeuXU39hl2IeECRIkXom2++oXghionj7EoKopwf/9KlS9
; SjRw8lJnAp8iXf5d/39vKm7l26s2tx1zSf8xMH4i9oDy8pEW/xTjAN582bZ3IFq90M9iyqg7R9o61U
; G1clgp7delJKUooiAVj7CuLi4qhGzRouRT4Qh/Bo2oM07nvA48R4wg+CF0/cEuT8+FD24OQKCAzQ44
; 93FvlP1zCXG4Pi9vLLL9PRo0d1+07OnD1DtcNqK74TvIrRx6LVCUBEEnLQcSypcOHCmiYEETRr5iwb
; V6+ckwj/FuxjtnffXgoICNDMJWoAxAX4B3ARLtVLxPMJX7YMsevHxxm7/Qf3U8PGwvbk4VwjZx3If+
; rNy9StIIEjIiJIz8Caou9zAV+Z+oCZntxGjRuRAWJeDfnigMmxd89eql+vvvqkhAf4FfWjyIORUi8Z
; UzJpMEDlM3+aST4+Pkpc5xCHQXHr1KkTXb1qec4B5xM2zJtKdhdS+Ll+4zoNHzPclNziouQNPcQMUR
; 7gF0Dr1683batMHfn4jdPe3bt2t9atzETAibpLly505fIVG2XDntaZcD2B0KYUGrvii4tU9lIjik+I
; 52nj1ve3eYawXaQmp1Lf3n3llBhnxCtfgOBywbQhYoOuAJQ40GhxXcQ6qhxa2VFfidPzCSwWSFu3bO
; WMiGZQjFRwJvzrQswFKl++vCxDQcIY3ARTCQGWVatWiQcMNGkcEKmrV62mChUqqBLBsBHDWGpaKmUw
; 00vbewYo/M7NO3zvcwXirSFf3nz8PCNser0aNvShmEsx1LN3T2an7JpLuF4JUOXr5KmTPAoLe56piA
; MQC85uKhIt2sbhDy9vL/ro44/YrVu3SOvAAp4/d97kgJC3j/lEffP70roN68zNqdQWHoQIu7tYYDGX
; Il8ELEbdOnXp0KFDuluugniTkpNo9vzZVLxEcYcSNqzXRw/geW3eaENJqUmqyBezkU6fOc1T8GXvuX
; zZcvN/wgzDyVP4l/VwB+xVBEAkCpwNlUNSIJyZGQwhtUUGESxZsoQrMVxUZQEhFCxYkAdt7OlBSgPz
; iIoW3OctX9OqIDJnEC8FWDdTpk5RzfgRCQA2f5PGTeSlwKMHj9j4L8ZbmHhIUvz6m691ZeoAYYgFNG
; 3alMlwBZ/w22+/zQ+O2H1nCXXAKznok0Gu2nNlAboGjlchJc2RIN2txFs0ftJ4fqJao+LqnFTL3Far
; Va/Gbty8oe5sE/4f/v/Ro0aTh7tM+zhQCBII32j7homScz1dmBYtW9DZs2c1LwyQl3grkcaOHstTlK
; 1f3jOvJ037v2mKx5gsEkgE0Xzw0EGqWasmf/GsIgAAEFeiRAla8esKi3fTow9t3bGVatauKTqzXINs
; O0SAtYQOpiWSiGls2rSJvPLJKO3iRTEXYyi0eqhFyhEWBsmcixYvMp8KUkMcBq7dvGkzCw0NtXkgzJ
; k9e/aY7sfkv5+cmkyTv5tMfoX9ZDteZhXAQ9a/f3+6eeum7pg9Lr8Sd4UGDByA9HanFD0tAKk44P0B
; piJQGt40cn8kN68N1tJIvAAifOeunVz8W8eWsef07duXJz2oIV/62eXLl3lKEhZWej/4/RECtfZuIU
; Dx9/m/qXXr1ry1ud2Ol1m3sCBctnvPbofMxZTUFLZk+RIqE1xGDBFnjSIrrEvTJk3pYdpD9ZcSpATC
; /YjyZm6nzEYC8OsEsQsfsZx9jy+Co7ds2SLmtNt16ogDCsiihYuoRFAJ872wvQwaNIilpqaar8cR9G
; XLl/Ggi9jaPKuUPztgXhhfH18e+hUQqmsLxG8QzonTJ1i7Du2UgjJOA6QzGCk5OVk9ViD89+HIwzxQ
; Z7AmSOtrkWUCxUtp8WExfPbZZ8z6TLo9kQnCQkpSq1atzBSInHecCkbCIg5GQPTm88xn5nrUrxk9Zj
; S90vQVfvoVZVGyUhk0yHAqFONmTZvx7B095qK4FvA1fDftO57V5KS5aAnYot0N1LFTx6cJn3bxz+iP
; zX8wuzqAdCB1CLamTPCH7234vMnLTej48eOKCaByQ1A22ZeTvmQoSo37oWjE/HnzqVpoNXNrc0ifDz
; /6kGLjYk1+A0EpizoWxeveo6IpEkOli+mihWX2OA1VtZFYKacHqUlBxBP27N9D9RrWs1YQHXof0QrA
; +cLPP/tc0zlN4R1Y+KRw/h0bV7bsl4SfcxfOUZXQKsrJGbm4a5Kh7AikhtoQFwYI3bVzF49UYXEB4H
; gAChsuX7mcUtJSZF2d2E4iD0XSR598RCEVQ7jVAhELyGLpwE/bIM6OCttKW6A9JFy7fo2GDB9C3r7e
; LpEA0NWQaGp3ZGYBpySnULNXm8nnDSp+V6AsRKCKBhRVokj+GWrOdO7Sma7EXiE15Iv3/evkX/Tiiy
; +a7wUvYse3OtLJsyYXp1p1MhAHvHHr1q2j9/q9xyN+UDS1hqul768HQKxwaG3+YzMTT9zoIQTEE1at
; W0UhlUOcIlhkXvXt09du5hV/p0xHUHR0NIlSVzMBsMyEwzlz5lgnRNgsHCYTEhJCa9assVu2DAswd9
; 5cuHi5ogeuR37d1OlT6W7SXU1uYuuB591IuEG/LPuF2rRpwxNAVESt0wkb2EtHjBiB2jzMkfc9F3OO
; uvToIi3YpPmdsNaNGjSiuNg4u7kW4t9QSHEKWVEZVXpRkbDvC7HzPn36aHo52JmDhwzmOoT0JfAnji
; ghFUlq3kErBdHg2Bi42qmB5KPHT3hNvOnTpnPlDcfNzbXxcrkE+VJEMITFcbxNbzwB437SfZoxZwYF
; Fg9kmvSYzL0fKeioDKbF9kfw7fTZ09yyUnyGvWoS4rgWf4292vxVTUoMDia+8OILLDLSlAcAxQkh2I
; ohFWXNO1QO41XKHciGtRmZIo8yTO7PU6dP0efjPqeq1asynWldNlxvUNgSUBUNBa+06EFktc6QsIej
; DlPTV5vajSfAEQax/1rz13hfB60EByJr27qtfZPafFyI2Xfq/H3ub6pSpYpmLkGG66QvJ/HQq6+3r6
; JTB1Jj+S/LVfMHHR3IQ4CEgZMLYdGyZcqSzUmoXJqRL0sIEK9vtnuTO760bAnW64yU7rHjx/KSOtYW
; DpBXuEBhGjN6DMmd+VfSQSBRJ0+ZzM8H2sVZt27d4LalpPtJigkbUMpgzmzYsMGmDqC9xeFaPtKacr
; nbNdegP5w6dcrlZ+ms5sMjeGiatHX7VkLTbH4ayt1gvU3IzUd168D8kLq1evVqbSXbrAYcYZu2bqJq
; NatxSQtmgWlcI7QGof6iHNcrKSB4PiqQQB9Se2+0jIF4ZMgamTBxAp05dQZHvCxuDAKAggYNPfzLcP
; Ly8SI9i6MFUGoWxac1D43HqWy+ljkXLBJyHxYuXEjt32pP3vm9pVnJDodu0ZJt4MCB/IAM01CmxeLd
; BCRfjr1M/Qb041p773d682RZuaF0P9wD1hEksJb3/X9cEjxyoaIcuwAAAABJRU5ErkJggg==
; thumbnail end
;
; 

; external perimeters extrusion width = 1.80mm
; perimeters extrusion width = 1.80mm
; infill extrusion width = 1.80mm
; solid infill extrusion width = 1.80mm
; top infill extrusion width = 1.80mm
; first layer extrusion width = 1.80mm

M107
M190 S60 ; set bed temperature and wait for it to be reached
;TYPE:Custom
;Begin Start GCode

;set temps
G10 P0 S210
G10 P0 R170
G10 P1 S0
G10 P1 R0

G28 ;home all axis
G29 S1 ;enable mesh


T0


M116 ;Wait for all temps

G90
M98 P"prime.g"
;End Start GCode
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
; Filament-specific start gcode
M703
M107
;LAYER_CHANGE
;Z:0.9
;HEIGHT:0.9
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.9

G10 ; retract
G1 Z.9 F10800
;AFTER_LAYER_CHANGE
;0.9
M800 F"layer"
G1 X142.885 Y137.079
G11 ; unretract
M204 P1000
;TYPE:Skirt/Brim
;WIDTH:1.8
G1 F622.332
G1 X145 Y136.393 E1.28345
G1 X185 Y136.393 E23.08795
G1 X186.64 Y136.788 E.97365
G1 X187.921 Y137.885 E.97365
G1 X188.607 Y140 E1.28345
G1 X188.607 Y180 E23.08795
G1 X188.212 Y181.64 E.97365
G1 X187.115 Y182.921 E.97365
G1 X185 Y183.607 E1.28345
G1 X145 Y183.607 E23.08795
G1 X143.36 Y183.212 E.97365
G1 X142.079 Y182.115 E.97365
G1 X141.393 Y180 E1.28345
G1 X141.393 Y140 E23.08795
G1 X141.788 Y138.36 E.97365
G1 X142.709 Y137.284 E.81781
G10 ; retract
G1 X147.707 Y142.707 F10800
G11 ; unretract
;TYPE:Perimeter
G1 F622.332
G1 X182.293 Y142.707 E19.96316
G1 X182.293 Y177.293 E19.96316
G1 X147.707 Y177.293 E19.96316
G1 X147.707 Y142.977 E19.80732
G10 ; retract
G1 X146.1 Y141.1 F10800
G11 ; unretract
;TYPE:External perimeter
G1 F622.332
G1 X183.9 Y141.1 E21.81811
G1 X183.9 Y178.9 E21.81811
G1 X146.1 Y178.9 E21.81811
G1 X146.1 Y141.37 E21.66227
G1 X147.839 Y141.566 F10800
G10 ; retract
G1 X178.477 Y143.189
G11 ; unretract
;TYPE:Solid infill
;WIDTH:1.8406
G1 F606.997
G1 X181.088 Y145.8 E2.18523
G1 X181.088 Y148.13 E1.37876
G1 X176.87 Y143.912 E3.52994
G1 X174.54 Y143.912 E1.37876
G1 X181.088 Y150.46 E5.4798
G1 X181.088 Y152.79 E1.37876
G1 X172.21 Y143.912 E7.42967
G1 X169.881 Y143.912 E1.37876
G1 X181.088 Y155.119 E9.37954
G1 X181.088 Y157.449 E1.37876
G1 X167.551 Y143.912 E11.3294
G1 X165.221 Y143.912 E1.37876
G1 X181.088 Y159.779 E13.27927
G1 X181.088 Y162.109 E1.37876
G1 X162.891 Y143.912 E15.22914
G1 X160.561 Y143.912 E1.37876
G1 X181.088 Y164.439 E17.179
G1 X181.088 Y166.769 E1.37876
G1 X158.231 Y143.912 E19.12887
G1 X155.901 Y143.912 E1.37876
G1 X181.088 Y169.099 E21.07874
G1 X181.088 Y171.428 E1.37876
G1 X153.572 Y143.912 E23.0286
G1 X151.242 Y143.912 E1.37876
G1 X181.088 Y173.758 E24.97847
G1 X181.088 Y176.088 E1.37873
G1 X148.912 Y143.912 E26.92825
G1 X148.912 Y146.242 E1.37876
G1 X178.758 Y176.088 E24.97836
G1 X176.428 Y176.088 E1.37876
G1 X148.912 Y148.572 E23.02849
G1 X148.912 Y150.902 E1.37876
G1 X174.098 Y176.088 E21.07863
G1 X171.769 Y176.088 E1.37876
G1 X148.912 Y153.231 E19.12876
G1 X148.912 Y155.561 E1.37876
G1 X169.439 Y176.088 E17.17889
G1 X167.109 Y176.088 E1.37876
G1 X148.912 Y157.891 E15.22903
G1 X148.912 Y160.221 E1.37876
G1 X164.779 Y176.088 E13.27916
G1 X162.449 Y176.088 E1.37876
G1 X148.912 Y162.551 E11.32929
G1 X148.912 Y164.881 E1.37876
G1 X160.119 Y176.088 E9.37943
G1 X157.789 Y176.088 E1.37876
G1 X148.912 Y167.211 E7.42956
G1 X148.912 Y169.54 E1.37876
G1 X155.46 Y176.088 E5.47969
G1 X153.13 Y176.088 E1.37876
G1 X148.912 Y171.87 E3.52983
G1 X148.912 Y174.2 E1.37876
G1 X151.523 Y176.811 E2.18512
G10 ; retract
M107
;TYPE:Custom
; Filament-specific end gcode
M106 S0 ; turn off cooling fan
G10 P0 S0 R0
G10 P1 S0 R0
M140 S0; turn off bed
;Drop the bed
G91
G1 Z10 F1000
G90
M0
; filament used [mm] = 681.18
; filament used [cm3] = 1.64
; filament used [g] = 2.03
; filament cost = 0.05
; total filament used [g] = 2.03
; total filament cost = 0.05
; estimated printing time (normal mode) = 1m 56s

; prusaslicer_config = begin
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = G:\\Rancor\\Rancor\\PrusaSlicer\\BedModel.stl
; bed_custom_texture = G:\\Rancor\\Rancor\\PrusaSlicer\\BedTexture.png
; bed_shape = 0x0,330x0,330x320,0x320
; bed_temperature = 60,0
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 3
; bottom_solid_min_thickness = 0.5
; bridge_acceleration = 1000
; bridge_angle = 0
; bridge_fan_speed = 100,100
; bridge_flow_ratio = 0.95
; bridge_speed = 30
; brim_separation = 0
; brim_type = outer_only
; brim_width = 0
; clip_multipart_objects = 1
; color_change_gcode = M600
; complete_objects = 0
; cooling = 1,0
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 1000
; default_filament_profile = ""
; default_print_profile = 
; deretract_speed = 0,0
; disable_fan_first_layers = 1,1
; dont_support_bridges = 1
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0.2
; end_filament_gcode = "; Filament-specific end gcode";
; end_gcode = M106 S0 ; turn off cooling fan\nG10 P0 S0 R0\nG10 P1 S0 R0\nM140 S0; turn off bed\n;Drop the bed\nG91\nG1 Z10 F1000\nG90\nM0
; ensure_vertical_shell_thickness = 1
; external_perimeter_extrusion_width = 1.8
; external_perimeter_speed = 35
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 45
; extruder_colour = #FF8000;#0000FF
; extruder_offset = 0x0,0x0
; extrusion_axis = E
; extrusion_multiplier = 0.96,1
; extrusion_width = 1.8
; fan_always_on = 1,0
; fan_below_layer_time = 100,100
; filament_colour = #FF8000;#FF8000
; filament_cooling_final_speed = 3.4,3.4
; filament_cooling_initial_speed = 2.2,2.2
; filament_cooling_moves = 4,4
; filament_cost = 24.99,0
; filament_density = 1.24,0
; filament_diameter = 1.75,1.75
; filament_load_time = 0,0
; filament_loading_speed = 28,28
; filament_loading_speed_start = 3,3
; filament_max_volumetric_speed = 15,15
; filament_minimal_purge_on_wipe_tower = 15,15
; filament_notes = "Affordable filament for everyday printing in premium quality manufactured in-house by Josef Prusa";
; filament_ramming_parameters = "120 100| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6";"120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = PLA;!Off
; filament_soluble = 0,0
; filament_spool_weight = 0,0
; filament_toolchange_delay = 0,0
; filament_type = PLA;PLA
; filament_unload_time = 0,0
; filament_unloading_speed = 90,90
; filament_unloading_speed_start = 100,100
; filament_vendor = Prusa Polymers
; fill_angle = 45
; fill_density = 15%
; fill_pattern = grid
; first_layer_acceleration = 1000
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 60,0
; first_layer_extrusion_width = 1.8
; first_layer_height = 0.9
; first_layer_speed = 20
; first_layer_speed_over_raft = 30
; first_layer_temperature = 210,0
; full_fan_speed_layer = 0,0
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 40
; gcode_comments = 0
; gcode_flavor = reprapfirmware
; gcode_label_objects = 0
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = duet
; infill_acceleration = 1000
; infill_anchor = 600%
; infill_anchor_max = 50
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 1.8
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 85
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]\nM800 F"layer"
; layer_height = 0.9
; machine_limits_usage = time_estimate_only
; machine_max_acceleration_e = 1500,1500
; machine_max_acceleration_extruding = 1500,1500
; machine_max_acceleration_retracting = 1500,1500
; machine_max_acceleration_travel = 500,1250
; machine_max_acceleration_x = 500,500
; machine_max_acceleration_y = 500,500
; machine_max_acceleration_z = 100,100
; machine_max_feedrate_e = 60,60
; machine_max_feedrate_x = 180,180
; machine_max_feedrate_y = 180,180
; machine_max_feedrate_z = 15,15
; machine_max_jerk_e = 25,25
; machine_max_jerk_x = 6.7,6.7
; machine_max_jerk_y = 6.7,6.7
; machine_max_jerk_z = 1.7,1.7
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100,100
; max_layer_height = 0,0
; max_print_height = 601
; max_print_speed = 200
; max_volumetric_speed = 0
; min_fan_speed = 100,100
; min_layer_height = 0.07,0.07
; min_print_speed = 15,15
; min_skirt_length = 4
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 1.8,1.8
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_T0-{filament_preset[0]}_T1-{filament_preset[1]}.gcode
; overhangs = 0
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 800
; perimeter_extruder = 1
; perimeter_extrusion_width = 1.8
; perimeter_speed = 50
; perimeters = 2
; physical_printer_settings_id = Printer 1
; post_process = 
; print_settings_id = N1.8 0.9mm SPEED
; printer_model = 
; printer_notes = 
; printer_settings_id = Rancor
; printer_technology = FFF
; printer_variant = 
; printer_vendor = 
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 0
; resolution = 0
; retract_before_travel = 2,2
; retract_before_wipe = 70%,70%
; retract_layer_change = 1,1
; retract_length = 0.5,0.5
; retract_length_toolchange = 0,0
; retract_lift = 0,0
; retract_lift_above = 0,0
; retract_lift_below = 600,600
; retract_restart_extra = 0,0
; retract_restart_extra_toolchange = 0,0
; retract_speed = 40,40
; seam_position = nearest
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 0
; skirt_distance = 2
; skirt_height = 3
; skirts = 1
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 20,20
; small_perimeter_speed = 30
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 1.8
; solid_infill_speed = 80
; spiral_vase = 0
; standby_temperature_delta = 170
; start_filament_gcode = "; Filament-specific start gcode\nM703";
; start_gcode = ;Begin Start GCode\n\n;set temps\nG10 P0 S{temperature[0]}\nG10 P0 R{if temperature[0] == 0}0{else}{temperature[0] - 40}{endif}\nG10 P1 S{temperature[1]}\nG10 P1 R{if temperature[1] == 0}0{else}{temperature[1] - 40}{endif}\n\nG28 ;home all axis\nG29 S1 ;enable mesh\n\n{ if current_extruder == 0 }\nT0\n{ elsif current_extruder == 1 } \nT1\n{ endif }\n\nM116 ;Wait for all temps\n\nG90\nM98 P"prime.g"\n;End Start GCode
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = -1
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.1
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.38
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 2
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 45
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 55
; support_material_with_sheath = 0
; support_material_xy_spacing = 50%
; temperature = 210,0
; template_custom_gcode = 
; thick_bridges = 1
; thin_walls = 0
; threads = 32
; thumbnails = 128x128
; toolchange_gcode = ;T[next_extruder]
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 1.8
; top_solid_infill_speed = 40
; top_solid_layers = 5
; top_solid_min_thickness = 0.6
; travel_speed = 180
; travel_speed_z = 0
; use_firmware_retraction = 1
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wipe = 0,0
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 170
; wipe_tower_y = 125
; wiping_volumes_extruders = 70,70,70,70
; wiping_volumes_matrix = 0,140,140,0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
