; generated by PrusaSlicer 2.4.2+win64 on 2022-05-18 at 18:58:16 UTC


;
; thumbnail begin 128x128 10864
; iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAfm0lEQVR4Ae1dB1hUV9NeuoCAFBFBuq
; ioiL0buxEldmMvUT4TY435jBqMLZZgjH+MGvWzRqMxYknsiZrYomLvUdBYQASRIr247/47Bxd2ly13
; 796lxJ08Exu799wzc+a8U84ckUgkEksZPFmfzxaxuZk5xoweA0ORREqvX7/G2dNn0bxpc5iYmECIcf
; Nht2puWLduHXJycrSOm8acnp4u3rplK7y9vPnNrbk5uod0x9VrVyEWi0s8Q1TWwpexdSVr/LD5B5WD
; 1EZiDR8i4WdkZOCrxV/BsYojhByzLkxK17lTZ1y/fl3jO9J4ld+LlOXmjZt4r+d7TKB8nu/l5YX1G9
; cjKzsLfBVAUIGrYh8fH1y9ehVCCJ8mkv7p7p276NG9B++JE4Lt7e0xd85cpKamQhfBy1NBQQFSklOw
; fOlyVLatzOW5EuW/s7KywqjRo/Do8aOiZ3JVALHSrwZbJe92fhc5mVLzKOYneBnl5+eDTKdnDU8Ycs
; zauEFQAxw7dkznVa+KaEv44/gfbDXzHY+piSmCgoJw4NABSV5+HkQ6fFis5veCsrWVNebPmy+VIL0x
; dBK+5A2RyZw8dTKsra1hqHFq40qVKiEsLAzx8fHQV/BEmZmZ+Hrp13CwdxBkfPQ9M2fN5KQAYi1/Fp
; rFZDL/PPEnLzxARCtl44aNqFy5MkSGHatKJqvz47YfmRUSQvjR96LRs0dPmJqa6js2hW1BCr7FIo5C
; L00Wi0xFqBVYC7GxseAySfKTKaPcglxMmDxBiEnjzGZmZggNDcW9e/fUKq+qsaqj3Nxc7NyxEzVq1B
; BifJIS81z4q8q/LFs2ke5VFqYYPmw4mwRNJl/d5L0Wv0ZiUiJatWsFkZnhx+zk5ISlEUtBHoc60mXV
; JzxPwH/C/mMI8KokY+lqc67mDDd3NzU/UHZsY2Mj3rJ1C3Lyc5hAuQpfbpJx69Yt+AX4GVQJmjdvjr
; NnznLesjQJn9A+bX/169UXIl4hUS/4N9z9ve64efcmov+JxvtD3y/TIIkqTXWv7o4r168oCF4XM0q0
; a9cu2NnZCT5GqYJi6uSpePHihdpn67LqM9IzMG/uPNja2hpsPktwSnoKezitsNSMVKz+32q4VHUpDQ
; FzGqilmSU6te/ETKuugn8z6cjKysLCBQthZmom2Dhr+tfEnj17GODkOA6xpjFSoKdD+w6aMIuE51xq
; tugKA5H+R+Dp4rWLeKfjO0ILVmfhE5Pfam1pjfCZ4ZK8nDzwITKryUnJ6N65u95KQHvy+wPexz8P/+
; HtpcgTuawb/rcBrq6ump7LVfgSnYSvrAAyyn+dj8TkRITPDYeNrY0QguUlfPmXcnJwwuGDhwvjA3zm
; XfqZG9duoGatmrzxAAlp9erVnOL47JFaNCT2aSyGDhnKvIdSmsuSrG6QzHTmZeHwscOoU7eO0APkOl
; gFzW/YoCHi4uKgDx397SjsHHTDA4SLyDxfuXxFkIgexQcOHTyEmjVrCjF/2oGeJtY24LzXeXjy7Ak+
; CPugNDVVIlJl9sxFGDR4EHMN+RDhHFLqpd8s5fwuBB4/n/U5UlJS1H6vLkAvNSUV0/87nUUKBRQ8P+
; HLK4C2iUt7lcZCkRbmFvoOXNtg1e93JoUh1tVrVoPi2HyItrek5CSMHDlSqxLUq1sPRw4fESyOf+ni
; JbRo0aI8eVraFYBtBdIU4pHfjiAwMNCQwle96lWwh4cHzl8+zwArH6J3SkhMQFBgECxMSyo0Zc1Gjx
; qNuFhu2422VU9eyLf/9y0cHR2h57sr/5z+MRtNA6e9KvGFFAzOCTeUbyr/Yjp95t2QdzWmV7UIDJE/
; R8LXyxcmIsXV6O7ujs2bNiMvT72F0cXkP4h5gD69+wixffJxA/kpAL0T7bOXrlxC+47thXgQL00lU6
; nSXEq3AjNLM8yYNYO5eLpQ0oskTJk4BVUcqih8J/nfId1DWP0A1zi+JuHn5eYhclck19StLvPDzb3j
; qwC0V9HK+n7t90IFhHgNllZMQO0AVsXSr3+/kitIGsJ2cHBA5O5IvC7gFow5c+oMWrVoVRRfr2xlBj
; c7K1SpUgWLFi2i8itO36Nt1b9IfIGPx38MCwu98RJnk69syXgpAJm9mAcxGDRkkBBAhRfQo+daWlqy
; Mfzz+B82ruzsbHz33XdwcSmpkPUC6+Hpo6fSaI96gVAuPWJxBKpVq1b0Xg3d7XFoTFPJ4bBmkt/XLh
; YM6JGSBQcHCx3H1zifjvaOcHFwYbWVvBSABk6TtPfXvfDz99N34LyFT2a4evXq+H7d9ww4KROh6LZt
; 25b43Huh7zElUUX37t5Dr569GLCT/fykNt6SU+NbKPC9HxZI8rPSeQmeiELVixYuKtUaBFIysmgXzl
; 3ArRu30LVzV+Yl6aR8BPTin8dj6rSpsLSyNOSANYIYMpcdOkqDLdeuaJpn5o/PmDFDoS7OytIKa9as
; UVjFhA2oJMzXx7covl7TxQY/D29YQvgyvrxouCTp2kmdhE//dOf2HXTp0sUQtQdqF5KtjS2mTZmGxM
; TEonwEbWHz5sxjlpIz6Dz912k0b9HcoIMVaVn19g72CP8iHCmpKeBCNOkUSatTu07RSnB2dcbFqIvs
; 3+KfxSNsTBjsKhdH/EY39YA6wcvzX9M6S+JO/FTCGqijK1euMLdUgPlTnku18xlQMwC/7vtVVitRYk
; wnjp1Ao+BGbCvVag2qOFYxpPA1rnoCY/WD6uPosaM6o3kiqhgaPnw4zC3MYWpuilZtW7EMXYMGDYpW
; AIG8jQODJFyEL8/Xl4+XZCc90zoGsqA7f9rJ0ta6vDuPuWQCHfL+EJaI0jZfiQmJGDd2HKtI1mKZDC
; J4jRNAWkl71QdjP0BcvH6xfQKuGzdthJubWyGAlNvGuteuCl0Fr2wNYk/8pHUMtAofRD9A9646Zxs5
; Az3Xqq5Ys3oNw0Zcs5C0NWzfth1+Pn6aKosEF77GqBatTE8vT2zZtoVzVk0bXb96Hc2aNFN4zqxOfh
; J9hK9sDbhsCeT7L4tYprD18Fkg8kyrt2P7jrh29ZrGIlNNFH0/mh0qoSppFVuCYILXygT0QnqG4M7f
; dyAE0epfu3otq8KVvZg2oKePNZABRE1Eq+7i+Yto0rCJuv2X89Zgb2ePL8K/QHJyMufCE3WUlZmFhf
; MXwtbKltVY8FUA3kDPydkJSyKW4FX6KwhBjx89xtDBQ1lZluw5qtw7ofnBruUK1kC+RE3eW0hLScPU
; SVOVk2ecCzaC6gXht6O/MSXXt/AkPy8f1y5dQ4umLWBuaq63BdBJo2nvady0MU6dOaW3Fsvol72/sA
; CQvHvHB+jxZXIXM57e1zrOgvwCHPz1IHy9fTnPJ2GjsaPHsmIRPsBYnlhIPytX/N1yaRCtios6fGKY
; VU/mj1bnxMkT8SLpBYSgly9f4tOpnyoc8hzQwA2nxreQlDa/AYhasQFZh9gnsRjQdwDhH43bp6eHJ7
; Zu3sqwkb6rnpTv8YPH6NWjFzttpeG5vISvcdUT0POv6Y/IPZEas2q60Lm/zqFdm3YKcfxF3WtJykL4
; 8kwAMeeldndRChDFa1atgVMVJ5XzRQdYKaDEF+gVkVRv8rLzsHfXXvh4+nAJDwu76slX7T+wPx48fA
; AhiEK833z9Daq7VS8Rxy9r4ctbg+fnDhSNWTmKKMMG7JyCNGTbplWbIiBG1ixiSQRevXql9xZJSbHk
; F8niCR9OgG0lW24hYRVn5nkDPUq2rFi1guUVhCByX/r27qtQPlUaQI8vUz6hICtda+l6ZnomPp/xOV
; q0bIEzp88IYiXJwpw7fQ7B9YJhaaFDSJ+OGzdt3FSbtmiN47dt1xZRl6IEKZWmlbBj2w5We881jl9e
; WD6foO0dKZSr76oXvxYjOyMbixcsRhW7KrrnI+hL4uLixOM/HA8baxudVz0VTX428zMkpyRDCEpISM
; D4ceNZCFP2nLICevpsCRRB5JpP4EsE9KLvRqNrR2kW0JJzkalioE62P5EZ2rF9B/x8uaWDCYwF1g3E
; oSOH9HZXZHTi+AlmjWRxfAJ6K3oHVhjBKzPXfIKuRCIjoLdt8za4V3NX5dvrZgHkv/je3/fQr3c/ib
; pqFtoqKLc+YtQIPI19CiGI0pgL5i5AVZeqRc/RN45f3qyBUERAL+FZAkYNGwUbKxv+lUCqFEAW1aLi
; huXLlsPFWbECh1amRw0PbNi0QW0Bhq506+YthHQLYd6D7DlCxvHLkzXQd0vIz8nHid9OIDAgUKjy/G
; IFUC54JLN+/tx5tG3dlu31ZPK7duuKG7duQAii8OSGdRvg5ell8Dh+ebIGXACiMrF2canpCJ8RDjsb
; O+VYvv4KoOnULR19nj93PubOn4u0tDQIQRTmHDV8lEKpOdeCjX8DK+cTNFHB6wJcunoJzZo1g5WFlX
; CCV7UFqCVxobshBB3cfxBB9YOKgF5px/HLC3PNJxAu27t7L7OUggufswIIQNTjbsZ/Z8DJsTgUWtHc
; O6FZE0BUrkN8/M9j9A7tLWiPg1JTAKrV6/BOB4U4/r8R6PFlru4iFZys/HYlqtiXKOPjf2oIBiTKan
; 33f9+x41byQK88xfHLC3MFiGQYrl2+hpbNWuoLBsUGVYAHDx5gQL8BCs0ay3Mcv7wwV4CY/iqdbal6
; A0MITOSy7Nq5C7UDapdZwUZFZ84FJ1JX/fcjvyPAL6B8KACdiZv08SSFg5dvO9Djy+ryCapc9ufPnm
; PY4GH8joY9efoEQtCpP0+hZfOWCnH88lCwUdGZa8EJBdY2r9+Mqs5VOQmeMJm3pzdE/rX9sf/Aft4J
; HQobL1m4BNVciw9etvV1NAI9Abmw4OQgp8aYf9/+Gx3f6agxLUx5np7de+Le7XvSP5uJYG1njWnTp7
; GaO13o7zt/I7RHqMLBS6N7ZzhWdYBVFVEJOCXXVKX3Kb8TsTACWelZLMAnYv9gKmINmFq2aYnzF85r
; fQDVrW3ZtAU+3j4VrmCjorO2ghNZAIkdVT95hlVPk2UmfEBl4WdPnlU4Si8q0g4TEeuf51TVCcu/XY
; 6MTNVNj5/FPWNly3wOXhpZGNal4ORl0ktM+HCCeNpEqYVPeFmix6KoxB4htQYmFibo3a83omOiFX74
; 6OGjrFff2x7HLy9MAJGLu8jKzqjyTEn46q+MeWMNvHy9WKNl0qLwWeFwdnY2unfljPkWnMjcSZFGd0
; GqBJbWlvDx9Snqd2OM45dP5lpwotxtXaTVZzQp/r0R6JVv5lNwol0BjHH8Cseq8gnqin5E8rV4qtgI
; 9Comy/IJ2u5YEEVHR2PTlk0ljlobgV7FZy4HWEVU3UsNG0J7hRYJ3hjH/3expoIT0Y6dO1jLFpnwy9
; vBSyMLw8oHWIsUgDpsGYHe28Py+YRHTx4VegHUSs3o3r09TADx1w3LWYs+pgDVpArw5bu1JCc+bF6h
; XsTI/HhOt1oSb1dHWUi/0PxXMjdF/yA3ye6RjSrUyxiZO/8yurGkfyNPidKl2op+v7+zDVb2qWu0Bv
; 8yXt2vvqSuh7OqhpElgz9kDUY19ZAcDWtWoV7SyCX52LhmkgmtfSR2qptEag4FN6nhgM2DGlSoFzZy
; MW8fGiwhGSqfH6DOK3TQ980pLbUKIJYBxCntfIxbQgXjL7oESBxtFbuGVLKqhGFDh+Hhw4fIzs/Go9
; hHCgqg9moSGUD8cUhwhZqEt5EJ6HWv5wHlHI+Huwe7U4FugCOiyjFikUiHe2mMALF889LQuhJfN0Wg
; R64eXWZBF4Cpakgl4iJ4ZWswKLi6ESCWIz48tqlkSFMfCSXz5IEeHdCZM2eOxgZeIl2Er2wN1g+sX6
; Em6t/IBNIberko3FBGStCoYSN2T7K2zqMiXQWvbA3GtfQ0bgllxDM7B0iqOSneCEJBnrCwMDx++hhi
; Dtes66MARbihjY8jjACx9JiAXudAd4UDOTL+eMLHyMrJAlcSedXwKvYTTfhbA2M+oXSYxfGrOam9Fa
; xWYC08fvIY4NjRR5T2Mg379+1H3/59YWNno1ufWRVbgjGfYBgujON7KcfxS7J0Efft15d1FQOH454i
; maaQT/gk9gnWrl2LkB4hhRcgSr+MrINSM0KtgNHoLgrLNJe+LjaaLn5SYDoGtn79ek59m0v0B8gvyG
; dNIO9H30dERASaNW4mYb3puDUhlshbA2M+QT+mOP74Vl4SS3PdW8FQmPdC1AXdFYBIFjCgitLc3FwJ
; XY5It3UGBQUVuxua8UKRlTDmE/jxrhGNWByf73ZMrmDrVq0RHx9feCxMFwVQJlnYkNqbn/jjBP7z0X
; /g6u7KTg6pE7wyQDTmE7hzeGd/iZ2VHg2g5ZRg2tRpyM3MVasEvFrEkDIkvEjAtp3bMGjYIFlrdzEX
; gGh0F9UzAb2utVwk+gpeYd4rVcKPP/6oFg/wUgDZYYPX4teEGcSP/nkk/n7N9+jRs0dh+1cTI0DUlW
; lO3O0N0ArWVDrntf1x5+4dla6hoE2iqM3M/Yf3sWDxAjRs1FCtS2nMJxQzAT2aC8EFL8cE4IcMGMLu
; MqTew3orgFiLf0GWgYAkdRv/9JNP4e3tXQgeTUpag7c5n0DguHZVWxhS+EVKIHXnv13xLbJys5h8ih
; SAbqvSVfhisW4XA2WkZ2Dv/r3ssujq7sW3f5FCvK35hOkd/AQBerow9Xc4fea0gmxEI4ePxPoN65H0
; IokBBWUToSx88CTmSRSIkZqUyq5b79y1MypVrgQzczOmEG9LPoGAXns/p1IVvIypSKRJkyaIexZXBA
; pFly9fRu06tRFYJxBfLvwSsfGxrFxIXtZ8Vr16TSj8hfCCFDxizdo16NihI6wsrZi7uLD7vzefML9b
; gMTZxhIikajMmLbiiRMmsmt6aJtmGIBu5fT28i4yE6PHjsb5i+fZ/X+CCV4N0SCysrJw+9ZtzJ8/H6
; 0aN8H7wR6Sg2OaVCjhalv1PQNdJSKRCOWBLa0sEbk7kkV8mQKQjI8dO1Z0J6+JqQnMrczFLVu3FC9b
; vgzxz+OZoDRtD/qQLNBElJObg7/O/4WViz/H1lGtKpSgVTG5d6UF9HRhf39/3L9/v9gLyCnIwfad2+
; HowJSg8GrzN6jdxcUFAwcOxMEjB5GalspurjI0kcIlPI3FvrnjKqS7SO7dVGn009LMFCKRqPyxuYjF
; bYoUgKpHaF+e+PFEWJmrDkgQiAgICMCc2XNw/cZ1ljgyKL3ZfKL2bcHB8e0rjPDJ5OsTxy8ttjCzkF
; OANzY4JSUF3d7tpvnD0hwAIfgu73bB1i1bkZSUhIK8AhgSLsTH3MGBGQPLPUCkenw3u/Jn8tWyvPBl
; dOfOHXYrqMYPvtke6A6bGp41MG7cOPx5/M/iIkQVjQn1pez0NJzesERyfHLHcid4VrDR0FNChy/Kvd
; DlWR3K37d3HxwcdTBjUoWwrmyN+g3qI2JxBB5GP4Q4XyzYtbLy9PRmlOTA1B7lxhrQwctA1QcvK4YF
; ULna8rIx64tZMLPkd0uVvYM9BvQfgO3btuNl8kvB9wayBn+s/LxMASIBvbBWvpIqdpW13b5e8RSAKO
; llEkJCQ1Tl/TmzhbmFmA4jfvLJJ7hx4wby8vOYO6kJL2hrbSZPN4/twb4P25W68GX1+Nra7FVoBSCi
; OkGKFOrzENnqoNw0Vams27AOCS8T9BK8PD2TAsQ/lk0ptS2B6vGrOztwLZMraxbrpQBEdB2M/IWP+j
; 60eYvmuHnzJoQkGUA0pLsoO3hJisx5LkxEKusjCC/QwqAsHd38Rb+n4lszE4EvhtTXApCpppDwqlWr
; oO5Kea5MZ9c+mfaJzjeTqBmXyj1EChBxbPZgwa3Boh6BEh837UCP6vWZYKXWobIUG1DHdXKXx4wdg3
; kL5rF53BW5C/t+3ceu6jlw8AAOHD6AzZs2Y+3KtewquDEfjGEHOj08PGBlbVX0nerOAhhUAWRKIAVy
; GD58OG+k61/TH7/8+ovKE6pCCV9GZA3Obf5KkHwCi+PXdZWYStPWKoGe6RvBS91h92ruCAkJwZcLvs
; TRo0fxNP4pcvJzivCOUoJN9e/f3NFM80QXb8bGxeLY8WNYsngJevXqBV8f32IZmJaSAsgoISEBjRo1
; 0ukBNNhBgwcVnlYpZSJrEBnWlrfwyb2rXU11iRuZbgtLC3h4e2Dch+Nw/ux5pCWnKVyyLURgTFlRKI
; t39epVfLPsG7Rs1ZJ5W7yui+OjAERRF6Lg5uYm+wKNe71rNVeW7iVN1pdSU1Lx5MkTnfMQORmvJIe/
; mqTTlkDuHQE91yp2Kt+LJn1gn4HY/8t+ZGZkFj/MoHlTFe8mnde70Xex7OtlaN2iNVNIwyoAXSMvDe
; 6sXLkStpU1hzs7dOyAa9euQQiKiopCu3btUL16ddbUmswr4RJtJO9VcM0nkMnvpObgpaurKz766CNc
; v3m9cGWWssCVSVamQYU2eVl5OPnnSYwcNRKVbSsbzgLQS+fm52LkmJEwtyxpeuzs7DD7i9ksa6gvkZ
; BXfLcCVV0LL0OU7cG0rdSsWVM854s5rNE1hZ+5mFtt+QSlBopFCJ7K3idNmQTqrF5u6c3rE3agq+Zn
; zZjF5o1S+xoVIP81v4xeQmIC2rRto/Bl9evXx2+//6bwc3x9+5iYGHH/Af21+toknC5du2DL5i1Iz0
; gvXplq9EFVPkHVwUtSMlMLU/Tu2xuXr1xWKKSsCEQh+MTERISHh8PLy0v9HN6+d7swXs/DnF2KusTu
; E6Jo2AdjPsCzeO1XnGojWs1SN0ns5+fH2YzJLIOnp6eEmiNcPH8RBbmacxAEECmfoKqBIlkAHx8f7N
; m7BznZ+uOXsiTaHmLux2DylMnMLVWaO7GoT78+yMvO43SUWPGbpSw1Hgd+OYCffvpJaysSLiS1KuIJ
; EyeoCrRoO5Gs0OiKhNm4UWOsWLECDx8/VFnJFPMgBoMG9oOjvWIcn05Fjxg5gkVA/y1E2wLVeZIl6x
; HaQ7bFFc6pRSUL5lLwIrFwrs7JkyfFVLGqwtfWuX9RkWUwM4Gtgy36v98fe/bsQVpaGjvf+PPun1Gn
; Tp0Scfw6tetg997dyM3LhSGIttuy2kpkcqI2cZu3bGZnNdh7UwCjetXqrF7cUDV/mojOJSxeshiOjo
; 58hKxToWXdwLro07cPrG2sFbAFIf7Bgwfjfsx9wYtaaPURmCVLRHN85OgR7I7czdLt+/btw4kTJ1j9
; RXJyMkuU0fNJUQxRXCMfQHsQ8wD9+vWj9y/cQ4MbBeN50nO2Z5QW3b5zm0XOSjOpomxh3Ku7Y9XqVc
; jMyoRQRBbk+PHjmDdvHrp17Qa3qm5wsnOCpZll0fPlx2FdyRquTq6oE1AHQ4cNxcrVK3Hp6iV2CTQR
; YTR9I6iqoqfZWdmFCiADPlQPKM4TazxPLgRJAxjiLT9sQY0aNUpN8MpM79upYydEXY7S2/LR58m0x8
; XGYcmSJfAL8IOVrZWCC6bUZaWkYooUf9bGyga+nr4IGxuGgwcPsgigIRanSH4Q5AZRvbgha/vinsWJ
; yWMoyzy6g70DZs+ezfIb+hLNVWp6KhYsXAB3d3eDFIaQhfT38cenUz7Fzes3UZAv3FatoACUXPD29c
; bdv+8KkrSRJzJjtP/VrVeXzyRp2ut1AokNgxvi0JFDbL/VlwhQ7tm3B8ENg0ulIogsg72dPUYMG4Ez
; Z88IIiOR8kPorF5o71B2WkcoS0CtSsNnh7MoIY8XF+REDVm3MWPGsIuShHivxBeJmPbfaYXNtAwseF
; VMz+3bty+uXL1SfDs4DxKp+nLaHyO+ilAo6OQb0SPfs0OHDmW66unY26bNm5Cdmw19iSb79NnTaN2m
; tWHy8zoyJaYmT5qMuCdxyMvNE+tqFUTqvpjcsnMXznFqN6qKCHVeOHcBPl4+fF5MkFVPAaGePXvixq
; 0bgphLclm/XvY1SwoZSqA8WUx3P+7YsYOd99MlKKdWAaj6p3HjxkhMSFTIcetC1Ixg7Nix8itFLBIZ
; ZAJKMJWwUXwh9ZX+SSmi23dvsxiCvlVRhhC+vMwGDRqEuLg4hk849QnU9OXU4mXKhCnIzeYfGYuNjU
; VQoyAu1SuCnZ5t1qSZ4iEVPelp7FM0btpYe2atjASvzAS0/zwpff/cfK05HpE2QVCQgho68AVO9Dk6
; 7StXRKLqeRJdX1ITBwcH469zfwnmydD3nDp/Ck1aNhGmDKsU2MHBARvXb0R+jmYlEHH5Mi9vL94lXR
; TWpETEilUrdKum1ZPpsgTqdCq7IkVfIixEkdJJn06CpbWlXo21S4tpvufOncu2A3XESQHoYAhlkVJS
; UxQnhWPnEIqSZWRkYPr06aW6hxII7BHSA/fu3xPMpc3Jy8Hu/bvhW8u3tK0BL2toYW6Bz2Z+pjbULe
; L6RVSevPSbpXodCX/+/DnatG4jKW33qYZHDWzbtk2Q4A8RKVPMoxgMGDoAJubl/0gYzTcpQX5eSdmJ
; dPki8jlPnjop1jAxWpcZhTJl7WhKkynjN3bMWNbtRCh6lfkKK9ethLObs6G2BGG8pjcHdxcsWFDisK
; 7onbbv6JSNa9q0qZiqc3mRFJNRsikyMrJMcgEUjAqqH8T6HQuV+qbtLepaFNp2aiv0liC4y1zVpSoO
; HzmMvNd5xV3CkpOSMWv6LNhV5hampUn86MOPOIMr5QgiTVhmbibmzpvL9iehX5ILU9Us3ab1Kl23Ho
; mq6E1dLpJSkjBz7kxY21kbwhoIpgxU9EIXRpISMAWg/1F26dD+Q6gXWI/Tl9hXsccP234oTE/ywFY0
; ZUmJSQjtGQpzU3OtqVJDMO2LHdt3xI2bNwQDiHkFeTh07BBq16/N1xoYPFBG1n7EiBFFnsH/A45OtG
; mgd1QkAAAAAElFTkSuQmCC
; thumbnail end
;
; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

M107
M190 S60 ; set bed temperature and wait for it to be reached
;TYPE:Custom
;Begin Start GCode

;set temps
G10 P0 S0
G10 P0 R0
G10 P1 S210
G10 P1 R170

G28 ;home all axis
G29 S1 ;enable mesh

 
T1


M116 ;Wait for all temps

G90
M98 P"prime.g"
;End Start GCode
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
;T1
T1
; Filament-specific start gcode
M703
M107
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.2

G10 ; retract
G1 Z.2 F10800
;AFTER_LAYER_CHANGE
;0.2
M800 F"layer"
G1 X148.015 Y143.693
G11 ; unretract
M204 P1000
;TYPE:Skirt/Brim
;WIDTH:0.42
G1 F1200
G1 X149.06 Y142.817 E.04107
G1 X150 Y142.623 E.02888
G1 X180 Y142.623 E.903
G1 X181.307 Y143.015 E.04107
G1 X182.183 Y144.06 E.04107
G1 X182.377 Y145 E.02888
G1 X182.377 Y175 E.903
G1 X181.985 Y176.307 E.04107
G1 X180.94 Y177.183 E.04107
G1 X180 Y177.377 E.02888
G1 X150 Y177.377 E.903
G1 X148.693 Y176.985 E.04107
G1 X147.817 Y175.94 E.04107
G1 X147.623 Y175 E.02888
G1 X147.623 Y145 E.903
G1 X147.997 Y143.75 E.03926
G10 ; retract
G1 X150.787 Y145.787 F10800
G11 ; unretract
;TYPE:Perimeter
G1 F1200
G1 X179.213 Y145.787 E.85562
G1 X179.213 Y174.213 E.85562
G1 X150.787 Y174.213 E.85562
G1 X150.787 Y145.847 E.85382
G1 X150.41 Y145.41 F10800
;TYPE:External perimeter
G1 F1200
G1 X179.59 Y145.41 E.87832
G1 X179.59 Y174.59 E.87832
G1 X150.41 Y174.59 E.87832
G1 X150.41 Y145.47 E.87652
G1 X150.796 Y145.514 F10800
G10 ; retract
G1 X178.331 Y145.9
G11 ; unretract
;TYPE:Solid infill
;WIDTH:0.42324
G1 F1200
G1 X178.93 Y146.5 E.02574
G1 X178.93 Y147.038 E.01633
G1 X177.962 Y146.07 E.04154
G1 X177.425 Y146.07 E.01633
G1 X178.93 Y147.575 E.06464
G1 X178.93 Y148.113 E.01633
G1 X176.887 Y146.07 E.08773
G1 X176.349 Y146.07 E.01633
G1 X178.93 Y148.651 E.11082
G1 X178.93 Y149.189 E.01633
G1 X175.811 Y146.07 E.13391
G1 X175.273 Y146.07 E.01633
G1 X178.93 Y149.727 E.157
G1 X178.93 Y150.265 E.01633
G1 X174.735 Y146.07 E.1801
G1 X174.198 Y146.07 E.01633
G1 X178.93 Y150.802 E.20319
G1 X178.93 Y151.34 E.01633
G1 X173.66 Y146.07 E.22628
G1 X173.122 Y146.07 E.01633
G1 X178.93 Y151.878 E.24937
G1 X178.93 Y152.416 E.01633
G1 X172.584 Y146.07 E.27247
G1 X172.046 Y146.07 E.01633
G1 X178.93 Y152.954 E.29556
G1 X178.93 Y153.492 E.01633
G1 X171.508 Y146.07 E.31865
G1 X170.97 Y146.07 E.01633
G1 X178.93 Y154.03 E.34174
G1 X178.93 Y154.567 E.01633
G1 X170.433 Y146.07 E.36483
G1 X169.895 Y146.07 E.01633
G1 X178.93 Y155.105 E.38793
G1 X178.93 Y155.643 E.01633
G1 X169.357 Y146.07 E.41102
G1 X168.819 Y146.07 E.01633
G1 X178.93 Y156.181 E.43411
G1 X178.93 Y156.719 E.01633
G1 X168.281 Y146.07 E.4572
G1 X167.743 Y146.07 E.01633
G1 X178.93 Y157.257 E.48029
G1 X178.93 Y157.795 E.01633
G1 X167.205 Y146.07 E.50339
G1 X166.668 Y146.07 E.01633
G1 X178.93 Y158.332 E.52648
G1 X178.93 Y158.87 E.01633
G1 X166.13 Y146.07 E.54957
G1 X165.592 Y146.07 E.01633
G1 X178.93 Y159.408 E.57266
G1 X178.93 Y159.946 E.01633
G1 X165.054 Y146.07 E.59575
G1 X164.516 Y146.07 E.01633
G1 X178.93 Y160.484 E.61885
G1 X178.93 Y161.022 E.01633
G1 X163.978 Y146.07 E.64194
G1 X163.44 Y146.07 E.01633
G1 X178.93 Y161.56 E.66503
G1 X178.93 Y162.097 E.01633
G1 X162.903 Y146.07 E.68812
G1 X162.365 Y146.07 E.01633
G1 X178.93 Y162.635 E.71122
G1 X178.93 Y163.173 E.01633
G1 X161.827 Y146.07 E.73431
G1 X161.289 Y146.07 E.01633
G1 X178.93 Y163.711 E.7574
G1 X178.93 Y164.249 E.01633
G1 X160.751 Y146.07 E.78049
G1 X160.213 Y146.07 E.01633
G1 X178.93 Y164.787 E.80358
G1 X178.93 Y165.325 E.01633
G1 X159.675 Y146.07 E.82668
G1 X159.138 Y146.07 E.01633
G1 X178.93 Y165.862 E.84977
G1 X178.93 Y166.4 E.01633
G1 X158.6 Y146.07 E.87286
G1 X158.062 Y146.07 E.01633
G1 X178.93 Y166.938 E.89595
G1 X178.93 Y167.476 E.01633
G1 X157.524 Y146.07 E.91904
G1 X156.986 Y146.07 E.01633
G1 X178.93 Y168.014 E.94214
G1 X178.93 Y168.552 E.01633
G1 X156.448 Y146.07 E.96523
G1 X155.91 Y146.07 E.01633
G1 X178.93 Y169.09 E.98832
G1 X178.93 Y169.627 E.01633
G1 X155.373 Y146.07 E1.01141
G1 X154.835 Y146.07 E.01633
G1 X178.93 Y170.165 E1.0345
G1 X178.93 Y170.703 E.01633
G1 X154.297 Y146.07 E1.0576
G1 X153.759 Y146.07 E.01633
G1 X178.93 Y171.241 E1.08069
G1 X178.93 Y171.779 E.01633
G1 X153.221 Y146.07 E1.10378
G1 X152.683 Y146.07 E.01633
G1 X178.93 Y172.317 E1.12687
G1 X178.93 Y172.854 E.01633
G1 X152.146 Y146.07 E1.14997
G1 X151.608 Y146.07 E.01633
G1 X178.93 Y173.392 E1.17306
G1 X178.93 Y173.93 E.01633
G1 X151.07 Y146.07 E1.19615
G1 X151.07 Y146.608 E.01633
G1 X178.392 Y173.93 E1.17305
G1 X177.854 Y173.93 E.01633
G1 X151.07 Y147.146 E1.14996
G1 X151.07 Y147.684 E.01633
G1 X177.317 Y173.93 E1.12687
G1 X176.779 Y173.93 E.01633
G1 X151.07 Y148.221 E1.10378
G1 X151.07 Y148.759 E.01633
G1 X176.241 Y173.93 E1.08068
G1 X175.703 Y173.93 E.01633
G1 X151.07 Y149.297 E1.05759
G1 X151.07 Y149.835 E.01633
G1 X175.165 Y173.93 E1.0345
G1 X174.627 Y173.93 E.01633
G1 X151.07 Y150.373 E1.01141
G1 X151.07 Y150.911 E.01633
G1 X174.089 Y173.93 E.98831
G1 X173.552 Y173.93 E.01633
G1 X151.07 Y151.448 E.96522
G1 X151.07 Y151.986 E.01633
G1 X173.014 Y173.93 E.94213
G1 X172.476 Y173.93 E.01633
G1 X151.07 Y152.524 E.91904
G1 X151.07 Y153.062 E.01633
G1 X171.938 Y173.93 E.89595
G1 X171.4 Y173.93 E.01633
G1 X151.07 Y153.6 E.87285
G1 X151.07 Y154.138 E.01633
G1 X170.862 Y173.93 E.84976
G1 X170.324 Y173.93 E.01633
G1 X151.07 Y154.676 E.82667
G1 X151.07 Y155.213 E.01633
G1 X169.787 Y173.93 E.80358
G1 X169.249 Y173.93 E.01633
G1 X151.07 Y155.751 E.78049
G1 X151.07 Y156.289 E.01633
G1 X168.711 Y173.93 E.75739
G1 X168.173 Y173.93 E.01633
G1 X151.07 Y156.827 E.7343
G1 X151.07 Y157.365 E.01633
G1 X167.635 Y173.93 E.71121
G1 X167.097 Y173.93 E.01633
G1 X151.07 Y157.903 E.68812
G1 X151.07 Y158.441 E.01633
G1 X166.559 Y173.93 E.66503
G1 X166.022 Y173.93 E.01633
G1 X151.07 Y158.978 E.64193
G1 X151.07 Y159.516 E.01633
G1 X165.484 Y173.93 E.61884
G1 X164.946 Y173.93 E.01633
G1 X151.07 Y160.054 E.59575
G1 X151.07 Y160.592 E.01633
G1 X164.408 Y173.93 E.57266
G1 X163.87 Y173.93 E.01633
G1 X151.07 Y161.13 E.54956
G1 X151.07 Y161.668 E.01633
G1 X163.332 Y173.93 E.52647
G1 X162.794 Y173.93 E.01633
G1 X151.07 Y162.206 E.50338
G1 X151.07 Y162.743 E.01633
G1 X162.257 Y173.93 E.48029
G1 X161.719 Y173.93 E.01633
G1 X151.07 Y163.281 E.4572
G1 X151.07 Y163.819 E.01633
G1 X161.181 Y173.93 E.4341
G1 X160.643 Y173.93 E.01633
G1 X151.07 Y164.357 E.41101
G1 X151.07 Y164.895 E.01633
G1 X160.105 Y173.93 E.38792
G1 X159.567 Y173.93 E.01633
G1 X151.07 Y165.433 E.36483
G1 X151.07 Y165.971 E.01633
G1 X159.029 Y173.93 E.34174
G1 X158.492 Y173.93 E.01633
G1 X151.07 Y166.508 E.31864
G1 X151.07 Y167.046 E.01633
G1 X157.954 Y173.93 E.29555
G1 X157.416 Y173.93 E.01633
G1 X151.07 Y167.584 E.27246
G1 X151.07 Y168.122 E.01633
G1 X156.878 Y173.93 E.24937
G1 X156.34 Y173.93 E.01633
G1 X151.07 Y168.66 E.22628
G1 X151.07 Y169.198 E.01633
G1 X155.802 Y173.93 E.20318
G1 X155.264 Y173.93 E.01633
G1 X151.07 Y169.736 E.18009
G1 X151.07 Y170.273 E.01633
G1 X154.727 Y173.93 E.157
G1 X154.189 Y173.93 E.01633
G1 X151.07 Y170.811 E.13391
G1 X151.07 Y171.349 E.01633
G1 X153.651 Y173.93 E.11081
G1 X153.113 Y173.93 E.01633
G1 X151.07 Y171.887 E.08772
G1 X151.07 Y172.425 E.01633
G1 X152.575 Y173.93 E.06463
G1 X152.037 Y173.93 E.01633
G1 X151.07 Y172.963 E.04154
G1 X151.07 Y173.5 E.01633
G1 X151.669 Y174.1 E.02573
G10 ; retract
M107
;TYPE:Custom
; Filament-specific end gcode
M106 S0 ; turn off cooling fan
G10 P0 S0 R0
G10 P1 S0 R0
M140 S0; turn off bed
;Drop the bed
G91
G1 Z10 F1000
G90
M0
; filament used [mm] = 0, 74.63
; filament used [cm3] = 0, 0.18
; filament used [g] = 0, 0.22
; filament cost = 0, 0.01
; total filament used [g] = 0.22
; total filament cost = 0.01
; estimated printing time (normal mode) = 2m 9s

; prusaslicer_config = begin
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = G:\\Rancor\\Rancor\\PrusaSlicer\\BedModel.stl
; bed_custom_texture = G:\\Rancor\\Rancor\\PrusaSlicer\\BedTexture.png
; bed_shape = 0x0,330x0,330x320,0x320
; bed_temperature = 0,60
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 4
; bottom_solid_min_thickness = 0.5
; bridge_acceleration = 1000
; bridge_angle = 0
; bridge_fan_speed = 100,100
; bridge_flow_ratio = 0.95
; bridge_speed = 30
; brim_separation = 0
; brim_type = outer_only
; brim_width = 0
; clip_multipart_objects = 1
; color_change_gcode = M600
; complete_objects = 0
; cooling = 0,1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 1000
; default_filament_profile = ""
; default_print_profile = 
; deretract_speed = 0,0
; disable_fan_first_layers = 1,1
; dont_support_bridges = 1
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0.2
; end_filament_gcode = ;"; Filament-specific end gcode"
; end_gcode = M106 S0 ; turn off cooling fan\nG10 P0 S0 R0\nG10 P1 S0 R0\nM140 S0; turn off bed\n;Drop the bed\nG91\nG1 Z10 F1000\nG90\nM0
; ensure_vertical_shell_thickness = 1
; external_perimeter_extrusion_width = 0.45
; external_perimeter_speed = 35
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 45
; extruder_colour = #FF8000;#0000FF
; extruder_offset = 0x0,0x0
; extrusion_axis = E
; extrusion_multiplier = 1,0.96
; extrusion_width = 0.45
; fan_always_on = 0,1
; fan_below_layer_time = 100,100
; filament_colour = #FF8000;#FF8000
; filament_cooling_final_speed = 3.4,3.4
; filament_cooling_initial_speed = 2.2,2.2
; filament_cooling_moves = 4,4
; filament_cost = 0,24.99
; filament_density = 0,1.24
; filament_diameter = 1.75,1.75
; filament_load_time = 0,0
; filament_loading_speed = 28,28
; filament_loading_speed_start = 3,3
; filament_max_volumetric_speed = 15,15
; filament_minimal_purge_on_wipe_tower = 15,15
; filament_notes = ;"Affordable filament for everyday printing in premium quality manufactured in-house by Josef Prusa"
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6";"120 100| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "-Extruder Off";"Prusament  PLA"
; filament_soluble = 0,0
; filament_spool_weight = 0,0
; filament_toolchange_delay = 0,0
; filament_type = PLA;PLA
; filament_unload_time = 0,0
; filament_unloading_speed = 90,90
; filament_unloading_speed_start = 100,100
; filament_vendor = Prusa Polymers
; fill_angle = 45
; fill_density = 20%
; fill_pattern = grid
; first_layer_acceleration = 1000
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 0,60
; first_layer_extrusion_width = 0.42
; first_layer_height = 0.2
; first_layer_speed = 20
; first_layer_speed_over_raft = 30
; first_layer_temperature = 0,210
; full_fan_speed_layer = 0,0
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 40
; gcode_comments = 0
; gcode_flavor = reprapfirmware
; gcode_label_objects = 0
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = duet
; infill_acceleration = 1000
; infill_anchor = 600%
; infill_anchor_max = 50
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.45
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 200
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]\nM800 F"layer"
; layer_height = 0.2
; machine_limits_usage = time_estimate_only
; machine_max_acceleration_e = 1500,1500
; machine_max_acceleration_extruding = 1500,1500
; machine_max_acceleration_retracting = 1500,1500
; machine_max_acceleration_travel = 500,1250
; machine_max_acceleration_x = 500,500
; machine_max_acceleration_y = 500,500
; machine_max_acceleration_z = 100,100
; machine_max_feedrate_e = 60,60
; machine_max_feedrate_x = 180,180
; machine_max_feedrate_y = 180,180
; machine_max_feedrate_z = 15,15
; machine_max_jerk_e = 25,25
; machine_max_jerk_x = 6.7,6.7
; machine_max_jerk_y = 6.7,6.7
; machine_max_jerk_z = 1.7,1.7
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100,100
; max_layer_height = 0,0
; max_print_height = 601
; max_print_speed = 200
; max_volumetric_speed = 0
; min_fan_speed = 100,100
; min_layer_height = 0.07,0.07
; min_print_speed = 15,15
; min_skirt_length = 4
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.4,0.4
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_{filament_type[0]}-{filament_type[1]}.gcode
; overhangs = 0
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 800
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.45
; perimeter_speed = 60
; perimeters = 2
; physical_printer_settings_id = Printer 1
; post_process = 
; print_settings_id = 0.20mm SPEED
; printer_model = 
; printer_notes = 
; printer_settings_id = Rancor
; printer_technology = FFF
; printer_variant = 
; printer_vendor = 
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 0
; resolution = 0
; retract_before_travel = 2,2
; retract_before_wipe = 70%,70%
; retract_layer_change = 1,1
; retract_length = 0.5,0.5
; retract_length_toolchange = 0,0
; retract_lift = 0,0
; retract_lift_above = 0,0
; retract_lift_below = 600,600
; retract_restart_extra = 0,0
; retract_restart_extra_toolchange = 0,0
; retract_speed = 40,40
; seam_position = nearest
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 0
; skirt_distance = 2
; skirt_height = 3
; skirts = 1
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 20,20
; small_perimeter_speed = 25
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.45
; solid_infill_speed = 200
; spiral_vase = 0
; standby_temperature_delta = 170
; start_filament_gcode = ;"; Filament-specific start gcode\nM703"
; start_gcode = ;Begin Start GCode\n\n;set temps\nG10 P0 S{temperature[0]}\nG10 P0 R{if temperature[0] == 0}0{else}{temperature[0] - 40}{endif}\nG10 P1 S{temperature[1]}\nG10 P1 R{if temperature[1] == 0}0{else}{temperature[1] - 40}{endif}\n\nG28 ;home all axis\nG29 S1 ;enable mesh\n\n{ if current_extruder == 0 }\nT0\n{ elsif current_extruder == 1 } \nT1\n{ endif }\n\nM116 ;Wait for all temps\n\nG90\nM98 P"prime.g"\n;End Start GCode
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = -1
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.1
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.35
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 2
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 50
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 55
; support_material_with_sheath = 0
; support_material_xy_spacing = 50%
; temperature = 0,210
; template_custom_gcode = 
; thick_bridges = 1
; thin_walls = 0
; threads = 32
; thumbnails = 128x128
; toolchange_gcode = ;T[next_extruder]
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0.4
; top_solid_infill_speed = 50
; top_solid_layers = 5
; top_solid_min_thickness = 0.6
; travel_speed = 180
; travel_speed_z = 0
; use_firmware_retraction = 1
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wipe = 0,0
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 20
; wipe_tower_x = 156.544
; wipe_tower_y = 144.37
; wiping_volumes_extruders = 70,70,70,70
; wiping_volumes_matrix = 0,140,140,0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
