; generated by PrusaSlicer 2.4.2+win64 on 2022-05-19 at 02:53:28 UTC


;
; thumbnail begin 128x128 14660
; iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAquklEQVR4Ae1dB3xN5/u/ESJDQmKkgk
; QkqE1JbdWIVdqoEX/UqFGrRVVtVVpFWyNWUaSKaqzWiFl7xs8MKkgQQYxEkJ04z/2f73tzrjvOueec
; m0SlzdvP80kl5773vO8z3me/Go1GQyqAU/m8GdjY2JBTMSfavHkz0QvSgcTg+PHixQv69ddfycnJST
; 9HcZfi9Fb9t2jJT0vo3r17lJmZiWfZ88LnyIrxgntBcXFx9Nu636hzp87k5upGGhsNFbIpRIULFWbv
; bmkfPMp50IKFCygpKYlyOvjVUGRkJH0Y+CHZ29uz+QsXLkwtmrWg8FPhbM3YG9HPSqwfn3n06BGdOX
; OG9v+1n/bv3495Xw3iTcHX15f+vvw3URaZEQGXPbJ3gtJS0mjMF2PYBhjOUahQIa5EiRJc3959uT+3
; /EmJzxJJ/zFGEWT1yMrMotu3btPcOXOpeZPm5OToBCLgeGKwuBdFixaloO5BFHktkqwdmVmZtHbtWq
; rsUxlrZPPy66RxX46jx48fU1ZWFonh2GjfXv6OUlJT6Pf1v1OnDztRCdcSZGdnR7a2tmRb2FYRAeQ6
; 8gVJ0LlzZ0pOSjZbhNimxMfHU0CrALIrYmf4XjrguVRTSMP5VvWlSZMn0cWLFykjPUNWwigd2MCIiA
; hu6ldTqXat2uTk4MSkgqX1VatejUI3hFJ6erri7wHF3o+7T0MGDyEXZxc2DxBVs0ZN2rZ1m2qux/NH
; jh2hJk2asHkk3tUi4vME+QIUsS9Cs7+fzRYlRr2m4+yZs+Tr48uJvBvHEwAjAptCuiMmMDCQfl39Kz
; 148IByMgzfC5yXkZZBhw4coi/HfEneFb2ZVGJHA77fxnh9zs7ONGLkCIZUuYHjZ99f+6hB/QZ6Sefg
; 4EC8dGOSSDjmpN7R9HcJTxJo6rSpekKyAMa/AGUXK1aM+6jPR1TGvUyeIT+ba8mtpBvOIg6bK4MIys
; zI5HaG7eTwfgabLUmoEJ8VKlSgQYMG0dFjR+n58+eSHKR0Y9mxwk/BZXH0JOEJhe0Mox7/14Pc33AX
; JQJwXuMmjenAwQOi3w2uf/rsKU37ehqVKV1GLx09K3jS8mXLKSUlRRXXYx/PXzhP/q38yUZjowQX2S
; KZf9i2kC33Vr23uJOnTtLzpOcU/r9wCmgdQOCqPCQCrr5ffcYlWS+ySOrgFjgxPSWdJkyYQDaFbTix
; DRclBNtCZO9oT40bN6ZFixbRzVs3ySrkG2POaNPv3rtLP6/4mbp060IOjg7sOw3foXTp0jTr+1n09O
; lT/efA9Tiu2rVtR0XtiuqkYpEi1LZ1W7pw4YJqrk9OTqaly5eqZVwd1/MvwI0aNYopGRkZGeyLgZAH
; jx7QlKlTyMXFRc2kSkDPtbZFbGnI8CGUmpYqes4ZimH85PUBrmOHjlBmlB9R2RKnkm8l2rJlC73IUq
; dBKxl4b+xddHQ0BQcHM4JzdHLUf7+dvR29/8H7dDHiItMrlv60lLw8vfTWRamSpWj619MpMTFRtaIH
; ou7Zq6eg2CkHcD3/EtzWrVspNTWVTEUxJk9OTabd+3ZTnbp1cpsI9OBg70Ch60P1RCCYdYaLNSSCqK
; goqvZmNcXEBs7q0LEDXb5y2Wgu082lXBjYQ6whNTmVLl64SBMnTWR7B0JnROhTiVq0aEGOjjriwDHB
; S176a99fqhU9ENy27dvIt7KvdXvfpUsXiomJYdqqpfXDNIm+HU0DPxmot0ut5HpJrq1UqRJdjbwK0c
; iZcr0Y1e/ds5dxjdz3lipdimbOmsl0AKmNzS3kCwNIFBCJqXHOHzp0iPz8/Izezb6oPdNR7sTeUS3y
; 4W+YOHEiO3KsZj6cG/hiJQPv8Oz5M5ofPJ/ZklYg3+IzhW0LU+AHgZT4NNHMqSPBsTR37lxGkGIKDz
; irYaOGdPDQQcUby44+noPhYDp27BglJSex/bHEmbL7xv8XnxBPY8eMZfa84TvCebRr7y5KS08T1X8s
; ESbeae1va8nH18fQSaWOGdUsCs/u3LmTqlerrndQ5JTrRZDGzfxuJnP+yHIm/xeI2Z7/19PULufgOY
; QJ9vDhQ+mPm8wtnOF7du+henXrUZHCRahR40Y0Y8YMdsampaWRWkGB58PDw+mdFu8wBU9sza5urkzP
; SkhIsPh+UgNSM7BToBqmfIkPUjigmIyfMJ6KFy+eq1wv9mzJkiXpyMEjMPsIp4HFF+P/eiP6BjWo14
; BxAaDKm1Vow8YNDJmiH5Hg+idPntBXk74yO1YwZ/ESxaljx4605Y8t9PjRY0kl0nBA0Zs/bz6V8ygn
; u37Y/q3btKbw0+FWHUk4Dn6Y8wNXpkwZxfusiADwHmfPnqVmzZuZuWLzAvnChjdq1IhxnZJ9wDNnzp
; 4h70re1C2oG924ccPSs2bIhyg9d/YcBfgHWOQimHbgYm9vbxr1+SjG2ZAKkByZLzL1Ziz+u37jOnXr
; 0o0ptyr2gcpXKM8t/mkxM+msGfB3NGkm6vkTl8SWJsPiENyAk0PFGcOpeM7coycQAe97GDZ8GLMKlA
; wg4dq1a8ySERtiXIXPpKak0k+Lf6IK5SqoPkfhqWvUsBGz/2/dvsWIICMzg0JDQ6lqlar6YxLBqw7t
; OzDpie+QOD71ewGdBibdjagbZM2AKT96zGjmiZTFidQk4L4uXbuw4IaKTbEW+aKf4z1+9Msvv6g+d0
; 2HlMi/GX2TevXopTfHrAUgFI6e7j27U9++ffXHJH5f/c3qtGXzFkZop0+dpsaNGjNJCg6Viy7WrFmT
; Nm/ZLHmUWRqQavxxxfExCc4iYZt+EFyxcdNGZlfmlaKnEed60c/7+PjQpSuXrCICKa7Hhv6x5Q+qUa
; 2GpSCJVSBsNuNiXjkFkRn4NSj+cTyL6oHoQAiIaFqaDw64L8Z8YVGZlVo7ft68eZP+r+f/iTIyw6/h
; hyA6Pv3sU8Z5ViJTzXOcks/DvGvbpi3FPYiTXayl3wlcDwXui1FfkGsJ11xFvCEBlC9XnpYsXsLOcT
; ErC5HKnTt2clUqV9FLA0tz4u/QwQ4fPSxriooRPeIJS5YuoXLlXyqjjg6ONGzIMB0B4HnYvA38Gqjl
; iFwV+VIA6p0yZYpiO1xK0Ttx7AQ1a9KMmXc5QbIUQEFs9W4rFrWU8+jhbzG3Y6hnj55M8dRHFS3MD1
; 3sxzk/Ml+MUuQbDijKrQJaUWXfyrQxdCO9yHyhcwTNmjWLSpYq+SoQbxVAVLm7u7OYuCUikBL58ADO
; +X4OlXUva43DRBGUdC1JUyZNYRFCNX78lOQUWhi8ULENj+eQ2CG4tA3nJgUDwShkBfHmNYtqatq/11
; 7SQZHLyM8xEdSvV59iY2JJLGAo5SmESYj0LrhcTedsV7U0da39Ro4QD4lZt3Zd2r1rt2o/Pp6NuBBB
; zZs2V6NvMahcpTKtXbcWlppqn4Hh0KgM9XIKn5Ey73JKBFyfPn0oLTVNdnMFAoi8Gkk+lXzM5prgX0
; l7eGhDBsGB1bTFiqpXBpEmNrD/QIqNjZXkeqn3wxqW/bSMOZ0Uxu3Nv9/JiRsydAjF3o0la4dGIWLU
; avi5gnAzsNFwhYsWpnnz5wmatSzlp2em08bNG/U2sW8pRwr9qK4e+QKE9W+gbeatTDGE29nby5t+Cf
; lF7whSinj86k7MHererTuLfVi5F/o9huTwe9uP9uzdQ3JJNZYIQAkypZBCTs5OzIevkXDq5Bro0r6o
; tHtpKDSy+GfKH++cARHMmj2LBjT0JFPEm8JnTb0sSgOcwR3f60hXLl9RHb2Da3v71u1UqWKlnOoiZn
; vr5uZG07+dztzZuUUAsghEfLt3/97c2QtnuZGjRnLZqdt5mkcIKYCkB39/f3qSKL9YuGWfxVylMzM+
; 0sohX4CV3WppISlMvxt+9lnfzaJnT5+pTtiAcjh61GhRXUQF0i3uLXS5du3bMW0/pwQgy/Uenh60Yv
; UKljqGkZ6RTqEbQ7nKlSuDuvOKCNi84B57O3uaNGGSrJcsdv96Uop40yNBUBBhojX0a0hHDh1Rr+jx
; QSPk8fvV95PNJM4J8g3By8uLlv+syydUSwCyX4SASNuObbnzEec5fjOMsnWY1s1H5rp27WpNvoDqDU
; BsfceOHaJWQWbKc7q89EutNcg3hAWB1bXjhn/CsovVcD0GTLw5P8yhEsVL5HTtqj+HOEWfvn2YJ1Ap
; AchyfXG34vTN7G+4R/GP9AsWWziSKBYsWkBl3yibW8iX/HutWrWYQ8VwJF47Q8dHt8ox8gXAXPePbx
; PdQFFFj7exo65HsQCQbSHbPFm3EoCkrF2nNm3dtlVSUmo0CrgepmK9t+txfx36i0tPTxfN0TOdGGLy
; 9OnTLBFCrY2rscD1Ru/Fm0/QpHv17KUvx4raMDfXEG8KkaunayFZLCEfbt4N6zdQeY/yOVH0cvUI5Y
; NT3Ljx4+jR40eiBGDxw0Udi9LQkUO5mLsxcF+aIVzSBucfTUxIpInjJpq6l5X6EmQXJtTsFS1SlJbP
; /ppOTQrMM+QLAGXySeQZUXfzwwcPafCgwTlxNefYayoF0GNavtuSjp84bnSMSRIAqLeiT0X6bcNvXH
; JKspHIl/M5408RERHUvl17azZD1QbgPbvX8aDDeYx40yMByqUgDaAbHD54mGrVqJVTrs9bC4oHDw8P
; mr9gvl5ialr5tzIT0YWKFKIPgz7krkRe4TKzMs0Qbwn50DxXrlrJNFGViFbkc4AfwMbWhiVTlnCyJ3
; jxXiXyDeHC3KHa+NvXafrU6VTMSVUEVW4v8hQQXOvarSvLJdQgPDp54mRd4Qe/wSXdS9LcBXO5hMQE
; M0VPjuuR2tzv436GaePWhoolkY/cPDh1Lm0LocP/EOINYfcnDbVBdT1ygnizdDiEalWm36nby2x488
; 03deFgaIj79u6jvh/3pWOnjnH8vxUpesKAbRwWFka1a9dWq/Cp4vp69evR8ePH6cqqqf844k3B2niC
; IcCRg4qnUydPsQphg5SuXEW8ERgiGkqe2rMe+e6ofLHC1lXM9Sip+mzkZ3Tz3LFXouhZCwrjCaJcj5
; SyRQsXUXpqOgvTIlj065pfqYJnhTwLYesJwBTRlpAuDJh5SGF+p+U71mQLyyM/m+u9vL1YN5HrWxa/
; FiJfCRFYiCeYrZ1l+zRtRhfOXWAVx6yfAfdyjy9dvkQdP+hIhYtYfSRYBjkuFxvQIBctXsQ0ShlEK/
; mdKNcXKlyIVdpGHNlN//u212uPeFMQiSeYrd25mDNNHD+RniU+M0K86UBZ2czZM1nSTq5LA7UiH0WZ
; QUFBhq7eXFf03Eq5sTLu6ztW5QuutyQNsuMJRmuHnoTCVlQgmXK91EC6+aEjh1ilEgp6c5UAFCl6WZ
; ksW7hq1apqqVCVooeihvBjh+nv11DRsxagIL7hrMvKhQnWp3cfirsX9xL5MgN9BFhYmw+4fTvj25xE
; FM2BFA7kDgrpzCqRr4jrHZwcWOnZnYuneEWvU75CsFJpEFjfl0JWhlBmeqYirkcoG9VGGVkZyDriun
; TukpMkEstHgJKB7JfQ30NZhy8FiFas6KGWb9euXRS5/vt8hVRr4EboXG0mQugyuy5wPUT/ju07WAZS
; DsLJ0hJZbRct0MvVv69St67dpJJJFXM9EkoQsow8eSBfKnrWAuIJSXeukSTXc1nsyH3y5Ak3auSo3B
; X5pnA54rIicWQ6kGodPD9Y39hIDdcD3Mu6U0hICEWFvR4evVcNpvEEgbkErj8dfpqr/1b93KxcMjM/
; 69apy2k8vTxp1YpVOgeESiJAEOTE8RPUskVLTjYLyEDRa9W6FV08c4oiFn+Rr5CWF4B4Qurje3qRn5
; Kawv34w4+soNTabGE5QJc1ls18Jxb/1pC9gz3169uP7t65S1YcCRzCoOPHjmd2rSXkOxd3pm++/YZu
; Htmeqwkb+R2wF3eP/cmaS1kZQVXE9TA/vSt6cyGrQvQNLDX6P9oWYtk1YTvCdOYJJ494QwUSE27ftp
; 11tRTj+lp1atHhw4fp2vof8hVyXiVMe6+G1tk+b8rWYH4im/nypctGOY0a0wcRbZswfgJL5pCSBpYs
; h+ioaGbnFrUvypBfpGgRGjJsCEWfOfpa+/FfF4AHUWl9ghKuB7iXcedmzpjJsplNUacR+yD8zmhjdu
; b0GTMFUYnZCJ/BilUrqP7b9Sl0U2i+8eO/LiB4EHMaXeRjNFyjtxuxZBWpohGNxoLSBl//ogWLWCMm
; oXMbKRwQM/ExN/5T5l1ug6EHUS3X80okN2L4CHoQ98BibwWN3GQQ5bzNz92MuqnKXIw7sb2A63MBDO
; sTFCp6HNrToOmmks4iGgWUxUFBrFKlCm3asImyMrJkiQDZs/lpk/MDiCScmHG9g70DF9QliK5fv66o
; kYQcAZh9QTHnYjRyxEh6/PCxqIII71b45H+fH/91AYOEEyN3LoJz5TzKccHzgpn+pSa6L3UESDp14L
; 5t+HZDOnL4iNGRkJf5+AVgDIYJJ7w7noMjDuVnSqqDDfU4pPJp5LheSkEsXaY0zZ41mx78fU5V4WUB
; 5A7AXKxX0Z054NB4Sg3X49mExAQaO26suBmoFHo2qFCg6P2DcOizd7Qxe9caxRPEON6Q66EboHq4ad
; OmZFeYJfWoL0iA+JnRrkq+2qx/MwjxBEviHiM5JZmCF+gCeKiosrXBMWKjjuvrergQlJH8tEH/BUA8
; Aaa3GPIRaIq6GcUu6UIZHZCP3AI4+zSVq1ZmlyyZZvaKRaKgfOSnTfkvQuTqaZSZ/LKNHNLI0CKnkn
; clKmJbhFUrC7h92+9t0jx5+oTOR5ynZcuX0cf9P2b2Pjp9MBGR/bBUX50CeD0BSvmj8wfp4eOH9Omn
; n7Jr7gSuN2Jy5HYKeWdCt2s0W0bTZfTo/eSTT6hfI98CRS8fwtHP/bUTujQnN0cHHSNLJfIamgaGI+
; 15Ip2fMzhfLboAzAEdTspaiieQyCjw4/+7wGI8wRT5BX78fy+IFrAKiC/w4/83wKyAFci/f/k07R/8
; dr5aSAHkDAIqZzcHRyuzM7s2UnB3P+3G3vXy1SIKQD382e8t7egW3tqKrtl3GeFq8S+//JIWfv8Nze
; njr13To462QBr8O2FRp+rarrXe0JZ0NOjhCH+wcJFRyRLO1KFmWe2c96tpdw/0y1eLKwBp2PeJn3b8
; uz7aJl6uWhFLwNw08C7pRJ/zYgLSID8ttADMIaR7be3HDcprq5Z2kvIFiDsIHIrYUrc6OmlQcCTkT5
; j9XlUm8p2LWqwothz9e9uzBE3w9ylQEPMRCIperTcUNZmSDwG7867EQQ0raJd3rVkgDV5zmMtL7Gk9
; 22i/GDqIvDy9lDTzkP4junEP6D+AlXB7lS9L7au5a6e1razd0b9+vtqU/wKA66Hohc79WotcTZT3oQ
; fkli1b2MXSLiVc9HcrmxCFOeJROlyjeg12Sxe6UyC//En8E1q/bj2N7NeDxvpXLlAQXyOAZB4VUFN7
; /tDulz59g4RdJH/ejrlNP/74IzVu3JjdbGrQz9FE+bN3oD4f9aHbt26/vBKFy54wS/fz2t+XKGTyEC
; owF/9ZgHn3Tdsq2iVjB2pTnj8lJQPh/gvnL9CkyZNYY0+NYXKAZ3lPWr5Ud9OE3K0Y+AEP4qzO9bXr
; exUki7xq2MAr5Z81rag9vmMDWTOAP9QQMAJAq5c2rdswylB7EdK965dp7ZTB2iWdaxQoiK8IoOh907
; ud9vG9O5TToQHn9+vTj902pfZKFGFA/OxYPF0bHFQQT8hLEMy7bT/PpdwaTAIgYfDihYuSyFc6WfT5
; kxTcp2VBPCEPAIrexE5NtHciL1tGAo8tVATj5hLh37IEgN5znd7vRImJiWQt8oWRykuDsMXfFMQTcg
; mg6E0J8NW2qVZWi35MSrq3XPn7Co0cOZIOHDhAKUkpTHFHeT9JEQACQg5FHWj27NnM7BOuhsnJgDSA
; glhgLloP8OMPbuTJ/Pg4qls0a0EJDxNky8DQYm7nrp0sw7tt27a0ds1aDswtVi6utwKQOYqW5Xv/2s
; uBCJQwv+EzYtIC0mDdV0MK4glWgJgfH7UbY8aMoZS0FIs4Ya3meBzu+2sfvVH2DdZ426uiF3097Wu6
; cukKa/hpRgAa9AGwKcQ1bNSQ7t+/r6gRBETNqVOnLDYiAGEc37SKSYMCBVEeJP342Q237B3t6ffff7
; dY/69vMZuZQUuXLWV1Hrj5Dc267BzsKKBNAC1ZsoQePnyoJwDO0As4bMgwysqULzWGHfnVV19Rly5d
; 6I8//6DE54lmUkGQDPdvXKFFg98viCdYANGEDUPI7rjmU9mHrl69KtsEAgNEMHTYUCpiV0TfpFOA7H
; sdzQtDHYs50pp1axTVm8Oz9Pnnn7Neg3AzzgueR7H3YuFP4FCTZvRstoKI9LOCeMJLEPz4EgkbZpIA
; Ir17j+7s7mQlRBB3P45wORikgEgtqPgXlStXjq5cuaLoCx7HP6b+/frrCg8LF+bcy7pzffv2pSPHjt
; Cz5GdkSgiG5mJ+QlReACQiEjb0OXpKwEbXyW3evHnsPJfy3wgDf0N/QNbkWykBQOvs0LEDPXv2TL7f
; DOkuTWzYoCGnKznWzQEPI5pPTp82nS5dumQkUSANNn8/9j9rLsK8g6L3fvUyWjtb67qA4zbzUydOsQ
; uqlYxNmzaxNj+KCABgV9SOdQFJTUu1rHRwugun0KbEs4KncWSRty5QmOji7EL+rfxpzeo1zFEBHcMw
; nvBfUhBVJmyQJSZt1KgR3bt3TxEBoD/AmLFjhEggJ0sAANcSrnTwwEFJq8DkxhFa99s6pnUaEYHNy+
; JEfDkoF44K9BlKT0un2MhLzFz8LyiI8OMrSNOSA31TD+zr8GHDmS4mO3gsJTxJoPcD3+eyu4PIEwDA
; r4Ef3b59WxT5pr9DJHH06NGK2pxDwjRo0IDQHTvycgT9GTyV/q0KoipFTyXgFpe169bK+m5Ys08ebk
; XfohrVagg3m8t/Abh2wIABeiqTDA5l5w08fvyY/AP8WQNqJXPDwVGiRAl2JcqCbybTjz2a/aviCYKi
; 5+FSlDQaqxFtsY1PzZo1KeJShKJIblZ6Fhe2I4wr5VZKGQEwKnNwpFUhq6APyLaMxc3h5y+cp/Ke5X
; U2p8zC0N1SyFBBXOJNXx8a8UGzfK8gCgkbLX1K5pTrFfVwCuoWRM+fPjfq4WjKrML/I+w/ffp05QSA
; l6hYsSIXeS1S1uzAQGuS7Tu2k1tJNx0R2ChbGAihc5fOrNtl1LkT+TbhZF3POixh4/sJI2nQoEEU+H
; 4gNW/anF2qjfw8tG9na7YxgJwRCZvz2+nf6gJGJB/Mw60vSglAr3R06NCBOSCUOIngIp40ZRK7+lWE
; CMyQD2JBF6vnSS/bngnxhPyUcALzDgkbj2JjSEjQBGA/kpKTKCEhgU6cPEGLFy+mPv36sEuc4eI1OT
; KtuhvQo6wHHT181Cj6J0UI+LUSAjB6Edj2LGqooBExBqJQ73V4zzKF839r2qwpnT59WpKwjm8Oee0L
; WEUTNjiyGFcBElJSU5jTbcHCBfTuu++yTt85kATsriElpiEcdBolXG8KSBffu2+v4ohh1I0o5hASy1
; F3dHKksePH0qPHj2TnQjxh2dAPXksFEX58cP2da5fJmgE/C25tx80r8NpN+3oa+fj4WHMvM/tM/wH9
; KS09zbKuRtISwCIFApG4GubG9RuKFgci2B62nXN/w91onipVq9COsB2KpQkGjoTQ78e9NhnJOwc00O
; Xjz/taSzkcpgyFowLNusA8+sujbSwzK3ADAnBydKKVv6xkuQGWhkYN4g1FNs6rQZ8MoqSUJLlFsVWB
; sufMmcOOELxg7z69mW9BTdIRNNeTp05yzZo3o0qliv3jBaxI2DDLx7diWFLW8Cf4+9etXccIAc26ZX
; Qp9m/bwrZUwasCRUREkKWhUSLyRaGQ7raxRUsW0YvMF7KLgohLTuJdkV+MoRUrVzCHkZqR+DSRm79g
; PgcvouBksuejYv9EAavgx58zNEhxPn6OB7x4iQk0f+F8KlehHNsDk6v6zPAHRxuUdr1pKEJmmuxJrF
; M6eCLw8vZiypvRu1rQOsHFSiKMwoBSeDXyKte1W1cO0sOgokX/zq+ygFVQ9P5av8LoPbEmrA+KFX7i
; veXiJ2TFQAwl8mokN3DAQDLZD1GAtIXS/iLjhSgRaCZPnMw5O1sflMCZ0yqgFT1OeMwWbu3CxAaCUL
; 9v+J2r5FNJoHhJSfUqCliFfHxDRQ9Ihn/91MlTtHTpUpo6dSqLc6DJ5pDBQ2jsl2Np/rz59Mcff1DM
; nRiWzpWTnEu2v/ynMzMycY8z51HOg5Nzu7u5utGB/QfEJQAUsN07d7PzxVoiAJVNmTJFdyt2LgysMf
; ZeLPfZiM9YYEmM68UAR0KbKqVyvYBVX3iZregJVTVbt22lHj17UJk3yjBfBzhSzNJBu114OIs5FePe
; eustGj58OHOSISULXlNFN4mbt31nFgMcZs3faW7J2cZaxNavV5/uxt41m1ffJg61gP0/7v/SQ6UOmB
; TZuWOnKvEuNpDCdODQAa6BXwNGWAYbqviY8nJ10CuIOZUGQuFl5JkT7P2gkIXtDKPmzZqz9CwhvYpl
; 28i9m43Bs/xPJGiMHjWaVWRZurrXVKqa9v9HBtbAwQPZmS/2vQj6oFH04IGDWZq44XRGjSIR7Fkdsp
; rKly+v7hjgKRxfUq1aNbp58yZZewrEJ8Rz3836jtzc3AyjiWr0E/3xAGmAZAtrzUXBj//L9NF68+7W
; rVvUt09fcnBwMEaqWoaxMf5/Zxdn+rDTh3T82HGdQs3JI97k9/Q8+Tl9PupzVtwrtmeQAlDaQ1aHUH
; pmuj5Ly6xTKCgq4mIEdXivg6qbqxHzR4wZG4TEAzUDCtPFiIvMYwiuVyryRZBv9vvaZZ2ZgqgmnmBa
; eAnFddu2bVSndh0lDResAqzZ3t6eevTqwfY/PS2dk0u7NyUCtPz7bvp3ks4jSJ6KPhW5iCsvo4YaqQ
; nhwsV1o66uroo3G1RmZ2fHlCFsmpLUciws5nYMV7tWbVlFTy3yBfB2d6WJXVsoiieYFl4itD1+/HhW
; U59b7yMHZdzLcMELgykhPkGnI6gYqSmpzNS2KyJ+HGB/W7duzWpBLRIABpB46OAh3cUCChcGSvb09K
; Rz/zuni0q9sIx89tLpqQSFj6Uu5yLiAb4+vrR+/XqKf3CfdiyarpWKJ4j58cNPhzPfvDXuWCtB/1kg
; sGXzlswtrCRF33CAeXEbvJQkxXE9Y8YM3a1hSia8d/cefTr8U+OzzwKAytq3bc8oWEkqGQZ//lObtm
; 04FRsl+yxE6tKfllJGWoY+cRIZyabxBCh6puYdjqXd+3ZT1WpVZW3tXEK+0TzMpVuoMOEW0LCwsJfF
; ngrHndg7FNAqgN0kKvYduCR839598gQgIAna74bQDeRTyUfRIuAqRhcK4Z560/lMf4dKlgsXL1Bl38
; q5uskgWtji4Arhqw0LWFF4KeXHhz50Pfo69ejdQ5BOeQGmxGzMrbxu5VrclVXyMAtL4YmAPT1y6AiV
; KVXG/DuzrZG69eqShnGpDPIN/g0vFHXr0o2KFJbZEP4LXFxdmL0rnGOmXG/0HZwubr5x40YqWbKklL
; JlFYeBgxs1bERnzpwxMlMhDZR02Hj67CktXraYypYrm9tKIKdkfdCtnJ2cacniJTpfiwKfAX4i4fbL
; MV+amtN6ImDmKHoFo76PkyjpEhtJSUkUPD+YFZNKLi6byqrXrE7Rt6J53GaJvqTR4HGTlpJGkydMNl
; VirHdXZwM2AOYlvHLwMKodOC9Pnz1N/m38WaAlF4lAMcBcXL16NYvwoQDUdAvN9pT/V+zdWKpV04KT
; z6awDbm7u7MOUshWUerKxRl58sRJeqfFO5a5gieC7j26c+AiiHn4MS19B87q5GfJFBQUZJq/nisAbg
; j8IJBu3rLOX/Hg0QOaMm0KJ7Rds+IdcrQeMN3ho4cpPSudEYEsnngFEgqfpB5T3kvn9EG8uUPHDhxc
; i2o25tHDR+z60mLFikkuFg6I5SuWsxfmqdesZtB0QEzj4qoqVarkKvINpQEKWDZt3KQzV1UMEG9aeh
; rt3LuTaterrSjz2QIhWLU+1GDiRjDZ8UIHUdFRVKpkKfH59uzaQx4eHvpkAiQtrlmzhrlklQ5oqNu3
; bafq1asbId4QUGuIK0tZQqnMIYZNBhGE7Qijsu5lRe8wzA2A23vY0GHM1lcrDfB+t2Ju0YDBA6iova
; z73KKipxbg8kWuJb+XMhtJjACgC7zX/j2hDsAY+DAhtzB4IeNS4ZfQnJHJGhcXR2rGzeib1Kd3Hw7O
; IJENYDdVopDU4jsb5q/z4guWhAozTDVgbnj4jh49KpmPaFEf4o/NkDUh5OntqSwekNMjLVu38q3sy+
; EYk7UK+L/DDP72229ZPMD07kANHkBSYr+P+xllm2BjatepTfv27VOa+8ceQqLHip9XsOxU08XimIG/
; GhQp9nnDjUaUcsOGDUxUwx7OKykgAGoXcVYiyme6JrnBXNmXL1LHwI6mCmKeHGHAEaTOml/XyDrbst
; dBu3btEvfjCA/FPYhj1TwswmUQrIDDYOrXU1mVsBzyDTfk/Nnz1K5tOzPuLe5SnLZv3878A3oLkDNK
; Yaa4h3E0ZOgQcrR3FL3xMq8AIdvWAa2F5guqNcT4J/E088eZ5FbKLc9iBgJg/o96f8TyApT4Bk4cO8
; GI3IQ4OT0BsCDQpQjmxjWt5oHm7O/vTxcvXpQ1Fw1/h6RGlIab+tHh3YqOioaINyOcg4cPUt06dVlg
; yfCe21cFyJBC54yQkBBVyarCSM9I5w4eOUh+jfygIObYfLVEAO80f8dIYkkOXkKAIV1cXMwtKxPk0d
; atW0UDQPhCXlmkZcuWMa+glEfP9Heg0P1/7SfkqhvO1bVrV2YaCuPZ82c0/ZvpzOslXG2el2e/HECP
; 6d27N+uXpPQIFNYvJLSMGD2CdVvJEwLg9Y2W/i0p6XmS7BGAEX4ynKXgmxGk6YOQBLNmzpIMgGBjev
; Xqxd25c0e2S5jhiL0Ty1KkeP884wrUGq5cuZJFry5dvkQBAQGM64F8OIHQ4nzlqpU0fOhw8q7ozVyx
; asLTKkGUU0GoVatWpT179yiqhDIlBORXhG4OJd+qvkoVRNN3Ev9bthcvqHuQMs8g/9/WP7dyqCI2m0
; vsA1DkPv74YzEiYC8FzkQ5E6SFrCliMPgN4X5b9xtVrFiRzQdJM2H8BCpXtpz+avNSpUrRD3N+oISn
; CcxvAJ8B9JPNmzdTYGAgobbAUDLg//P6vEWO/cSJE5lLWI3HFAPOr6vXr1JQjyA18QSLyMcRDYX6h9
; k/yHdvQVp5eho3dsJY1lvILIFF6oMPHj6gZi2aWczMKeZcjEPfOpz1ckPYKLzw5cuXqX279nrEsVvL
; eEUP+f6Hjh6itIw0MnUdY8BpExMbQwsXLaR27dsxTRgbYZJEkjtcZgKYv2nTpnT+/HkhA1iVkpj4NJ
; GCFwdTmbJlck6wPBLLlS9H165fs/ylug6hjHCbNGsinr1k6fPh4eHMMWRp40AgjZs0Zs9yCmrTgcSw
; XWG6hkUChxVzotFjRtPduLt6rrc0MB0cVSCkmbNmMjseyaMGCSV5ApgbHrVFixZxQpRTDSGwwpbTJ6
; n5u81zFE9AmBsRTmYBSO8RJziCDh86zBRA0fksTKBDFh+LFjEfzCYqXaY061plWPBhat6hqnjc+HHk
; UsxFb95VfbMqbfpjEyWnJutjBWoG5oUegf5Eoz8fzc5sfRmVAcfIvb8KicHqEzp37ozKJrWCgA2Yue
; Mnjyfn4s6GGVCKOB+u566du7IbXKSUP8OXAqEi2VdSfyKyPAmcRBMmTlDEWdgYKG9RUVGcoR0NkXnm
; 3BkmQgVFD/OBa/fs2YMzSpbrZUc2tT9LfEa7w3bTkE+GMKJk554uczen5hhnIg04KKd//vmn6ngCBi
; yp7Tu3U41aNThFxxePfDjqPuj0AUEBV8InYKjw/4UzqSWJP9OcdDGSTniSwPX4qIc5Z4mLSc67kjdr
; ZwrNGXZqcDB/9pUuozfvDJ+HYqc3ZXKjpCQ7AIKoIrKMVv+6mgI7B3Kubq65gngxcTxixAiKj49XFU
; 8Q4h3Rt6Op74C+kindQsY1rCYo5olPEkW/Rwxv9+PuU7Mmzcz23AgyUjP0m2/JtkdcABysdLNgcsC9
; 3Cmwk66BpIRHDwGZeXPn6fLecigEpDYaHBp9M5qWL1/O4hGIXBpxhI1i5IsnbPAcDD/HyZMnFdVFmO
; 4zGmL8HPIza6ljaC5iv7BvXhW82LuLdQKTOoMgucdPGi9veTRs2JAhAOeZYesXo6AMr5EjCeHkqZNU
; vlx5qY2S5BQsxJJHD563EydOWF1PoGSTuex6Pega16OuMw+lnx/vrSvCE6WtRq6DiaLjA40dUIeHzV
; fyToYD+3vu4jlq16Eds2rAtfZ29tQmoA1duHBB1Xw492fNmqU0h1PDob0r3LW4HxBh3eSkZM6QkplC
; +EKXhRLyawgVd1WVIq0I0IoO2SuKRnb6mNJKGsMBXYNZGvz6wFHg2jHjxlDFShWFLCRFXC8FQB5MXN
; O8CqXa4qP4RzRj1gyWzYwmEU+filcfS80HaYc2O6JOHxH4f6bNWka0RDCpAAAAAElFTkSuQmCC
; thumbnail end
;
; 

; external perimeters extrusion width = 1.50mm
; perimeters extrusion width = 1.50mm
; infill extrusion width = 1.50mm
; solid infill extrusion width = 1.50mm
; top infill extrusion width = 1.40mm
; first layer extrusion width = 1.50mm

M107
M190 S60 ; set bed temperature and wait for it to be reached
;TYPE:Custom
;Begin Start GCode

;set temps
G10 P0 S0
G10 P0 R0
G10 P1 S210
G10 P1 R170

G28 ;home all axis
G29 S1 ;enable mesh

 
T1


M116 ;Wait for all temps

G90
M98 P"prime.g"
;End Start GCode
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
;T1
T1
; Filament-specific start gcode
M703
M107
;LAYER_CHANGE
;Z:0.7
;HEIGHT:0.7
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.7

G10 ; retract
G1 Z.7 F10800
;AFTER_LAYER_CHANGE
;0.7
M800 F"layer"
G1 X143.134 Y137.218
G11 ; unretract
M204 P1000
;TYPE:Skirt/Brim
;WIDTH:1.5
G1 F952.537
G1 X145 Y136.65 E.7357
G1 X185 Y136.65 E15.08432
G1 X186.576 Y137.044 E.61271
G1 X187.782 Y138.134 E.61271
G1 X188.35 Y140 E.7357
G1 X188.35 Y180 E15.08432
G1 X187.956 Y181.576 E.61271
G1 X186.866 Y182.782 E.61271
G1 X185 Y183.35 E.7357
G1 X145 Y183.35 E15.08432
G1 X143.424 Y182.956 E.61271
G1 X142.218 Y181.866 E.61271
G1 X141.65 Y180 E.7357
G1 X141.65 Y140 E15.08432
G1 X142.044 Y138.424 E.61271
G1 X142.993 Y137.374 E.53352
G10 ; retract
G1 X147.3 Y142.3 F10800
G11 ; unretract
;TYPE:Perimeter
G1 F952.537
G1 X182.7 Y142.3 E13.34979
G1 X182.7 Y177.7 E13.34979
G1 X147.3 Y177.7 E13.34979
G1 X147.3 Y142.51 E13.2706
G10 ; retract
G1 X145.95 Y140.95 F10800
G11 ; unretract
;TYPE:External perimeter
G1 F952.537
G1 X184.05 Y140.95 E14.36782
G1 X184.05 Y179.05 E14.36782
G1 X145.95 Y179.05 E14.36782
G1 X145.95 Y141.16 E14.28863
G1 X147.302 Y141.312 F10800
G10 ; retract
G1 X179.536 Y142.705
G11 ; unretract
;TYPE:Solid infill
;WIDTH:1.51437
G1 F942.503
G1 X181.688 Y144.856 E1.15963
G1 X181.688 Y146.785 E.73526
G1 X178.215 Y143.312 E1.87207
G1 X176.285 Y143.312 E.73526
G1 X181.688 Y148.715 E2.91188
G1 X181.688 Y150.644 E.73526
G1 X174.356 Y143.312 E3.9517
G1 X172.427 Y143.312 E.73526
G1 X181.688 Y152.573 E4.99152
G1 X181.688 Y154.502 E.73526
G1 X170.498 Y143.312 E6.03133
G1 X168.569 Y143.312 E.73526
G1 X181.688 Y156.431 E7.07115
G1 X181.688 Y158.361 E.73526
G1 X166.639 Y143.312 E8.11097
G1 X164.71 Y143.312 E.73526
G1 X181.688 Y160.29 E9.15078
G1 X181.688 Y162.219 E.73526
G1 X162.781 Y143.312 E10.1906
G1 X160.852 Y143.312 E.73526
G1 X181.688 Y164.148 E11.23042
G1 X181.688 Y166.077 E.73526
G1 X158.923 Y143.312 E12.27023
G1 X156.993 Y143.312 E.73526
G1 X181.688 Y168.007 E13.31005
G1 X181.688 Y169.936 E.73526
G1 X155.064 Y143.312 E14.34987
G1 X153.135 Y143.312 E.73526
G1 X181.688 Y171.865 E15.38968
G1 X181.688 Y173.794 E.73526
G1 X151.206 Y143.312 E16.4295
G1 X149.277 Y143.312 E.73526
G1 X181.688 Y175.723 E17.46932
G1 X181.688 Y176.688 E.36761
G1 X180.723 Y176.688 E.36765
G1 X148.312 Y144.277 E17.46925
G1 X148.312 Y146.206 E.73526
G1 X178.794 Y176.688 E16.42944
G1 X176.865 Y176.688 E.73526
G1 X148.312 Y148.135 E15.38962
G1 X148.312 Y150.064 E.73526
G1 X174.936 Y176.688 E14.3498
G1 X173.006 Y176.688 E.73526
G1 X148.312 Y151.994 E13.30999
G1 X148.312 Y153.923 E.73526
G1 X171.077 Y176.688 E12.27017
G1 X169.148 Y176.688 E.73526
G1 X148.312 Y155.852 E11.23035
G1 X148.312 Y157.781 E.73526
G1 X167.219 Y176.688 E10.19054
G1 X165.29 Y176.688 E.73526
G1 X148.312 Y159.71 E9.15072
G1 X148.312 Y161.64 E.73526
G1 X163.36 Y176.688 E8.1109
G1 X161.431 Y176.688 E.73526
G1 X148.312 Y163.569 E7.07108
G1 X148.312 Y165.498 E.73526
G1 X159.502 Y176.688 E6.03127
G1 X157.573 Y176.688 E.73526
G1 X148.312 Y167.427 E4.99145
G1 X148.312 Y169.356 E.73526
G1 X155.644 Y176.688 E3.95163
G1 X153.714 Y176.688 E.73526
G1 X148.312 Y171.286 E2.91182
G1 X148.312 Y173.215 E.73526
G1 X151.785 Y176.688 E1.872
G1 X149.856 Y176.688 E.73526
G1 X147.705 Y174.537 E1.15957
G10 ; retract
M107
;TYPE:Custom
; Filament-specific end gcode
M106 S0 ; turn off cooling fan
G10 P0 S0 R0
G10 P1 S0 R0
M140 S0; turn off bed
;Drop the bed
G91
G1 Z10 F1000
G90
M0
; filament used [mm] = 0, 514.86
; filament used [cm3] = 0, 1.24
; filament used [g] = 0, 1.54
; filament cost = 0, 0.04
; total filament used [g] = 1.54
; total filament cost = 0.04
; estimated printing time (normal mode) = 1m 29s

; prusaslicer_config = begin
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = G:\\Rancor\\Rancor\\PrusaSlicer\\BedModel.stl
; bed_custom_texture = G:\\Rancor\\Rancor\\PrusaSlicer\\BedTexture.png
; bed_shape = 0x0,330x0,330x320,0x320
; bed_temperature = 0,60
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 3
; bottom_solid_min_thickness = 0.5
; bridge_acceleration = 1000
; bridge_angle = 0
; bridge_fan_speed = 100,100
; bridge_flow_ratio = 0.95
; bridge_speed = 30
; brim_separation = 0
; brim_type = outer_only
; brim_width = 0
; clip_multipart_objects = 1
; color_change_gcode = M600
; complete_objects = 0
; cooling = 0,1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 1000
; default_filament_profile = ""
; default_print_profile = 
; deretract_speed = 0,0
; disable_fan_first_layers = 1,1
; dont_support_bridges = 1
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0.2
; end_filament_gcode = ;"; Filament-specific end gcode"
; end_gcode = M106 S0 ; turn off cooling fan\nG10 P0 S0 R0\nG10 P1 S0 R0\nM140 S0; turn off bed\n;Drop the bed\nG91\nG1 Z10 F1000\nG90\nM0
; ensure_vertical_shell_thickness = 1
; external_perimeter_extrusion_width = 1.5
; external_perimeter_speed = 35
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 45
; extruder_colour = #FF8000;#0000FF
; extruder_offset = 0x0,0x0
; extrusion_axis = E
; extrusion_multiplier = 1,0.96
; extrusion_width = 1.5
; fan_always_on = 0,1
; fan_below_layer_time = 100,100
; filament_colour = #FF8000;#FF8000
; filament_cooling_final_speed = 3.4,3.4
; filament_cooling_initial_speed = 2.2,2.2
; filament_cooling_moves = 4,4
; filament_cost = 0,24.99
; filament_density = 0,1.24
; filament_diameter = 1.75,1.75
; filament_load_time = 0,0
; filament_loading_speed = 28,28
; filament_loading_speed_start = 3,3
; filament_max_volumetric_speed = 15,15
; filament_minimal_purge_on_wipe_tower = 15,15
; filament_notes = ;"Affordable filament for everyday printing in premium quality manufactured in-house by Josef Prusa"
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6";"120 100| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = !Off;PLA
; filament_soluble = 0,0
; filament_spool_weight = 0,0
; filament_toolchange_delay = 0,0
; filament_type = PLA;PLA
; filament_unload_time = 0,0
; filament_unloading_speed = 90,90
; filament_unloading_speed_start = 100,100
; filament_vendor = Prusa Polymers
; fill_angle = 45
; fill_density = 15%
; fill_pattern = grid
; first_layer_acceleration = 1000
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 0,60
; first_layer_extrusion_width = 1.5
; first_layer_height = 0.7
; first_layer_speed = 20
; first_layer_speed_over_raft = 30
; first_layer_temperature = 0,210
; full_fan_speed_layer = 0,0
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 40
; gcode_comments = 0
; gcode_flavor = reprapfirmware
; gcode_label_objects = 0
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = duet
; infill_acceleration = 1000
; infill_anchor = 600%
; infill_anchor_max = 50
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 1.5
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 85
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]\nM800 F"layer"
; layer_height = 0.7
; machine_limits_usage = time_estimate_only
; machine_max_acceleration_e = 1500,1500
; machine_max_acceleration_extruding = 1500,1500
; machine_max_acceleration_retracting = 1500,1500
; machine_max_acceleration_travel = 500,1250
; machine_max_acceleration_x = 500,500
; machine_max_acceleration_y = 500,500
; machine_max_acceleration_z = 100,100
; machine_max_feedrate_e = 60,60
; machine_max_feedrate_x = 180,180
; machine_max_feedrate_y = 180,180
; machine_max_feedrate_z = 15,15
; machine_max_jerk_e = 25,25
; machine_max_jerk_x = 6.7,6.7
; machine_max_jerk_y = 6.7,6.7
; machine_max_jerk_z = 1.7,1.7
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100,100
; max_layer_height = 0,0
; max_print_height = 601
; max_print_speed = 200
; max_volumetric_speed = 0
; min_fan_speed = 100,100
; min_layer_height = 0.07,0.07
; min_print_speed = 15,15
; min_skirt_length = 4
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 1.4,1.4
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_T0-{filament_preset[0]}_T1-{filament_preset[1]}.gcode
; overhangs = 0
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 800
; perimeter_extruder = 1
; perimeter_extrusion_width = 1.5
; perimeter_speed = 50
; perimeters = 2
; physical_printer_settings_id = Printer 1
; post_process = 
; print_settings_id = N1.4 0.7mm SPEED
; printer_model = 
; printer_notes = 
; printer_settings_id = Rancor
; printer_technology = FFF
; printer_variant = 
; printer_vendor = 
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 0
; resolution = 0
; retract_before_travel = 2,2
; retract_before_wipe = 70%,70%
; retract_layer_change = 1,1
; retract_length = 0.5,0.5
; retract_length_toolchange = 0,0
; retract_lift = 0,0
; retract_lift_above = 0,0
; retract_lift_below = 600,600
; retract_restart_extra = 0,0
; retract_restart_extra_toolchange = 0,0
; retract_speed = 40,40
; seam_position = nearest
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 0
; skirt_distance = 2
; skirt_height = 3
; skirts = 1
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 20,20
; small_perimeter_speed = 30
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 1.5
; solid_infill_speed = 80
; spiral_vase = 0
; standby_temperature_delta = 170
; start_filament_gcode = ;"; Filament-specific start gcode\nM703"
; start_gcode = ;Begin Start GCode\n\n;set temps\nG10 P0 S{temperature[0]}\nG10 P0 R{if temperature[0] == 0}0{else}{temperature[0] - 40}{endif}\nG10 P1 S{temperature[1]}\nG10 P1 R{if temperature[1] == 0}0{else}{temperature[1] - 40}{endif}\n\nG28 ;home all axis\nG29 S1 ;enable mesh\n\n{ if current_extruder == 0 }\nT0\n{ elsif current_extruder == 1 } \nT1\n{ endif }\n\nM116 ;Wait for all temps\n\nG90\nM98 P"prime.g"\n;End Start GCode
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = -1
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.1
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.38
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 2
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 45
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 55
; support_material_with_sheath = 0
; support_material_xy_spacing = 50%
; temperature = 0,210
; template_custom_gcode = 
; thick_bridges = 1
; thin_walls = 0
; threads = 32
; thumbnails = 128x128
; toolchange_gcode = ;T[next_extruder]
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 1.4
; top_solid_infill_speed = 40
; top_solid_layers = 5
; top_solid_min_thickness = 0.6
; travel_speed = 180
; travel_speed_z = 0
; use_firmware_retraction = 1
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wipe = 0,0
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 170
; wipe_tower_y = 125
; wiping_volumes_extruders = 70,70,70,70
; wiping_volumes_matrix = 0,140,140,0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
