M48
; DRILL file {KiCad (6.0.4)} date Thu Apr  7 16:51:45 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-04-07T16:51:45-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.600
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.800
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.950
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C2.700
%
G90
G05
T1
X80.0Y-69.0
X80.0Y-83.0
T2
X64.25Y-79.0
X67.75Y-79.0
T3
X64.75Y-95.025
X67.25Y-95.025
X69.75Y-95.025
X72.25Y-95.025
T4
X74.0Y-59.0
X74.0Y-81.0
T0
M30
