; tpost1.g
; called after tool 1 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.3.10 on Mon Feb 14 2022 00:04:11 GMT-0500 (Eastern Standard Time)
; Wait for set temperatures to be reached
M116 P1

G91
G1 U-10 F6000
G90